=== metasfresh/metasfresh/misc/services/camel/de-metas-camel-externalsystems/com-adekia-exchange/com.adekia.exchange-model/model/UBL-2.3-JSON-v1.0-cn01/json-schema-model/maindoc/UBL-TransportServiceDescription-2.3.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "json-schema-model/maindoc/UBL-TransportServiceDescription-2.3.json",
  "description": "\n  Library:           OASIS Universal Business Language (UBL) 2.3 OS\n                     http://docs.oasis-open.org/ubl/os-UBL-2.3/\n  Release Date:      15 June 2021\n  Module:            json-schema-model/maindoc/UBL-TransportServiceDescription-2.3.json\n  Generated on:      2021-12-15 21:56z\n  Copyright (c) OASIS Open 2021. All Rights Reserved.\n\n\n  OASIS takes no position regarding the validity or scope of any \n  intellectual property or other rights that might be claimed to pertain \n  to the implementation or use of the technology described in this \n  document or the extent to which any license under such rights \n  might or might not be available; neither does it represent that it has \n  made any effort to identify any such rights. Information on OASIS's \n  procedures with respect to rights in OASIS specifications can be \n  found at the OASIS website. Copies of claims of rights made \n  available for publication and any assurances of licenses to be made \n  available, or the result of an attempt made to obtain a general \n  license or permission for the use of such proprietary rights by \n  implementors or users of this specification, can be obtained from \n  the OASIS Executive Director.\n\n  OASIS invites any interested party to bring to its attention any \n  copyrights, patents or patent applications, or other proprietary \n  rights which may cover technology that may be required to \n  implement this specification. Please address the information to the \n  OASIS Executive Director.\n  \n  This document and translations of it may be copied and furnished to \n  others, and derivative works that comment on or otherwise explain \n  it or assist in its implementation may be prepared, copied, \n  published and distributed, in whole or in part, without restriction of \n  any kind, provided that the above copyright notice and this \n  paragraph are included on all such copies and derivative works. \n  However, this document itself may not be modified in any way, \n  such as by removing the copyright notice or references to OASIS, \n  except as needed for the purpose of developing OASIS \n  specifications, in which case the procedures for copyrights defined \n  in the OASIS Intellectual Property Rights document must be \n  followed, or as required to translate it into languages other than \n  English. \n\n  The limited permissions granted above are perpetual and will not be \n  revoked by OASIS or its successors or assigns. \n\n  This document and the information contained herein is provided on \n  an \"AS IS\" basis and OASIS DISCLAIMS ALL WARRANTIES, \n  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO ANY \n  WARRANTY THAT THE USE OF THE INFORMATION HEREIN \n  WILL NOT INFRINGE ANY RIGHTS OR ANY IMPLIED \n  WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A \n  PARTICULAR PURPOSE.    \n",
  "required": [
    "TransportServiceDescription"
    ],
  "properties": {
    "_D": {
      "description": "Document ABIE XML namespace string",
      "type": "string"
      },
    "_A": {
      "description": "Library ABIE XML namespace string (for ASBIEs)",
      "type": "string"
      },
    "_B": {
      "description": "BBIE XML namespace string",
      "type": "string"
      },
    "_E": {
      "description": "Extension scaffolding XML namespace string",
      "type": "string"
      },
    "TransportServiceDescription": {
      "description": "A document sent by a transport service provider to announce the availability of a transport service.",
      "$ref": "#/definitions/TransportServiceDescription"
      }
    },
  "additionalProperties": false,
  "type": "object",
  "definitions": {
    "TransportServiceDescription": {
      "title": "Transport Service Description. Details",
      "description": "A document sent by a transport service provider to announce the availability of a transport service.",
      "required": [
        "ID"
        ],
      "properties": {

        "UBLExtensions": {
          "title": "UBLExtensions",
          "description": "An optional set of extensions to the committee model",
          "items": { 
            "$ref": "../common/UBL-CommonExtensionComponents-2.3.json#/definitions/UBLExtensions" },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },

        "UBLVersionID": {
          "title": "Transport Service Description. UBL Version Identifier. Identifier",
          "description": "Identifies the earliest version of the UBL 2 schema for this document type that defines all of the elements that might be encountered in the current instance.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/UBLVersionID"
          },
        "CustomizationID": {
          "title": "Transport Service Description. Customization Identifier. Identifier",
          "description": "Identifies a user-defined customization of UBL for a specific use.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/CustomizationID"
          },
        "ProfileID": {
          "title": "Transport Service Description. Profile Identifier. Identifier",
          "description": "Identifies a user-defined profile of the customization of UBL being used.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ProfileID"
          },
        "ProfileExecutionID": {
          "title": "Transport Service Description. Profile Execution Identifier. Identifier",
          "description": "Identifies an instance of executing a profile, to associate all transactions in a collaboration.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ProfileExecutionID"
          },
        "ID": {
          "title": "Transport Service Description. Identifier",
          "description": "An identifier for this document, assigned by the sender.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ID"
          },
        "CopyIndicator": {
          "title": "Transport Service Description. Copy_ Indicator. Indicator",
          "description": "Indicates whether this document is a copy (true) or not (false).",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/CopyIndicator"
          },
        "UUID": {
          "title": "Transport Service Description. UUID. Identifier",
          "description": "A universally unique identifier for an instance of this document.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/UUID"
          },
        "IssueDate": {
          "title": "Transport Service Description. Issue Date. Date",
          "description": "The date, assigned by the sender, on which this document was issued.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/IssueDate"
          },
        "IssueTime": {
          "title": "Transport Service Description. Issue Time. Time",
          "description": "The time, assigned by the sender, at which this document was issued.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/IssueTime"
          },
        "Note": {
          "title": "Transport Service Description. Note. Text",
          "description": "Free-form text pertinent to this document, conveying information that is not contained explicitly in other structures.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/Note"
            },
          "minItems": 1,
          "type": "array"
          },
        "ServiceName": {
          "title": "Transport Service Description. Service Name. Name",
          "description": "A name, assigned by the Transport Service Provider, for the service being announced.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ServiceName"
          },
        "ResponseCode": {
          "title": "Transport Service Description. Response Code. Code",
          "description": "A code signifying a response related to the Transport Service Description.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ResponseCode"
          },
        "Signature": {
          "title": "Transport Service Description. Signature",
          "description": "A signature applied to this document.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/Signature"
            },
          "minItems": 1,
          "type": "array"
          },
        "SenderParty": {
          "title": "Transport Service Description. Sender_ Party. Party",
          "description": "The party sending the Transport Service Description.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/SenderParty"
          },
        "ReceiverParty": {
          "title": "Transport Service Description. Receiver_ Party. Party",
          "description": "The party receiving the Transport Service Description.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/ReceiverParty"
          },
        "TransportServiceDescriptionRequestDocumentReference": {
          "title": "Transport Service Description. Transport Service Description Request_ Document Reference. Document Reference",
          "description": "A Transport Service Description Request to which this Transport Service Description is a response.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/TransportServiceDescriptionRequestDocumentReference"
          },
        "TransportServiceProviderParty": {
          "title": "Transport Service Description. Transport Service Provider_ Party. Party",
          "description": "The transport service provider.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/TransportServiceProviderParty"
          },
        "ServiceChargePaymentTerms": {
          "title": "Transport Service Description. Service Charge_ Payment Terms. Payment Terms",
          "description": "The terms of payment under which the transport service would be provided.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/ServiceChargePaymentTerms"
          },
        "ValidityPeriod": {
          "title": "Transport Service Description. Validity_ Period. Period",
          "description": "A period during which this Transport Service Description is valid.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/ValidityPeriod"
          },
        "TransportationService": {
          "title": "Transport Service Description. Transportation Service",
          "description": "A transportation service announced in this Transport Service Description.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/TransportationService"
            },
          "minItems": 1,
          "type": "array"
          }
        },
      "additionalProperties": false,
      "type": "object"
      }
    }
  }

=== metasfresh/metasfresh/misc/services/camel/de-metas-camel-externalsystems/com-adekia-exchange/com.adekia.exchange-model/model/UBL-2.3-JSON-v1.0-cn01/json-model/UBL-TransportServiceDescription-2.1-Example.json
{"_D":"urn:oasis:names:specification:ubl:schema:xsd:TransportServiceDescription-2",
 "_A":"urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2",
 "_B":"urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2",
 "TransportServiceDescription":{
 "UBLVersionID":{"_":"2.1"},
 "ID":{"_":"TSD_RESP_1"},
 "IssueDate":{"_":"2011-09-12"},
 "IssueTime":{"_":"11:01:10+01:00"},
 "SenderParty":{
  "PartyIdentification":[{
   "ID":{"_":"4058673827641",
    "schemeAgencyName":"GS1",
    "schemeName":"GLN"}
  }],
  "PartyName":[{
   "Name":{"_":"NECOSS"}
  }],
  "Contact":{
   "Name":{"_":"SomeName"},
   "Telephone":{"_":"+49450557000"},
   "ElectronicMail":{"_":"SomeName@necoss.de"}
  }
 },
 "ReceiverParty":{
  "PartyIdentification":[{
   "ID":{"_":"4058673827000",
    "schemeAgencyName":"GS1",
    "schemeName":"GLN"}
  }],
  "PartyName":[{
   "Name":{"_":"Consignor"}
  }],
  "Contact":{
   "Name":{"_":"SomeName"},
   "Telephone":{"_":"+8687878763"},
   "ElectronicMail":{"_":"SomeName@consignor.cn"}
  }
 },
 "TransportServiceDescriptionRequestDocumentReference":{
  "ID":{"_":"TSD_REQ_1"}
 },
 "TransportServiceProviderParty":{
  "PartyIdentification":[{
   "ID":{"_":"4058673827641",
    "schemeAgencyName":"GS1",
    "schemeName":"GLN"}
  }],
  "PartyName":[{
   "Name":{"_":"NECOSS"}
  }],
  "Contact":{
   "Name":{"_":"SomeName"},
   "Telephone":{"_":"+49450557000"},
   "ElectronicMail":{"_":"SomeName@necoss.de"}
  }
 },
 "ServiceChargePaymentTerms":{
  "Amount":{"_":2500,
   "currencyID":"EUR"},
  "PaymentDueDate":{"_":"2011-11-06"}
 },
 "ValidityPeriod":{
  "StartDate":{"_":"2011-09-12"},
  "EndDate":{"_":"2011-09-30"},
  "EndTime":{"_":"16:00:00+01:00"}
 },
 "TransportationService":[{
  "TransportServiceCode":{"_":"3"},
  "SupportedTransportEquipment":[{
   "ID":{"_":"1"},
   "TransportEquipmentTypeCode":{"_":"CN"},
   "MeasurementDimension":[{
    "AttributeID":{"_":"Length"},
    "Measure":{"_":6.1,
     "unitCode":"MTR"}
   },{
    "AttributeID":{"_":"Height"},
    "Measure":{"_":2.6,
     "unitCode":"MTR"}
   },{
    "AttributeID":{"_":"Width"},
    "Measure":{"_":2.44,
     "unitCode":"MTR"}
   }]
  },{
   "ID":{"_":"1"},
   "TransportEquipmentTypeCode":{"_":"CN"},
   "MeasurementDimension":[{
    "AttributeID":{"_":"Length"},
    "Measure":{"_":6.1,
     "unitCode":"MTR"}
   },{
    "AttributeID":{"_":"Height"},
    "Measure":{"_":2.6,
     "unitCode":"MTR"}
   },{
    "AttributeID":{"_":"Width"},
    "Measure":{"_":2.44,
     "unitCode":"MTR"}
   }]
  }],
  "ShipmentStage":[{
   "ID":{"_":"1"},
   "PlannedDepartureTransportEvent":{
    "Location":{
     "Address":{
      "ID":{"_":"DEHAM",
       "schemeAgencyName":"UN",
       "schemeName":"UN/LOCODE"},
      "StreetName":{"_":"Neuer Wandrahm 4"},
      "CityName":{"_":"Hamburg"},
      "Country":{
       "IdentificationCode":{"_":"DE"}
      }
     }
    },
    "Period":[{
     "StartDate":{"_":"2011-10-03"},
     "StartTime":{"_":"09:30:10+01:00"},
     "EndDate":{"_":"2011-10-03"},
     "EndTime":{"_":"12:30:10+01:00"}
    }]
   },
   "PlannedArrivalTransportEvent":{
    "Location":{
     "LocationTypeCode":{"_":"13"},
     "Address":{
      "ID":{"_":"4568763527610",
       "schemeAgencyName":"GS1",
       "schemeName":"GLN"},
      "StreetName":{"_":"Ludwig-Erhard-Str. 15"},
      "CityName":{"_":"Bremen"},
      "Country":{
       "IdentificationCode":{"_":"DE"}
      }
     }
    },
    "Period":[{
     "StartDate":{"_":"2011-10-03"},
     "StartTime":{"_":"18:30:10+01:00"},
     "EndDate":{"_":"2011-10-03"},
     "EndTime":{"_":"21:30:10+01:00"}
    }]
   }
  },{
   "ID":{"_":"2"},
   "PlannedDepartureTransportEvent":{
    "Location":{
     "LocationTypeCode":{"_":"13"},
     "Address":{
      "ID":{"_":"4568763527610",
       "schemeAgencyName":"GS1",
       "schemeName":"GLN"},
      "StreetName":{"_":"Ludwig-Erhard-Str. 15"},
      "CityName":{"_":"Bremen"},
      "Country":{
       "IdentificationCode":{"_":"DE"}
      }
     }
    },
    "Period":[{
     "StartDate":{"_":"2011-10-04"},
     "StartTime":{"_":"09:30:10+01:00"},
     "EndDate":{"_":"2011-10-04"},
     "EndTime":{"_":"09:30:10+01:00"}
    }]
   },
   "PlannedArrivalTransportEvent":{
    "Location":{
     "LocationTypeCode":{"_":"13"},
     "Address":{
      "StreetName":{"_":"Sandstr. 38-40"},
      "CityName":{"_":"Nurnberg"},
      "Country":{
       "IdentificationCode":{"_":"DE"}
      }
     }
    },
    "Period":[{
     "StartDate":{"_":"2011-10-04"},
     "StartTime":{"_":"15:30:10+01:00"},
     "EndDate":{"_":"2011-10-04"},
     "EndTime":{"_":"18:30:10+01:00"}
    }]
   }
  },{
   "ID":{"_":"3"},
   "PlannedDepartureTransportEvent":{
    "Location":{
     "LocationTypeCode":{"_":"13"},
     "Address":{
      "StreetName":{"_":"Sandstr. 38-40"},
      "CityName":{"_":"Nurnberg"},
      "Country":{
       "IdentificationCode":{"_":"DE"}
      }
     }
    },
    "Period":[{
     "StartDate":{"_":"2011-10-06"},
     "StartTime":{"_":"09:30:10+01:00"},
     "EndDate":{"_":"2011-10-06"},
     "EndTime":{"_":"12:30:10+01:00"}
    }]
   },
   "PlannedArrivalTransportEvent":{
    "Location":{
     "Address":{
      "StreetName":{"_":"Grosse strasse 34"},
      "CityName":{"_":"Nurnberg"},
      "Country":{
       "IdentificationCode":{"_":"DE"}
      }
     }
    },
    "Period":[{
     "StartDate":{"_":"2011-10-06"},
     "StartTime":{"_":"12:30:10+01:00"},
     "EndDate":{"_":"2011-10-06"},
     "EndTime":{"_":"15:30:10+01:00"}
    }]
   }
  }]
 }]
}}
