=== metasfresh/metasfresh/misc/services/camel/de-metas-camel-externalsystems/com-adekia-exchange/com.adekia.exchange-model/model/UBL-2.3-JSON-v1.0-cn01/json-schema-model/maindoc/UBL-OrderChange-2.3.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "json-schema-model/maindoc/UBL-OrderChange-2.3.json",
  "description": "\n  Library:           OASIS Universal Business Language (UBL) 2.3 OS\n                     http://docs.oasis-open.org/ubl/os-UBL-2.3/\n  Release Date:      15 June 2021\n  Module:            json-schema-model/maindoc/UBL-OrderChange-2.3.json\n  Generated on:      2021-12-15 21:56z\n  Copyright (c) OASIS Open 2021. All Rights Reserved.\n\n\n  OASIS takes no position regarding the validity or scope of any \n  intellectual property or other rights that might be claimed to pertain \n  to the implementation or use of the technology described in this \n  document or the extent to which any license under such rights \n  might or might not be available; neither does it represent that it has \n  made any effort to identify any such rights. Information on OASIS's \n  procedures with respect to rights in OASIS specifications can be \n  found at the OASIS website. Copies of claims of rights made \n  available for publication and any assurances of licenses to be made \n  available, or the result of an attempt made to obtain a general \n  license or permission for the use of such proprietary rights by \n  implementors or users of this specification, can be obtained from \n  the OASIS Executive Director.\n\n  OASIS invites any interested party to bring to its attention any \n  copyrights, patents or patent applications, or other proprietary \n  rights which may cover technology that may be required to \n  implement this specification. Please address the information to the \n  OASIS Executive Director.\n  \n  This document and translations of it may be copied and furnished to \n  others, and derivative works that comment on or otherwise explain \n  it or assist in its implementation may be prepared, copied, \n  published and distributed, in whole or in part, without restriction of \n  any kind, provided that the above copyright notice and this \n  paragraph are included on all such copies and derivative works. \n  However, this document itself may not be modified in any way, \n  such as by removing the copyright notice or references to OASIS, \n  except as needed for the purpose of developing OASIS \n  specifications, in which case the procedures for copyrights defined \n  in the OASIS Intellectual Property Rights document must be \n  followed, or as required to translate it into languages other than \n  English. \n\n  The limited permissions granted above are perpetual and will not be \n  revoked by OASIS or its successors or assigns. \n\n  This document and the information contained herein is provided on \n  an \"AS IS\" basis and OASIS DISCLAIMS ALL WARRANTIES, \n  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO ANY \n  WARRANTY THAT THE USE OF THE INFORMATION HEREIN \n  WILL NOT INFRINGE ANY RIGHTS OR ANY IMPLIED \n  WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A \n  PARTICULAR PURPOSE.    \n",
  "required": [
    "OrderChange"
    ],
  "properties": {
    "_D": {
      "description": "Document ABIE XML namespace string",
      "type": "string"
      },
    "_A": {
      "description": "Library ABIE XML namespace string (for ASBIEs)",
      "type": "string"
      },
    "_B": {
      "description": "BBIE XML namespace string",
      "type": "string"
      },
    "_E": {
      "description": "Extension scaffolding XML namespace string",
      "type": "string"
      },
    "OrderChange": {
      "description": "A document used to specify changes to an existing Order.",
      "$ref": "#/definitions/OrderChange"
      }
    },
  "additionalProperties": false,
  "type": "object",
  "definitions": {
    "OrderChange": {
      "title": "Order Change. Details",
      "description": "A document used to specify changes to an existing Order.",
      "required": [
        "IssueDate",
        "SequenceNumberID",
        "OrderReference",
        "BuyerCustomerParty",
        "SellerSupplierParty",
        "OrderLine"
        ],
      "properties": {

        "UBLExtensions": {
          "title": "UBLExtensions",
          "description": "An optional set of extensions to the committee model",
          "items": { 
            "$ref": "../common/UBL-CommonExtensionComponents-2.3.json#/definitions/UBLExtensions" },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },

        "UBLVersionID": {
          "title": "Order Change. UBL Version Identifier. Identifier",
          "description": "Identifies the earliest version of the UBL 2 schema for this document type that defines all of the elements that might be encountered in the current instance.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/UBLVersionID"
          },
        "CustomizationID": {
          "title": "Order Change. Customization Identifier. Identifier",
          "description": "Identifies a user-defined customization of UBL for a specific use.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/CustomizationID"
          },
        "ProfileID": {
          "title": "Order Change. Profile Identifier. Identifier",
          "description": "Identifies a user-defined profile of the customization of UBL being used.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ProfileID"
          },
        "ProfileExecutionID": {
          "title": "Order Change. Profile Execution Identifier. Identifier",
          "description": "Identifies an instance of executing a profile, to associate all transactions in a collaboration.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ProfileExecutionID"
          },
        "ID": {
          "title": "Order Change. Identifier",
          "description": "An identifier for this document, assigned by the sender.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ID"
          },
        "SalesOrderID": {
          "title": "Order Change. Sales_ Order Identifier. Identifier",
          "description": "An identifier for the Order Change, assigned by the seller.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/SalesOrderID"
          },
        "CopyIndicator": {
          "title": "Order Change. Copy_ Indicator. Indicator",
          "description": "Indicates whether this document is a copy (true) or not (false).",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/CopyIndicator"
          },
        "UUID": {
          "title": "Order Change. UUID. Identifier",
          "description": "A universally unique identifier for an instance of this document.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/UUID"
          },
        "IssueDate": {
          "title": "Order Change. Issue Date. Date",
          "description": "The date, assigned by the sender, on which this document was issued.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/IssueDate"
          },
        "IssueTime": {
          "title": "Order Change. Issue Time. Time",
          "description": "The time, assigned by the sender, at which this document was issued.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/IssueTime"
          },
        "SequenceNumberID": {
          "title": "Order Change. Sequence Number. Identifier",
          "description": "The Order Change Sequence Number assigned by the Buyer to ensure the proper sequencing of changes.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/SequenceNumberID"
          },
        "Note": {
          "title": "Order Change. Note. Text",
          "description": "Free-form text pertinent to this document, conveying information that is not contained explicitly in other structures.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/Note"
            },
          "minItems": 1,
          "type": "array"
          },
        "RequestedInvoiceCurrencyCode": {
          "title": "Order Change. Requested Invoice_ Currency Code. Code",
          "description": "A code signifying he currency requested for amount totals in Invoices related to this Order Change.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/RequestedInvoiceCurrencyCode"
          },
        "DocumentCurrencyCode": {
          "title": "Order Change. Document_ Currency Code. Code",
          "description": "A code signifying the default currency for this document.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/DocumentCurrencyCode"
          },
        "PricingCurrencyCode": {
          "title": "Order Change. Pricing_ Currency Code. Code",
          "description": "A code signifying the currency that is used for all prices in the Order Change.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/PricingCurrencyCode"
          },
        "TaxCurrencyCode": {
          "title": "Order Change. Tax_ Currency Code. Code",
          "description": "A code signifying the currency requested for tax amounts in Invoices related to this Order Change.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/TaxCurrencyCode"
          },
        "CustomerReference": {
          "title": "Order Change. Customer_ Reference. Text",
          "description": "A supplementary reference for the transaction (e.g., CRI when using purchasing card).",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/CustomerReference"
          },
        "AccountingCostCode": {
          "title": "Order Change. Accounting Cost Code. Code",
          "description": "The buyer's accounting code, applied to the Order Change as a whole.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/AccountingCostCode"
          },
        "AccountingCost": {
          "title": "Order Change. Accounting Cost. Text",
          "description": "The buyer's accounting code, applied to the Order Change as a whole, expressed as text.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/AccountingCost"
          },
        "LineCountNumeric": {
          "title": "Order Change. Line Count. Numeric",
          "description": "The number of Order Change lines in the document.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/LineCountNumeric"
          },
        "ValidityPeriod": {
          "title": "Order Change. Validity_ Period. Period",
          "description": "A period during which the Order Change is valid.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/ValidityPeriod"
            },
          "minItems": 1,
          "type": "array"
          },
        "OrderReference": {
          "title": "Order Change. Order Reference",
          "description": "A reference to the Order being changed.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/OrderReference"
          },
        "QuotationDocumentReference": {
          "title": "Order Change. Quotation_ Document Reference. Document Reference",
          "description": "A reference to a Quotation.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/QuotationDocumentReference"
          },
        "OriginatorDocumentReference": {
          "title": "Order Change. Originator_ Document Reference. Document Reference",
          "description": "A reference to an originator document associated with this document.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/OriginatorDocumentReference"
          },
        "AdditionalDocumentReference": {
          "title": "Order Change. Additional_ Document Reference. Document Reference",
          "description": "A reference to an additional document associated with this document.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/AdditionalDocumentReference"
            },
          "minItems": 1,
          "type": "array"
          },
        "Contract": {
          "title": "Order Change. Contract",
          "description": "A contract associated with the Order being changed.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/Contract"
            },
          "minItems": 1,
          "type": "array"
          },
        "Signature": {
          "title": "Order Change. Signature",
          "description": "A signature applied to this document.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/Signature"
            },
          "minItems": 1,
          "type": "array"
          },
        "BuyerCustomerParty": {
          "title": "Order Change. Buyer_ Customer Party. Customer Party",
          "description": "The buyer.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/BuyerCustomerParty"
          },
        "SellerSupplierParty": {
          "title": "Order Change. Seller_ Supplier Party. Supplier Party",
          "description": "The seller.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/SellerSupplierParty"
          },
        "OriginatorCustomerParty": {
          "title": "Order Change. Originator_ Customer Party. Customer Party",
          "description": "The originator.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/OriginatorCustomerParty"
          },
        "FreightForwarderParty": {
          "title": "Order Change. Freight Forwarder_ Party. Party",
          "description": "A freight forwarder or carrier.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/FreightForwarderParty"
          },
        "AccountingCustomerParty": {
          "title": "Order Change. Accounting_ Customer Party. Customer Party",
          "description": "The accounting customer party.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/AccountingCustomerParty"
          },
        "AccountingSupplierParty": {
          "title": "Order Change. Accounting_ Supplier Party. Supplier Party",
          "description": "The accounting supplier party.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/AccountingSupplierParty"
          },
        "Delivery": {
          "title": "Order Change. Delivery",
          "description": "A delivery associated with this document.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/Delivery"
            },
          "minItems": 1,
          "type": "array"
          },
        "DeliveryTerms": {
          "title": "Order Change. Delivery Terms",
          "description": "A set of delivery terms associated with this document.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/DeliveryTerms"
          },
        "PaymentMeans": {
          "title": "Order Change. Payment Means",
          "description": "Expected means of payment.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/PaymentMeans"
            },
          "minItems": 1,
          "type": "array"
          },
        "PaymentTerms": {
          "title": "Order Change. Payment Terms",
          "description": "A set of payment terms associated with this document.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/PaymentTerms"
            },
          "minItems": 1,
          "type": "array"
          },
        "TransactionConditions": {
          "title": "Order Change. Transaction Conditions",
          "description": "Purchasing, sales, or payment conditions applying to the whole Order being changed.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/TransactionConditions"
          },
        "AllowanceCharge": {
          "title": "Order Change. Allowance Charge",
          "description": "A discount or charge that applies to a price component.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/AllowanceCharge"
            },
          "minItems": 1,
          "type": "array"
          },
        "TaxExchangeRate": {
          "title": "Order Change. Tax_ Exchange Rate. Exchange Rate",
          "description": "The exchange rate between the document currency and the tax currency.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/TaxExchangeRate"
          },
        "PricingExchangeRate": {
          "title": "Order Change. Pricing_ Exchange Rate. Exchange Rate",
          "description": "The exchange rate between the document currency and the pricing currency.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/PricingExchangeRate"
          },
        "PaymentExchangeRate": {
          "title": "Order Change. Payment_ Exchange Rate. Exchange Rate",
          "description": "The exchange rate between the document currency and the payment currency.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/PaymentExchangeRate"
          },
        "DestinationCountry": {
          "title": "Order Change. Destination_ Country. Country",
          "description": "The country of destination (for customs purposes).",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/DestinationCountry"
          },
        "TaxTotal": {
          "title": "Order Change. Tax Total",
          "description": "The total amount of a specific type of tax.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/TaxTotal"
            },
          "minItems": 1,
          "type": "array"
          },
        "AnticipatedMonetaryTotal": {
          "title": "Order Change. Anticipated_ Monetary Total. Monetary Total",
          "description": "The amount of change to the total cost of the order anticipated by the buyer.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/AnticipatedMonetaryTotal"
          },
        "OrderLine": {
          "title": "Order Change. Order Line",
          "description": "An association to one or more (changed) Order Lines.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/OrderLine"
            },
          "minItems": 1,
          "type": "array"
          }
        },
      "additionalProperties": false,
      "type": "object"
      }
    }
  }

=== metasfresh/metasfresh/misc/services/camel/de-metas-camel-externalsystems/com-adekia-exchange/com.adekia.exchange-model/model/UBL-2.3-JSON-v1.0-cn01/json-model/UBL-OrderChange-2.1-Example.json
{"_D":"urn:oasis:names:specification:ubl:schema:xsd:OrderChange-2",
 "_A":"urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2",
 "_B":"urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2",
 "OrderChange":{
 "UBLVersionID":{"_":"2.1"},
 "CustomizationID":{"_":"urn:www.cenbii.eu:transaction:biicoretrdmXYZ:ver1.0"},
 "ProfileID":{"_":"urn:www.cenbii.eu:profile:BIIXYZ:ver1.0",
  "schemeAgencyID":"BII",
  "schemeID":"Profile"},
 "ID":{"_":"7"},
 "IssueDate":{"_":"2010-01-21"},
 "IssueTime":{"_":"12:30:00Z"},
 "SequenceNumberID":{"_":"1"},
 "Note":[{"_":"Information text for the whole order change"}],
 "OrderReference":{
  "ID":{"_":"34"}
 },
 "BuyerCustomerParty":{
  "Party":{
   "EndpointID":{"_":"7300072311115",
    "schemeAgencyID":"9",
    "schemeID":"GLN"},
   "PartyIdentification":[{
    "ID":{"_":"7300070011115",
     "schemeAgencyID":"9",
     "schemeID":"GLN"}
   },{
    "ID":{"_":"PartyID123"}
   }],
   "PartyName":[{
    "Name":{"_":"Johnssons byggvaror"}
   }]
  }
 },
 "SellerSupplierParty":{
  "Party":{
   "EndpointID":{"_":"7302347231111",
    "schemeAgencyID":"9",
    "schemeID":"GLN"},
   "PartyIdentification":[{
    "ID":{"_":"SellerPartyID123"}
   }],
   "PartyName":[{
    "Name":{"_":"Moderna Produkter AB"}
   }]
  }
 },
 "OrderLine":[{
  "Note":[{"_":"Freetext note on line 1"}],
  "LineItem":{
   "ID":{"_":"1"},
   "LineStatusCode":{"_":"Revised",
    "listAgencyID":"UBL",
    "listName":"Line Status"},
   "Quantity":{"_":240,
    "unitCode":"LTR"},
   "LineExtensionAmount":{"_":12000,
    "currencyID":"SEK"},
   "TotalTaxAmount":{"_":20,
    "currencyID":"SEK"},
   "PartialDeliveryIndicator":{"_":false},
   "AccountingCostCode":{"_":"ProjectID123"},
   "Delivery":[{
    "RequestedDeliveryPeriod":{
     "StartDate":{"_":"2010-02-10"},
     "EndDate":{"_":"2010-02-25"}
    }
   }],
   "OriginatorParty":{
    "PartyIdentification":[{
     "ID":{"_":"EmployeeXXX",
      "schemeAgencyID":"ZZZ",
      "schemeID":"ZZZ"}
    }],
    "PartyName":[{
     "Name":{"_":"Josef K."}
    }]
   },
   "Price":{
    "PriceAmount":{"_":50,
     "currencyID":"SEK"},
    "BaseQuantity":{"_":1,
     "unitCode":"LTR"}
   },
   "Item":{
    "Description":[{"_":"Red paint"}],
    "Name":{"_":"Falu Rödfärg"},
    "SellersItemIdentification":{
     "ID":{"_":"SItemNo001"}
    },
    "StandardItemIdentification":{
     "ID":{"_":"1234567890123",
      "schemeAgencyID":"6",
      "schemeID":"GTIN"}
    },
    "AdditionalItemProperty":[{
     "Name":{"_":"Paint type"},
     "Value":{"_":"Acrylic"}
    },{
     "Name":{"_":"Solvant"},
     "Value":{"_":"Water"}
    }]
   }
  }
 }]
}}
