=== metasfresh/metasfresh/misc/services/camel/de-metas-camel-externalsystems/com-adekia-exchange/com.adekia.exchange-model/model/UBL-2.3-JSON-v1.0-cn01/json-schema-model/maindoc/UBL-ReceiptAdvice-2.3.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "json-schema-model/maindoc/UBL-ReceiptAdvice-2.3.json",
  "description": "\n  Library:           OASIS Universal Business Language (UBL) 2.3 OS\n                     http://docs.oasis-open.org/ubl/os-UBL-2.3/\n  Release Date:      15 June 2021\n  Module:            json-schema-model/maindoc/UBL-ReceiptAdvice-2.3.json\n  Generated on:      2021-12-15 21:56z\n  Copyright (c) OASIS Open 2021. All Rights Reserved.\n\n\n  OASIS takes no position regarding the validity or scope of any \n  intellectual property or other rights that might be claimed to pertain \n  to the implementation or use of the technology described in this \n  document or the extent to which any license under such rights \n  might or might not be available; neither does it represent that it has \n  made any effort to identify any such rights. Information on OASIS's \n  procedures with respect to rights in OASIS specifications can be \n  found at the OASIS website. Copies of claims of rights made \n  available for publication and any assurances of licenses to be made \n  available, or the result of an attempt made to obtain a general \n  license or permission for the use of such proprietary rights by \n  implementors or users of this specification, can be obtained from \n  the OASIS Executive Director.\n\n  OASIS invites any interested party to bring to its attention any \n  copyrights, patents or patent applications, or other proprietary \n  rights which may cover technology that may be required to \n  implement this specification. Please address the information to the \n  OASIS Executive Director.\n  \n  This document and translations of it may be copied and furnished to \n  others, and derivative works that comment on or otherwise explain \n  it or assist in its implementation may be prepared, copied, \n  published and distributed, in whole or in part, without restriction of \n  any kind, provided that the above copyright notice and this \n  paragraph are included on all such copies and derivative works. \n  However, this document itself may not be modified in any way, \n  such as by removing the copyright notice or references to OASIS, \n  except as needed for the purpose of developing OASIS \n  specifications, in which case the procedures for copyrights defined \n  in the OASIS Intellectual Property Rights document must be \n  followed, or as required to translate it into languages other than \n  English. \n\n  The limited permissions granted above are perpetual and will not be \n  revoked by OASIS or its successors or assigns. \n\n  This document and the information contained herein is provided on \n  an \"AS IS\" basis and OASIS DISCLAIMS ALL WARRANTIES, \n  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO ANY \n  WARRANTY THAT THE USE OF THE INFORMATION HEREIN \n  WILL NOT INFRINGE ANY RIGHTS OR ANY IMPLIED \n  WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A \n  PARTICULAR PURPOSE.    \n",
  "required": [
    "ReceiptAdvice"
    ],
  "properties": {
    "_D": {
      "description": "Document ABIE XML namespace string",
      "type": "string"
      },
    "_A": {
      "description": "Library ABIE XML namespace string (for ASBIEs)",
      "type": "string"
      },
    "_B": {
      "description": "BBIE XML namespace string",
      "type": "string"
      },
    "_E": {
      "description": "Extension scaffolding XML namespace string",
      "type": "string"
      },
    "ReceiptAdvice": {
      "description": "A document used to describe the receipt of goods and services.",
      "$ref": "#/definitions/ReceiptAdvice"
      }
    },
  "additionalProperties": false,
  "type": "object",
  "definitions": {
    "ReceiptAdvice": {
      "title": "Receipt Advice. Details",
      "description": "A document used to describe the receipt of goods and services.",
      "required": [
        "ID",
        "IssueDate",
        "DeliveryCustomerParty",
        "DespatchSupplierParty",
        "ReceiptLine"
        ],
      "properties": {

        "UBLExtensions": {
          "title": "UBLExtensions",
          "description": "An optional set of extensions to the committee model",
          "items": { 
            "$ref": "../common/UBL-CommonExtensionComponents-2.3.json#/definitions/UBLExtensions" },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },

        "UBLVersionID": {
          "title": "Receipt Advice. UBL Version Identifier. Identifier",
          "description": "Identifies the earliest version of the UBL 2 schema for this document type that defines all of the elements that might be encountered in the current instance.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/UBLVersionID"
          },
        "CustomizationID": {
          "title": "Receipt Advice. Customization Identifier. Identifier",
          "description": "Identifies a user-defined customization of UBL for a specific use.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/CustomizationID"
          },
        "ProfileID": {
          "title": "Receipt Advice. Profile Identifier. Identifier",
          "description": "Identifies a user-defined profile of the subset of UBL being used.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ProfileID"
          },
        "ProfileExecutionID": {
          "title": "Receipt Advice. Profile Execution Identifier. Identifier",
          "description": "Identifies an instance of executing a profile, to associate all transactions in a collaboration.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ProfileExecutionID"
          },
        "ID": {
          "title": "Receipt Advice. Identifier",
          "description": "An identifier for this document, assigned by the sender.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ID"
          },
        "CopyIndicator": {
          "title": "Receipt Advice. Copy_ Indicator. Indicator",
          "description": "Indicates whether this document is a copy (true) or not (false).",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/CopyIndicator"
          },
        "UUID": {
          "title": "Receipt Advice. UUID. Identifier",
          "description": "A universally unique identifier for an instance of this document.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/UUID"
          },
        "IssueDate": {
          "title": "Receipt Advice. Issue Date. Date",
          "description": "The date, assigned by the sender, on which this document was issued.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/IssueDate"
          },
        "IssueTime": {
          "title": "Receipt Advice. Issue Time. Time",
          "description": "The time, assigned by the sender, at which this document was issued.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/IssueTime"
          },
        "DocumentStatusCode": {
          "title": "Receipt Advice. Document Status Code. Code",
          "description": "A code signifying the status of the Receipt Advice with respect to its original state. This code may be used if the document precedes the event and is subsequently found to be incorrect and in need of cancellation or revision.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/DocumentStatusCode"
          },
        "ReceiptAdviceTypeCode": {
          "title": "Receipt Advice. Receipt Advice Type Code. Code",
          "description": "A code signifying the type of the Receipt Advice.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ReceiptAdviceTypeCode"
          },
        "Note": {
          "title": "Receipt Advice. Note. Text",
          "description": "Free-form text pertinent to this document, conveying information that is not contained explicitly in other structures.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/Note"
            },
          "minItems": 1,
          "type": "array"
          },
        "LineCountNumeric": {
          "title": "Receipt Advice. Line Count. Numeric",
          "description": "The number of Receipt Lines in this document.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/LineCountNumeric"
          },
        "OrderReference": {
          "title": "Receipt Advice. Order Reference",
          "description": "A reference to an Order associated with this Receipt Advice.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/OrderReference"
            },
          "minItems": 1,
          "type": "array"
          },
        "DespatchDocumentReference": {
          "title": "Receipt Advice. Despatch_ Document Reference. Document Reference",
          "description": "A reference to a Despatch Advice associated with this document.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/DespatchDocumentReference"
            },
          "minItems": 1,
          "type": "array"
          },
        "AdditionalDocumentReference": {
          "title": "Receipt Advice. Additional_ Document Reference. Document Reference",
          "description": "A reference to an additional document associated with this document.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/AdditionalDocumentReference"
            },
          "minItems": 1,
          "type": "array"
          },
        "Signature": {
          "title": "Receipt Advice. Signature",
          "description": "A signature applied to this document.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/Signature"
            },
          "minItems": 1,
          "type": "array"
          },
        "DeliveryCustomerParty": {
          "title": "Receipt Advice. Delivery_ Customer Party. Customer Party",
          "description": "The customer party.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/DeliveryCustomerParty"
          },
        "DespatchSupplierParty": {
          "title": "Receipt Advice. Despatch_ Supplier Party. Supplier Party",
          "description": "The supplier party.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/DespatchSupplierParty"
          },
        "BuyerCustomerParty": {
          "title": "Receipt Advice. Buyer_ Customer Party. Customer Party",
          "description": "The buyer.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/BuyerCustomerParty"
          },
        "SellerSupplierParty": {
          "title": "Receipt Advice. Seller_ Supplier Party. Supplier Party",
          "description": "The seller.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/SellerSupplierParty"
          },
        "Shipment": {
          "title": "Receipt Advice. Shipment",
          "description": "Details about the Shipment.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/Shipment"
          },
        "ReceiptLine": {
          "title": "Receipt Advice. Receipt Line",
          "description": "A line detailing a kind of item received.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/ReceiptLine"
            },
          "minItems": 1,
          "type": "array"
          }
        },
      "additionalProperties": false,
      "type": "object"
      }
    }
  }

=== metasfresh/metasfresh/misc/services/camel/de-metas-camel-externalsystems/com-adekia-exchange/com.adekia.exchange-model/model/UBL-2.3-JSON-v1.0-cn01/json-model/UBL-ReceiptAdvice-2.0-Example.json
{"_D":"urn:oasis:names:specification:ubl:schema:xsd:ReceiptAdvice-2",
 "_A":"urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2",
 "_B":"urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2",
 "ReceiptAdvice":{
 "UBLVersionID":{"_":"2.0"},
 "CustomizationID":{"_":"urn:oasis:names:specification:ubl:xpath:ReceiptAdvice-2.0:sbs-1.0-draft"},
 "ProfileID":{"_":"bpid:urn:oasis:names:draft:bpss:ubl-2-sbs-receipt-advice-notification-draft"},
 "ID":{"_":"658398"},
 "CopyIndicator":{"_":false},
 "UUID":{"_":"89F82FA6-5331-491D-83BC-7B6CA7FD047C"},
 "IssueDate":{"_":"2005-06-21"},
 "Note":[{"_":"sample"}],
 "OrderReference":[{
  "ID":{"_":"AEG012345"},
  "SalesOrderID":{"_":"CON0095678"},
  "UUID":{"_":"6E09886B-DC6E-439F-82D1-7CCAC7F4E3B1"},
  "IssueDate":{"_":"2005-06-20"}
 }],
 "DespatchDocumentReference":[{
  "ID":{"_":"565899"},
  "UUID":{"_":"88C7280E-8F10-419F-9949-8EFFFA2842B8"},
  "IssueDate":{"_":"2005-06-20"}
 }],
 "DeliveryCustomerParty":{
  "CustomerAssignedAccountID":{"_":"XFB01"},
  "SupplierAssignedAccountID":{"_":"GT00978567"},
  "Party":{
   "PartyName":[{
    "Name":{"_":"IYT Corporation"}
   }],
   "PostalAddress":{
    "StreetName":{"_":"Avon Way"},
    "BuildingName":{"_":"Thereabouts"},
    "BuildingNumber":{"_":"56A"},
    "CityName":{"_":"Bridgtow"},
    "PostalZone":{"_":"ZZ99 1ZZ"},
    "CountrySubentity":{"_":"Avon"},
    "AddressLine":[{
     "Line":{"_":"3rd Floor, Room 5"}
    }],
    "Country":{
     "IdentificationCode":{"_":"GB"}
    }
   },
   "PartyTaxScheme":[{
    "RegistrationName":{"_":"Bridgtow District Council"},
    "CompanyID":{"_":"12356478"},
    "ExemptionReason":[{"_":"Local Authority"}],
    "TaxScheme":{
     "ID":{"_":"UK VAT"},
     "TaxTypeCode":{"_":"VAT"}
    }
   }],
   "Contact":{
    "Name":{"_":"Mr Fred Churchill"},
    "Telephone":{"_":"0127 2653214"},
    "Telefax":{"_":"0127 2653215"},
    "ElectronicMail":{"_":"fred@iytcorporation.gov.uk"}
   }
  }
 },
 "DespatchSupplierParty":{
  "CustomerAssignedAccountID":{"_":"CO001"},
  "Party":{
   "PartyName":[{
    "Name":{"_":"Consortial"}
   }],
   "PostalAddress":{
    "StreetName":{"_":"Busy Street"},
    "BuildingName":{"_":"Thereabouts"},
    "BuildingNumber":{"_":"56A"},
    "CityName":{"_":"Farthing"},
    "PostalZone":{"_":"AA99 1BB"},
    "CountrySubentity":{"_":"Heremouthshire"},
    "AddressLine":[{
     "Line":{"_":"The Roundabout"}
    }],
    "Country":{
     "IdentificationCode":{"_":"GB"}
    }
   },
   "PartyTaxScheme":[{
    "RegistrationName":{"_":"Farthing Purchasing Consortium"},
    "CompanyID":{"_":"175 269 2355"},
    "ExemptionReason":[{"_":"N/A"}],
    "TaxScheme":{
     "ID":{"_":"VAT"},
     "TaxTypeCode":{"_":"VAT"}
    }
   }],
   "Contact":{
    "Name":{"_":"Mrs Bouquet"},
    "Telephone":{"_":"0158 1233714"},
    "Telefax":{"_":"0158 1233856"},
    "ElectronicMail":{"_":"bouquet@fpconsortial.co.uk"}
   }
  }
 },
 "Shipment":{
  "ID":{"_":"1"},
  "Consignment":[{
   "ID":{"_":"1"}
  }],
  "Delivery":{
   "ID":{"_":"1"},
   "Quantity":{"_":90,
    "unitCode":"KGM"},
   "ActualDeliveryDate":{"_":"2005-06-20"},
   "ActualDeliveryTime":{"_":"11:30:00.0Z"},
   "RequestedDeliveryPeriod":{
    "StartDate":{"_":"2005-06-20"},
    "StartTime":{"_":"10:30:47.0Z"},
    "EndDate":{"_":"2005-06-21"},
    "EndTime":{"_":"10:30:47.0Z"}
   }
  }
 },
 "ReceiptLine":[{
  "ID":{"_":"1"},
  "Note":[{"_":"SAMPLE"}],
  "ReceivedQuantity":{"_":90,
   "unitCode":"KGM"},
  "ShortQuantity":{"_":10,
   "unitCode":"KGM"},
  "Item":[{
   "Description":[{"_":"Acme beeswax"}],
   "Name":{"_":"beeswax"},
   "BuyersItemIdentification":{
    "ID":{"_":"6578489"}
   },
   "SellersItemIdentification":{
    "ID":{"_":"17589683"}
   },
   "ItemInstance":[{
    "LotIdentification":{
     "LotNumberID":{"_":"546378239"},
     "ExpiryDate":{"_":"2010-01-01"}
    }
   }]
  }]
 }]
}}
