=== metasfresh/metasfresh/misc/services/camel/de-metas-camel-externalsystems/com-adekia-exchange/com.adekia.exchange-model/model/UBL-2.3-JSON-v1.0-cn01/json-schema-model/maindoc/UBL-Order-2.3.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "json-schema-model/maindoc/UBL-Order-2.3.json",
  "description": "\n  Library:           OASIS Universal Business Language (UBL) 2.3 OS\n                     http://docs.oasis-open.org/ubl/os-UBL-2.3/\n  Release Date:      15 June 2021\n  Module:            json-schema-model/maindoc/UBL-Order-2.3.json\n  Generated on:      2021-12-15 21:56z\n  Copyright (c) OASIS Open 2021. All Rights Reserved.\n\n\n  OASIS takes no position regarding the validity or scope of any \n  intellectual property or other rights that might be claimed to pertain \n  to the implementation or use of the technology described in this \n  document or the extent to which any license under such rights \n  might or might not be available; neither does it represent that it has \n  made any effort to identify any such rights. Information on OASIS's \n  procedures with respect to rights in OASIS specifications can be \n  found at the OASIS website. Copies of claims of rights made \n  available for publication and any assurances of licenses to be made \n  available, or the result of an attempt made to obtain a general \n  license or permission for the use of such proprietary rights by \n  implementors or users of this specification, can be obtained from \n  the OASIS Executive Director.\n\n  OASIS invites any interested party to bring to its attention any \n  copyrights, patents or patent applications, or other proprietary \n  rights which may cover technology that may be required to \n  implement this specification. Please address the information to the \n  OASIS Executive Director.\n  \n  This document and translations of it may be copied and furnished to \n  others, and derivative works that comment on or otherwise explain \n  it or assist in its implementation may be prepared, copied, \n  published and distributed, in whole or in part, without restriction of \n  any kind, provided that the above copyright notice and this \n  paragraph are included on all such copies and derivative works. \n  However, this document itself may not be modified in any way, \n  such as by removing the copyright notice or references to OASIS, \n  except as needed for the purpose of developing OASIS \n  specifications, in which case the procedures for copyrights defined \n  in the OASIS Intellectual Property Rights document must be \n  followed, or as required to translate it into languages other than \n  English. \n\n  The limited permissions granted above are perpetual and will not be \n  revoked by OASIS or its successors or assigns. \n\n  This document and the information contained herein is provided on \n  an \"AS IS\" basis and OASIS DISCLAIMS ALL WARRANTIES, \n  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO ANY \n  WARRANTY THAT THE USE OF THE INFORMATION HEREIN \n  WILL NOT INFRINGE ANY RIGHTS OR ANY IMPLIED \n  WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A \n  PARTICULAR PURPOSE.    \n",
  "required": [
    "Order"
    ],
  "properties": {
    "_D": {
      "description": "Document ABIE XML namespace string",
      "type": "string"
      },
    "_A": {
      "description": "Library ABIE XML namespace string (for ASBIEs)",
      "type": "string"
      },
    "_B": {
      "description": "BBIE XML namespace string",
      "type": "string"
      },
    "_E": {
      "description": "Extension scaffolding XML namespace string",
      "type": "string"
      },
    "Order": {
      "description": "A document used to order goods and services.",
      "$ref": "#/definitions/Order"
      }
    },
  "additionalProperties": false,
  "type": "object",
  "definitions": {
    "Order": {
      "title": "Order. Details",
      "description": "A document used to order goods and services.",
      "required": [
        "ID",
        "IssueDate",
        "BuyerCustomerParty",
        "SellerSupplierParty",
        "OrderLine"
        ],
      "properties": {

        "UBLExtensions": {
          "title": "UBLExtensions",
          "description": "An optional set of extensions to the committee model",
          "items": { 
            "$ref": "../common/UBL-CommonExtensionComponents-2.3.json#/definitions/UBLExtensions" },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },

        "UBLVersionID": {
          "title": "Order. UBL Version Identifier. Identifier",
          "description": "Identifies the earliest version of the UBL 2 schema for this document type that defines all of the elements that might be encountered in the current instance.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/UBLVersionID"
          },
        "CustomizationID": {
          "title": "Order. Customization Identifier. Identifier",
          "description": "Identifies a user-defined customization of UBL for a specific use.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/CustomizationID"
          },
        "ProfileID": {
          "title": "Order. Profile Identifier. Identifier",
          "description": "Identifies a user-defined profile of the customization of UBL being used.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ProfileID"
          },
        "ProfileExecutionID": {
          "title": "Order. Profile Execution Identifier. Identifier",
          "description": "Identifies an instance of executing a profile, to associate all transactions in a collaboration.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ProfileExecutionID"
          },
        "ID": {
          "title": "Order. Identifier",
          "description": "An identifier for this document, assigned by the sender.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ID"
          },
        "SalesOrderID": {
          "title": "Order. Sales_ Order Identifier. Identifier",
          "description": "An identifier for the Order, assigned by the seller.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/SalesOrderID"
          },
        "CopyIndicator": {
          "title": "Order. Copy_ Indicator. Indicator",
          "description": "Indicates whether this document is a copy (true) or not (false).",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/CopyIndicator"
          },
        "UUID": {
          "title": "Order. UUID. Identifier",
          "description": "A universally unique identifier for an instance of this document.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/UUID"
          },
        "IssueDate": {
          "title": "Order. Issue Date. Date",
          "description": "The date, assigned by the sender, on which this document was issued.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/IssueDate"
          },
        "IssueTime": {
          "title": "Order. Issue Time. Time",
          "description": "The time, assigned by the sender, at which this document was issued.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/IssueTime"
          },
        "OrderTypeCode": {
          "title": "Order. Order Type Code. Code",
          "description": "A code signifying the type of Order.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/OrderTypeCode"
          },
        "Note": {
          "title": "Order. Note. Text",
          "description": "Free-form text pertinent to this document, conveying information that is not contained explicitly in other structures.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/Note"
            },
          "minItems": 1,
          "type": "array"
          },
        "RequestedInvoiceCurrencyCode": {
          "title": "Order. Requested Invoice_ Currency Code. Code",
          "description": "A code signifying the currency requested for amount totals in Invoices related to this Order.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/RequestedInvoiceCurrencyCode"
          },
        "DocumentCurrencyCode": {
          "title": "Order. Document_ Currency Code. Code",
          "description": "A code signifying the default currency for this document.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/DocumentCurrencyCode"
          },
        "PricingCurrencyCode": {
          "title": "Order. Pricing_ Currency Code. Code",
          "description": "A code signifying the currency used for all prices in the Order.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/PricingCurrencyCode"
          },
        "TaxCurrencyCode": {
          "title": "Order. Tax_ Currency Code. Code",
          "description": "A code signifying the currency requested for tax amounts in Invoices related to this Order.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/TaxCurrencyCode"
          },
        "CustomerReference": {
          "title": "Order. Customer_ Reference. Text",
          "description": "A supplementary reference for the Order.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/CustomerReference"
          },
        "AccountingCostCode": {
          "title": "Order. Accounting Cost Code. Code",
          "description": "The buyer's accounting code, applied to the Order as a whole.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/AccountingCostCode"
          },
        "AccountingCost": {
          "title": "Order. Accounting Cost. Text",
          "description": "The buyer's accounting cost centre, applied to the Order as a whole, expressed as text.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/AccountingCost"
          },
        "LineCountNumeric": {
          "title": "Order. Line Count. Numeric",
          "description": "The number of Order Lines in the document.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/LineCountNumeric"
          },
        "ValidityPeriod": {
          "title": "Order. Validity_ Period. Period",
          "description": "The period for which the Order is valid.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/ValidityPeriod"
            },
          "minItems": 1,
          "type": "array"
          },
        "QuotationDocumentReference": {
          "title": "Order. Quotation_ Document Reference. Document Reference",
          "description": "A reference to a Quotation.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/QuotationDocumentReference"
          },
        "OrderDocumentReference": {
          "title": "Order. Order_ Document Reference. Document Reference",
          "description": "A reference to another Order.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/OrderDocumentReference"
            },
          "minItems": 1,
          "type": "array"
          },
        "OriginatorDocumentReference": {
          "title": "Order. Originator_ Document Reference. Document Reference",
          "description": "A reference to an originator document associated with this document.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/OriginatorDocumentReference"
          },
        "CatalogueReference": {
          "title": "Order. Catalogue Reference",
          "description": "A reference to the Catalogue on which this Order is based.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/CatalogueReference"
          },
        "AdditionalDocumentReference": {
          "title": "Order. Additional_ Document Reference. Document Reference",
          "description": "A reference to an additional document associated with this document.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/AdditionalDocumentReference"
            },
          "minItems": 1,
          "type": "array"
          },
        "Contract": {
          "title": "Order. Contract",
          "description": "A contracts associated with this Order.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/Contract"
            },
          "minItems": 1,
          "type": "array"
          },
        "ProjectReference": {
          "title": "Order. Project Reference",
          "description": "A project with which this Order is associated.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/ProjectReference"
            },
          "minItems": 1,
          "type": "array"
          },
        "Signature": {
          "title": "Order. Signature",
          "description": "A signature applied to this document.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/Signature"
            },
          "minItems": 1,
          "type": "array"
          },
        "BuyerCustomerParty": {
          "title": "Order. Buyer_ Customer Party. Customer Party",
          "description": "The buyer.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/BuyerCustomerParty"
          },
        "SellerSupplierParty": {
          "title": "Order. Seller_ Supplier Party. Supplier Party",
          "description": "The seller.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/SellerSupplierParty"
          },
        "OriginatorCustomerParty": {
          "title": "Order. Originator_ Customer Party. Customer Party",
          "description": "The originator.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/OriginatorCustomerParty"
          },
        "FreightForwarderParty": {
          "title": "Order. Freight Forwarder_ Party. Party",
          "description": "A freight forwarder or carrier.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/FreightForwarderParty"
          },
        "AccountingCustomerParty": {
          "title": "Order. Accounting_ Customer Party. Customer Party",
          "description": "The accounting customer party.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/AccountingCustomerParty"
          },
        "Delivery": {
          "title": "Order. Delivery",
          "description": "A delivery associated with this document.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/Delivery"
            },
          "minItems": 1,
          "type": "array"
          },
        "DeliveryTerms": {
          "title": "Order. Delivery Terms",
          "description": "A set of delivery terms associated with this document.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/DeliveryTerms"
            },
          "minItems": 1,
          "type": "array"
          },
        "PaymentMeans": {
          "title": "Order. Payment Means",
          "description": "Expected means of payment.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/PaymentMeans"
            },
          "minItems": 1,
          "type": "array"
          },
        "PaymentTerms": {
          "title": "Order. Payment Terms",
          "description": "A set of payment terms associated with this document.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/PaymentTerms"
            },
          "minItems": 1,
          "type": "array"
          },
        "TransactionConditions": {
          "title": "Order. Transaction Conditions",
          "description": "A specification of purchasing or sales conditions applying to the whole Order.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/TransactionConditions"
          },
        "AllowanceCharge": {
          "title": "Order. Allowance Charge",
          "description": "A discount or charge that applies to a price component.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/AllowanceCharge"
            },
          "minItems": 1,
          "type": "array"
          },
        "TaxExchangeRate": {
          "title": "Order. Tax_ Exchange Rate. Exchange Rate",
          "description": "The exchange rate between the document currency and the tax currency.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/TaxExchangeRate"
          },
        "PricingExchangeRate": {
          "title": "Order. Pricing_ Exchange Rate. Exchange Rate",
          "description": "The exchange rate between the document currency and the pricing currency.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/PricingExchangeRate"
          },
        "PaymentExchangeRate": {
          "title": "Order. Payment_ Exchange Rate. Exchange Rate",
          "description": "The exchange rate between the document currency and the payment currency.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/PaymentExchangeRate"
          },
        "DestinationCountry": {
          "title": "Order. Destination_ Country. Country",
          "description": "The country of destination (for customs purposes).",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/DestinationCountry"
          },
        "TaxTotal": {
          "title": "Order. Tax Total",
          "description": "The total amount of a specific type of tax.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/TaxTotal"
            },
          "minItems": 1,
          "type": "array"
          },
        "AnticipatedMonetaryTotal": {
          "title": "Order. Anticipated_ Monetary Total. Monetary Total",
          "description": "The total amount for the Order anticipated by the buyer.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/AnticipatedMonetaryTotal"
          },
        "OrderLine": {
          "title": "Order. Order Line",
          "description": "A line associated with a line in the Catalogue and specifying a kind of item being ordered.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/OrderLine"
            },
          "minItems": 1,
          "type": "array"
          }
        },
      "additionalProperties": false,
      "type": "object"
      }
    }
  }

=== metasfresh/metasfresh/misc/services/camel/de-metas-camel-externalsystems/com-adekia-exchange/com.adekia.exchange-model/model/UBL-2.3-JSON-v1.0-cn01/json-model/UBL-Order-2.0-Example.json
{"_D":"urn:oasis:names:specification:ubl:schema:xsd:Order-2",
 "_A":"urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2",
 "_B":"urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2",
 "Order":{
 "UBLVersionID":{"_":"2.0"},
 "CustomizationID":{"_":"urn:oasis:names:specification:ubl:xpath:Order-2.0:sbs-1.0-draft"},
 "ProfileID":{"_":"bpid:urn:oasis:names:draft:bpss:ubl-2-sbs-order-with-simple-response-draft"},
 "ID":{"_":"AEG012345"},
 "SalesOrderID":{"_":"CON0095678"},
 "CopyIndicator":{"_":false},
 "UUID":{"_":"6E09886B-DC6E-439F-82D1-7CCAC7F4E3B1"},
 "IssueDate":{"_":"2005-06-20"},
 "Note":[{"_":"sample"}],
 "BuyerCustomerParty":{
  "CustomerAssignedAccountID":{"_":"XFB01"},
  "SupplierAssignedAccountID":{"_":"GT00978567"},
  "Party":{
   "PartyName":[{
    "Name":{"_":"IYT Corporation"}
   }],
   "PostalAddress":{
    "StreetName":{"_":"Avon Way"},
    "BuildingName":{"_":"Thereabouts"},
    "BuildingNumber":{"_":"56A"},
    "CityName":{"_":"Bridgtow"},
    "PostalZone":{"_":"ZZ99 1ZZ"},
    "CountrySubentity":{"_":"Avon"},
    "AddressLine":[{
     "Line":{"_":"3rd Floor, Room 5"}
    }],
    "Country":{
     "IdentificationCode":{"_":"GB"}
    }
   },
   "PartyTaxScheme":[{
    "RegistrationName":{"_":"Bridgtow District Council"},
    "CompanyID":{"_":"12356478"},
    "ExemptionReason":[{"_":"Local Authority"}],
    "TaxScheme":{
     "ID":{"_":"UK VAT"},
     "TaxTypeCode":{"_":"VAT"}
    }
   }],
   "Contact":{
    "Name":{"_":"Mr Fred Churchill"},
    "Telephone":{"_":"0127 2653214"},
    "Telefax":{"_":"0127 2653215"},
    "ElectronicMail":{"_":"fred@iytcorporation.gov.uk"}
   }
  }
 },
 "SellerSupplierParty":{
  "CustomerAssignedAccountID":{"_":"CO001"},
  "Party":{
   "PartyName":[{
    "Name":{"_":"Consortial"}
   }],
   "PostalAddress":{
    "StreetName":{"_":"Busy Street"},
    "BuildingName":{"_":"Thereabouts"},
    "BuildingNumber":{"_":"56A"},
    "CityName":{"_":"Farthing"},
    "PostalZone":{"_":"AA99 1BB"},
    "CountrySubentity":{"_":"Heremouthshire"},
    "AddressLine":[{
     "Line":{"_":"The Roundabout"}
    }],
    "Country":{
     "IdentificationCode":{"_":"GB"}
    }
   },
   "PartyTaxScheme":[{
    "RegistrationName":{"_":"Farthing Purchasing Consortium"},
    "CompanyID":{"_":"175 269 2355"},
    "ExemptionReason":[{"_":"N/A"}],
    "TaxScheme":{
     "ID":{"_":"VAT"},
     "TaxTypeCode":{"_":"VAT"}
    }
   }],
   "Contact":{
    "Name":{"_":"Mrs Bouquet"},
    "Telephone":{"_":"0158 1233714"},
    "Telefax":{"_":"0158 1233856"},
    "ElectronicMail":{"_":"bouquet@fpconsortial.co.uk"}
   }
  }
 },
 "OriginatorCustomerParty":{
  "Party":{
   "PartyName":[{
    "Name":{"_":"The Terminus"}
   }],
   "PostalAddress":{
    "StreetName":{"_":"Avon Way"},
    "BuildingName":{"_":"Thereabouts"},
    "BuildingNumber":{"_":"56A"},
    "CityName":{"_":"Bridgtow"},
    "PostalZone":{"_":"ZZ99 1ZZ"},
    "CountrySubentity":{"_":"Avon"},
    "AddressLine":[{
     "Line":{"_":"3rd Floor, Room 5"}
    }],
    "Country":{
     "IdentificationCode":{"_":"GB"}
    }
   },
   "PartyTaxScheme":[{
    "RegistrationName":{"_":"Bridgtow District Council"},
    "CompanyID":{"_":"12356478"},
    "ExemptionReason":[{"_":"Local Authority"}],
    "TaxScheme":{
     "ID":{"_":"UK VAT"},
     "TaxTypeCode":{"_":"VAT"}
    }
   }],
   "Contact":{
    "Name":{"_":"S Massiah"},
    "Telephone":{"_":"0127 98876545"},
    "Telefax":{"_":"0127 98876546"},
    "ElectronicMail":{"_":"smassiah@the-email.co.uk"}
   }
  }
 },
 "Delivery":[{
  "DeliveryAddress":{
   "StreetName":{"_":"Avon Way"},
   "BuildingName":{"_":"Thereabouts"},
   "BuildingNumber":{"_":"56A"},
   "CityName":{"_":"Bridgtow"},
   "PostalZone":{"_":"ZZ99 1ZZ"},
   "CountrySubentity":{"_":"Avon"},
   "AddressLine":[{
    "Line":{"_":"3rd Floor, Room 5"}
   }],
   "Country":{
    "IdentificationCode":{"_":"GB"}
   }
  },
  "RequestedDeliveryPeriod":{
   "StartDate":{"_":"2005-06-29"},
   "StartTime":{"_":"09:30:47.0Z"},
   "EndDate":{"_":"2005-06-29"},
   "EndTime":{"_":"09:30:47.0Z"}
  }
 }],
 "DeliveryTerms":[{
  "SpecialTerms":[{"_":"1% deduction for late delivery as per contract"}]
 }],
 "TransactionConditions":{
  "Description":[{"_":"order response required; payment is by BACS or by cheque"}]
 },
 "AnticipatedMonetaryTotal":{
  "LineExtensionAmount":{"_":100.00,
   "currencyID":"GBP"},
  "PayableAmount":{"_":100.00,
   "currencyID":"GBP"}
 },
 "OrderLine":[{
  "Note":[{"_":"this is an illustrative order line"}],
  "LineItem":{
   "ID":{"_":"1"},
   "SalesOrderID":{"_":"A"},
   "LineStatusCode":{"_":"NoStatus"},
   "Quantity":{"_":100,
    "unitCode":"KGM"},
   "LineExtensionAmount":{"_":100.00,
    "currencyID":"GBP"},
   "TotalTaxAmount":{"_":17.50,
    "currencyID":"GBP"},
   "Price":{
    "PriceAmount":{"_":100.00,
     "currencyID":"GBP"},
    "BaseQuantity":{"_":1,
     "unitCode":"KGM"}
   },
   "Item":{
    "Description":[{"_":"Acme beeswax"}],
    "Name":{"_":"beeswax"},
    "BuyersItemIdentification":{
     "ID":{"_":"6578489"}
    },
    "SellersItemIdentification":{
     "ID":{"_":"17589683"}
    }
   }
  }
 }]
}}
