=== metasfresh/metasfresh/misc/services/camel/de-metas-camel-externalsystems/com-adekia-exchange/com.adekia.exchange-model/model/UBL-2.3-JSON-v1.0-cn01/json-schema-model/maindoc/UBL-PriorInformationNotice-2.3.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "json-schema-model/maindoc/UBL-PriorInformationNotice-2.3.json",
  "description": "\n  Library:           OASIS Universal Business Language (UBL) 2.3 OS\n                     http://docs.oasis-open.org/ubl/os-UBL-2.3/\n  Release Date:      15 June 2021\n  Module:            json-schema-model/maindoc/UBL-PriorInformationNotice-2.3.json\n  Generated on:      2021-12-15 21:56z\n  Copyright (c) OASIS Open 2021. All Rights Reserved.\n\n\n  OASIS takes no position regarding the validity or scope of any \n  intellectual property or other rights that might be claimed to pertain \n  to the implementation or use of the technology described in this \n  document or the extent to which any license under such rights \n  might or might not be available; neither does it represent that it has \n  made any effort to identify any such rights. Information on OASIS's \n  procedures with respect to rights in OASIS specifications can be \n  found at the OASIS website. Copies of claims of rights made \n  available for publication and any assurances of licenses to be made \n  available, or the result of an attempt made to obtain a general \n  license or permission for the use of such proprietary rights by \n  implementors or users of this specification, can be obtained from \n  the OASIS Executive Director.\n\n  OASIS invites any interested party to bring to its attention any \n  copyrights, patents or patent applications, or other proprietary \n  rights which may cover technology that may be required to \n  implement this specification. Please address the information to the \n  OASIS Executive Director.\n  \n  This document and translations of it may be copied and furnished to \n  others, and derivative works that comment on or otherwise explain \n  it or assist in its implementation may be prepared, copied, \n  published and distributed, in whole or in part, without restriction of \n  any kind, provided that the above copyright notice and this \n  paragraph are included on all such copies and derivative works. \n  However, this document itself may not be modified in any way, \n  such as by removing the copyright notice or references to OASIS, \n  except as needed for the purpose of developing OASIS \n  specifications, in which case the procedures for copyrights defined \n  in the OASIS Intellectual Property Rights document must be \n  followed, or as required to translate it into languages other than \n  English. \n\n  The limited permissions granted above are perpetual and will not be \n  revoked by OASIS or its successors or assigns. \n\n  This document and the information contained herein is provided on \n  an \"AS IS\" basis and OASIS DISCLAIMS ALL WARRANTIES, \n  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO ANY \n  WARRANTY THAT THE USE OF THE INFORMATION HEREIN \n  WILL NOT INFRINGE ANY RIGHTS OR ANY IMPLIED \n  WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A \n  PARTICULAR PURPOSE.    \n",
  "required": [
    "PriorInformationNotice"
    ],
  "properties": {
    "_D": {
      "description": "Document ABIE XML namespace string",
      "type": "string"
      },
    "_A": {
      "description": "Library ABIE XML namespace string (for ASBIEs)",
      "type": "string"
      },
    "_B": {
      "description": "BBIE XML namespace string",
      "type": "string"
      },
    "_E": {
      "description": "Extension scaffolding XML namespace string",
      "type": "string"
      },
    "PriorInformationNotice": {
      "description": "A document used by a contracting party to declare the intention to buy goods, services, or works during a specified period.",
      "$ref": "#/definitions/PriorInformationNotice"
      }
    },
  "additionalProperties": false,
  "type": "object",
  "definitions": {
    "PriorInformationNotice": {
      "title": "Prior Information Notice. Details",
      "description": "A document used by a contracting party to declare the intention to buy goods, services, or works during a specified period.",
      "required": [
        "IssueDate",
        "ContractingParty"
        ],
      "properties": {

        "UBLExtensions": {
          "title": "UBLExtensions",
          "description": "An optional set of extensions to the committee model",
          "items": { 
            "$ref": "../common/UBL-CommonExtensionComponents-2.3.json#/definitions/UBLExtensions" },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },

        "UBLVersionID": {
          "title": "Prior Information Notice. UBL Version Identifier. Identifier",
          "description": "Identifies the earliest version of the UBL 2 schema for this document type that defines all of the elements that might be encountered in the current instance.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/UBLVersionID"
          },
        "CustomizationID": {
          "title": "Prior Information Notice. Customization Identifier. Identifier",
          "description": "Identifies a user-defined customization of UBL for a specific use.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/CustomizationID"
          },
        "ProfileID": {
          "title": "Prior Information Notice. Profile Identifier. Identifier",
          "description": "Identifies a user-defined profile of the customization of UBL being used.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ProfileID"
          },
        "ProfileExecutionID": {
          "title": "Prior Information Notice. Profile Execution Identifier. Identifier",
          "description": "Identifies an instance of executing a profile, to associate all transactions in a collaboration.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ProfileExecutionID"
          },
        "ID": {
          "title": "Prior Information Notice. Identifier",
          "description": "An identifier for this document, assigned by the sender.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ID"
          },
        "CopyIndicator": {
          "title": "Prior Information Notice. Copy_ Indicator. Indicator",
          "description": "Indicates whether this document is a copy (true) or not (false).",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/CopyIndicator"
          },
        "UUID": {
          "title": "Prior Information Notice. UUID. Identifier",
          "description": "A universally unique identifier for an instance of this document.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/UUID"
          },
        "ContractFolderID": {
          "title": "Prior Information Notice. Contract Folder Identifier. Identifier",
          "description": "An identifier, assigned by the sender, for the process file (i.e., record) to which this document belongs.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ContractFolderID"
          },
        "IssueDate": {
          "title": "Prior Information Notice. Issue Date. Date",
          "description": "The date, assigned by the sender, on which this document was issued.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/IssueDate"
          },
        "IssueTime": {
          "title": "Prior Information Notice. Issue Time. Time",
          "description": "The time, assigned by the sender, at which this document was issued.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/IssueTime"
          },
        "Note": {
          "title": "Prior Information Notice. Note. Text",
          "description": "Free-form text pertinent to this document, conveying information that is not contained explicitly in other structures.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/Note"
            },
          "minItems": 1,
          "type": "array"
          },
        "VersionID": {
          "title": "Prior Information Notice. Version Identifier. Identifier",
          "description": "An identifier of the current version of the Prior Information Notice.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/VersionID"
          },
        "PreviousVersionID": {
          "title": "Prior Information Notice. Previous_ Version Identifier. Identifier",
          "description": "An identifier of the previous version of the Prior Information Notice which is superceded by this version.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/PreviousVersionID"
          },
        "RequestedPublicationDate": {
          "title": "Prior Information Notice. Requested_ Publication Date. Date",
          "description": "The requested publication date for this Prior Information Notice.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/RequestedPublicationDate"
          },
        "PlannedDate": {
          "title": "Prior Information Notice. Planned Date. Date",
          "description": "The date planned by the Contracting Party for publication of the contract notice.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/PlannedDate"
          },
        "RegulatoryDomain": {
          "title": "Prior Information Notice. Regulatory Domain. Text",
          "description": "Information about the law that defines the regulatory domain.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/RegulatoryDomain"
            },
          "minItems": 1,
          "type": "array"
          },
        "NoticeTypeCode": {
          "title": "Prior Information Notice. Notice Type Code. Code",
          "description": "The type of notice (PIN, Qualification, Reduce time...)",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/NoticeTypeCode"
          },
        "NoticeLanguageCode": {
          "title": "Prior Information Notice. Notice_ Language Code. Code",
          "description": "The language used for this prior information notice.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/NoticeLanguageCode"
          },
        "AdditionalNoticeLanguage": {
          "title": "Prior Information Notice. Additional Notice_ Language. Language",
          "description": "An additional official language used for this prior information notice.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/AdditionalNoticeLanguage"
            },
          "minItems": 1,
          "type": "array"
          },
        "DocumentReference": {
          "title": "Prior Information Notice. Document Reference",
          "description": "A reference to another document associated with this document.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/DocumentReference"
            },
          "minItems": 1,
          "type": "array"
          },
        "Signature": {
          "title": "Prior Information Notice. Signature",
          "description": "A signature applied to this document.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/Signature"
            },
          "minItems": 1,
          "type": "array"
          },
        "ContractingParty": {
          "title": "Prior Information Notice. Contracting Party",
          "description": "The contracting party or parties in case of joint procurement.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/ContractingParty"
            },
          "minItems": 1,
          "type": "array"
          },
        "OriginatorCustomerParty": {
          "title": "Prior Information Notice. Originator_ Customer Party. Customer Party",
          "description": "A party who originated the tendering process.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/OriginatorCustomerParty"
            },
          "minItems": 1,
          "type": "array"
          },
        "ReceiverParty": {
          "title": "Prior Information Notice. Receiver_ Party. Party",
          "description": "The party receiving this document.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/ReceiverParty"
          },
        "TenderingTerms": {
          "title": "Prior Information Notice. Tendering Terms",
          "description": "The tendering terms associated with this tendering process.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/TenderingTerms"
          },
        "TenderingProcess": {
          "title": "Prior Information Notice. Tendering Process",
          "description": "A description of the tendering process itself.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/TenderingProcess"
          },
        "ProcurementProject": {
          "title": "Prior Information Notice. Procurement Project",
          "description": "An overall definition of this procurement project.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/ProcurementProject"
          },
        "ProcurementProjectLot": {
          "title": "Prior Information Notice. Procurement Project Lot",
          "description": "One of the procurement project lots into which this contract can be split.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/ProcurementProjectLot"
            },
          "minItems": 1,
          "type": "array"
          }
        },
      "additionalProperties": false,
      "type": "object"
      }
    }
  }

=== metasfresh/metasfresh/misc/services/camel/de-metas-camel-externalsystems/com-adekia-exchange/com.adekia.exchange-model/model/UBL-2.3-JSON-v1.0-cn01/json-model/UBL-PriorInformationNotice-2.2-Example-External.json
{"_D":"urn:oasis:names:specification:ubl:schema:xsd:PriorInformationNotice-2",
 "_A":"urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2",
 "_B":"urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2",
 "PriorInformationNotice":{
 "IssueDate":{"_":"2016-05-29"},
 "ContractingParty":[{
  "Party":{
   "PartyIdentification":[{
    "ID":{"_":"Other"}
   }]
  }
 }],
 "TenderingTerms":{
  "TenderPreparation":[{
   "TenderEnvelopeID":{"_":"abc"},
   "TenderEncryptionData":[{
    "MessageFormat":{"_":"1.2.840.113549.1.9.16.0.1"},
    "EncryptionCertificateAttachment":{
     "ExternalReference":{
      "URI":{"_":"www.digst.dk/udbud/NemID.cer "}
     }
    },
    "EncryptionCertificatePathChain":[{
     "URI":{"_":"https://www.trust2408/certPaths/Trust2408_issuingCA12_chain.p7c"}
    }],
    "EncryptionSymmetricAlgorithm":[{
     "OID":{"_":"2.16.840.1.101.3.4.1.2"}
    },{
     "OID":{"_":"2.16.840.1.101.3.4.1.42"}
    }]
   }]
  }]
 }
}}
