=== metasfresh/metasfresh/misc/services/camel/de-metas-camel-externalsystems/com-adekia-exchange/com.adekia.exchange-model/model/UBL-2.3-JSON-v1.0-cn01/json-schema-model/maindoc/UBL-Manifest-2.3.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "json-schema-model/maindoc/UBL-Manifest-2.3.json",
  "description": "\n  Library:           OASIS Universal Business Language (UBL) 2.3 OS\n                     http://docs.oasis-open.org/ubl/os-UBL-2.3/\n  Release Date:      15 June 2021\n  Module:            json-schema-model/maindoc/UBL-Manifest-2.3.json\n  Generated on:      2021-12-15 21:56z\n  Copyright (c) OASIS Open 2021. All Rights Reserved.\n\n\n  OASIS takes no position regarding the validity or scope of any \n  intellectual property or other rights that might be claimed to pertain \n  to the implementation or use of the technology described in this \n  document or the extent to which any license under such rights \n  might or might not be available; neither does it represent that it has \n  made any effort to identify any such rights. Information on OASIS's \n  procedures with respect to rights in OASIS specifications can be \n  found at the OASIS website. Copies of claims of rights made \n  available for publication and any assurances of licenses to be made \n  available, or the result of an attempt made to obtain a general \n  license or permission for the use of such proprietary rights by \n  implementors or users of this specification, can be obtained from \n  the OASIS Executive Director.\n\n  OASIS invites any interested party to bring to its attention any \n  copyrights, patents or patent applications, or other proprietary \n  rights which may cover technology that may be required to \n  implement this specification. Please address the information to the \n  OASIS Executive Director.\n  \n  This document and translations of it may be copied and furnished to \n  others, and derivative works that comment on or otherwise explain \n  it or assist in its implementation may be prepared, copied, \n  published and distributed, in whole or in part, without restriction of \n  any kind, provided that the above copyright notice and this \n  paragraph are included on all such copies and derivative works. \n  However, this document itself may not be modified in any way, \n  such as by removing the copyright notice or references to OASIS, \n  except as needed for the purpose of developing OASIS \n  specifications, in which case the procedures for copyrights defined \n  in the OASIS Intellectual Property Rights document must be \n  followed, or as required to translate it into languages other than \n  English. \n\n  The limited permissions granted above are perpetual and will not be \n  revoked by OASIS or its successors or assigns. \n\n  This document and the information contained herein is provided on \n  an \"AS IS\" basis and OASIS DISCLAIMS ALL WARRANTIES, \n  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO ANY \n  WARRANTY THAT THE USE OF THE INFORMATION HEREIN \n  WILL NOT INFRINGE ANY RIGHTS OR ANY IMPLIED \n  WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A \n  PARTICULAR PURPOSE.    \n",
  "required": [
    "Manifest"
    ],
  "properties": {
    "_D": {
      "description": "Document ABIE XML namespace string",
      "type": "string"
      },
    "_A": {
      "description": "Library ABIE XML namespace string (for ASBIEs)",
      "type": "string"
      },
    "_B": {
      "description": "BBIE XML namespace string",
      "type": "string"
      },
    "_E": {
      "description": "Extension scaffolding XML namespace string",
      "type": "string"
      },
    "Manifest": {
      "description": "A document listing the contents, cargo, passengers and crew of an airplane, a ship, a truck or a vagon.",
      "$ref": "#/definitions/Manifest"
      }
    },
  "additionalProperties": false,
  "type": "object",
  "definitions": {
    "Manifest": {
      "title": "Manifest. Details",
      "description": "A document listing the contents, cargo, passengers and crew of an airplane, a ship, a truck or a vagon.",
      "required": [
        "ID",
        "SendingLogisticsOperatorParty"
        ],
      "properties": {

        "UBLExtensions": {
          "title": "UBLExtensions",
          "description": "An optional set of extensions to the committee model",
          "items": { 
            "$ref": "../common/UBL-CommonExtensionComponents-2.3.json#/definitions/UBLExtensions" },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },

        "UBLVersionID": {
          "title": "Manifest. UBL Version Identifier. Identifier",
          "description": "Identifies the earliest version of the UBL 2 schema for this document type that defines all of the elements that might be encountered in the current instance.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/UBLVersionID"
          },
        "CustomizationID": {
          "title": "Manifest. Customization Identifier. Identifier",
          "description": "Identifies a user-defined customization of UBL for a specific use.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/CustomizationID"
          },
        "ProfileID": {
          "title": "Manifest. Profile Identifier. Identifier",
          "description": "Identifies a user-defined profile of the customization of UBL being used.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ProfileID"
          },
        "ProfileExecutionID": {
          "title": "Manifest. Profile Execution Identifier. Identifier",
          "description": "Identifies an instance of executing a profile, to associate all transactions in a collaboration.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ProfileExecutionID"
          },
        "ID": {
          "title": "Manifest. Identifier",
          "description": "An identifier for this document.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ID"
          },
        "UUID": {
          "title": "Manifest. UUID. Identifier",
          "description": "A universally unique identifier for an instance of this document.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/UUID"
          },
        "IssueDate": {
          "title": "Manifest. Issue Date. Date",
          "description": "The date, assigned by the sender, on which this document was issued.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/IssueDate"
          },
        "IssueTime": {
          "title": "Manifest. Issue Time. Time",
          "description": "The time, assigned by the sender, at which this document was issued.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/IssueTime"
          },
        "ManifestTypeCode": {
          "title": "Manifest. Manifest Type Code. Code",
          "description": "The type of Manifest, expressed as a code.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ManifestTypeCode"
          },
        "ManifestType": {
          "title": "Manifest. Manifest Type. Text",
          "description": "The type of Manifest, expressed as text.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ManifestType"
            },
          "minItems": 1,
          "type": "array"
          },
        "Description": {
          "title": "Manifest. Description. Text",
          "description": "Textual description of this document instance.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/Description"
            },
          "minItems": 1,
          "type": "array"
          },
        "Note": {
          "title": "Manifest. Note. Text",
          "description": "Free-form text pertinent to this document, conveying information that is not contained explicitly in other structures.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/Note"
            },
          "minItems": 1,
          "type": "array"
          },
        "VersionID": {
          "title": "Manifest. Version. Identifier",
          "description": "Identifies a version of a common transportation report in order to distinguish updates.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/VersionID"
          },
        "AdValoremIndicator": {
          "title": "Manifest. Ad Valorem_ Indicator. Indicator",
          "description": "An indicator of whether ad valorem duties are levied on commodities described in this manifest (true) or not (false).",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/AdValoremIndicator"
          },
        "DeclaredCarriageValueAmount": {
          "title": "Manifest. Declared_ Carriage Value. Amount",
          "description": "Value declared by the shipper or his agent for the purpose of varying the carrier's level of liability from that provided in the contract of carriage in case of loss or damage to goods or delayed delivery.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/DeclaredCarriageValueAmount"
          },
        "SendingLogisticsOperatorParty": {
          "title": "Manifest. Sending Logistics Operator_ Party. Party",
          "description": "The logistics operator party issuing this manifest",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/SendingLogisticsOperatorParty"
          },
        "AuthorityParty": {
          "title": "Manifest. Authority_ Party. Party",
          "description": "The authority or regulator receiving this manifest.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/AuthorityParty"
          },
        "ConsignorParty": {
          "title": "Manifest. Consignor_ Party. Party",
          "description": "The party responsible for sending the goods mentioned in this manifest.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/ConsignorParty"
          },
        "ConsigneeParty": {
          "title": "Manifest. Consignee_ Party. Party",
          "description": "The party receiving the goods mentioned in this manifest.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/ConsigneeParty"
          },
        "CrewPerson": {
          "title": "Manifest. Crew_ Person. Person",
          "description": "A person registred as crew in this manifest.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/CrewPerson"
            },
          "minItems": 1,
          "type": "array"
          },
        "PassengerPerson": {
          "title": "Manifest. Passenger_ Person. Person",
          "description": "A person registred as passenger in this manifest",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/PassengerPerson"
            },
          "minItems": 1,
          "type": "array"
          },
        "Shipment": {
          "title": "Manifest. Shipment",
          "description": "A shipment associated with this manifest.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/Shipment"
          },
        "DocumentReference": {
          "title": "Manifest. Document Reference",
          "description": "A reference to a document relevant for or associated with this common transportation report.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/DocumentReference"
            },
          "minItems": 1,
          "type": "array"
          },
        "DocumentDistribution": {
          "title": "Manifest. Document Distribution",
          "description": "An interested party to whom this document is distributed.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/DocumentDistribution"
            },
          "minItems": 1,
          "type": "array"
          },
        "Signature": {
          "title": "Manifest. Signature",
          "description": "A signature applied to this document.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/Signature"
            },
          "minItems": 1,
          "type": "array"
          }
        },
      "additionalProperties": false,
      "type": "object"
      }
    }
  }

=== metasfresh/metasfresh/misc/services/camel/de-metas-camel-externalsystems/com-adekia-exchange/com.adekia.exchange-model/model/UBL-2.3-JSON-v1.0-cn01/json-model/UBL-Manifest-2.3-Example-Shipment.json
{"_D":"urn:oasis:names:specification:ubl:schema:xsd:Manifest-2",
 "_A":"urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2",
 "_B":"urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2",
 "Manifest":{
 "UBLVersionID":{"_":"2.3"},
 "CustomizationID":{"_":"urn:oasis:names:specification:ubl:xpath:ForwardingInstructions-2.0:samples-2.0-draft"},
 "ProfileID":{"_":"bpid:urn:oasis:names:draft:bpss:ubl-2-sample-international-scenario"},
 "ID":{"_":"KHN23-44048"},
 "UUID":{"_":"6E09886B-DC6E-439F-82D1-7C83709652B1"},
 "IssueDate":{"_":"2005-06-24"},
 "IssueTime":{"_":"14:20:00.0Z"},
 "SendingLogisticsOperatorParty":{
  "PartyName":[{
   "Name":{"_":"One-Stop Forwarders"}
  }],
  "PostalAddress":{
   "Postbox":{"_":"99043"},
   "CityName":{"_":"Boston"},
   "PostalZone":{"_":"02210"},
   "CountrySubentityCode":{"_":"MA"},
   "Country":{
    "IdentificationCode":{"_":"US"}
   }
  },
  "Contact":{
   "Name":{"_":"Con Solidador"},
   "Telephone":{"_":" +1 343 1453654"},
   "Telefax":{"_":"+1 343 1453655"},
   "ElectronicMail":{"_":"ctanner@onestopfreight.com"}
  }
 },
 "ConsignorParty":{
  "PartyName":[{
   "Name":{"_":"Consortial"}
  }],
  "PostalAddress":{
   "StreetName":{"_":"Boston Road"},
   "BuildingName":{"_":"Suite M-102"},
   "BuildingNumber":{"_":"630"},
   "CityName":{"_":"Billerica"},
   "PostalZone":{"_":"01821"},
   "CountrySubentity":{"_":"Massachusetts"},
   "CountrySubentityCode":{"_":"MA"},
   "Country":{
    "IdentificationCode":{"_":"US"}
   }
  },
  "Contact":{
   "Name":{"_":"Mrs Bouquet"},
   "Telephone":{"_":" +1 158 1233714"},
   "Telefax":{"_":"+ 1 158 1233856"},
   "ElectronicMail":{"_":"bouquet@fpconsortial.com"}
  }
 },
 "ConsigneeParty":{
  "PartyName":[{
   "Name":{"_":"IYT Corporation"}
  }],
  "PostalAddress":{
   "StreetName":{"_":"Avon Way"},
   "BuildingName":{"_":"Thereabouts"},
   "BuildingNumber":{"_":"56A"},
   "CityName":{"_":"Bridgtow"},
   "PostalZone":{"_":"ZZ99 1ZZ"},
   "CountrySubentity":{"_":"Avon"},
   "AddressLine":[{
    "Line":{"_":"3rd Floor, Room 5"}
   }],
   "Country":{
    "IdentificationCode":{"_":"GB"}
   }
  },
  "Contact":{
   "Name":{"_":"Mr Fred Churchill"},
   "Telephone":{"_":"+44 127 2653214"},
   "Telefax":{"_":"+44 127 2653215"},
   "ElectronicMail":{"_":"fred@iytcorporation.gov.uk"}
  }
 },
 "Shipment":{
  "ID":{"_":"CONS-0001"},
  "GrossWeightMeasure":{"_":130,
   "unitCode":"KGM"},
  "NetWeightMeasure":{"_":110,
   "unitCode":"KGM"},
  "NetNetWeightMeasure":{"_":100,
   "unitCode":"KGM"},
  "GrossVolumeMeasure":{"_":2,
   "unitCode":"MTQ"},
  "NetVolumeMeasure":{"_":2.235,
   "unitCode":"MTQ"},
  "TotalGoodsItemQuantity":{"_":1},
  "TotalTransportHandlingUnitQuantity":{"_":10},
  "InsuranceValueAmount":{"_":1000.00,
   "currencyID":"USD"},
  "DeclaredCustomsValueAmount":{"_":524.80,
   "currencyID":"GBP"},
  "FreeOnBoardValueAmount":{"_":1200.00,
   "currencyID":"USD"},
  "SpecialInstructions":[{"_":"Beeswax becomes liquid at 50'C"}],
  "Consignment":[{
   "ID":{"_":"CONS-0001"},
   "TariffDescription":[{"_":"Beeswax, other insect waxes and spermacetti"}],
   "TariffCode":{"_":"15219000"},
   "HazardousRiskIndicator":{"_":false},
   "ConsigneeParty":{
    "PartyName":[{
     "Name":{"_":"IYT Corporation"}
    }],
    "PostalAddress":{
     "StreetName":{"_":"Avon Way"},
     "BuildingName":{"_":"Thereabouts"},
     "BuildingNumber":{"_":"56A"},
     "CityName":{"_":"Bridgtow"},
     "PostalZone":{"_":"ZZ99 1ZZ"},
     "CountrySubentity":{"_":"Avon"},
     "AddressLine":[{
      "Line":{"_":"3rd Floor, Room 5"}
     }],
     "Country":{
      "IdentificationCode":{"_":"GB"}
     }
    },
    "Contact":{
     "Name":{"_":"Mr Fred Churchill"},
     "Telephone":{"_":"+44 127 2653214"},
     "Telefax":{"_":"+44 127 2653215"},
     "ElectronicMail":{"_":"fred@iytcorporation.gov.uk"}
    }
   },
   "NotifyParty":{
    "PartyName":[{
     "Name":{"_":"IYT Corporation"}
    }],
    "PostalAddress":{
     "StreetName":{"_":"Avon Way"},
     "BuildingName":{"_":"Thereabouts"},
     "BuildingNumber":{"_":"56A"},
     "CityName":{"_":"Bridgtow"},
     "PostalZone":{"_":"ZZ99 1ZZ"},
     "CountrySubentity":{"_":"Avon"},
     "AddressLine":[{
      "Line":{"_":"3rd Floor, Room 5"}
     }],
     "Country":{
      "IdentificationCode":{"_":"GB"}
     }
    },
    "Contact":{
     "Name":{"_":"Mr Fred Churchill"},
     "Telephone":{"_":"+44 127 2653214"},
     "Telefax":{"_":"+44 127 2653215"},
     "ElectronicMail":{"_":"fred@iytcorporation.gov.uk"}
    }
   },
   "FinalDeliveryParty":{
    "PartyName":[{
     "Name":{"_":"The Terminus"}
    }],
    "PostalAddress":{
     "StreetName":{"_":"Avon Way"},
     "BuildingName":{"_":"Thereabouts"},
     "BuildingNumber":{"_":"56A"},
     "CityName":{"_":"Bridgtow"},
     "PostalZone":{"_":"ZZ99 1ZZ"},
     "CountrySubentity":{"_":"Avon"},
     "AddressLine":[{
      "Line":{"_":"3rd Floor, Room 5"}
     }],
     "Country":{
      "IdentificationCode":{"_":"GB"}
     }
    },
    "Contact":{
     "Name":{"_":"S Massiah"},
     "Telephone":{"_":"+ 44 127 98876545"},
     "Telefax":{"_":"+ 44 127 98876546"},
     "ElectronicMail":{"_":"smassiah@the-email.co.uk"}
    }
   },
   "OriginalDepartureCountry":{
    "IdentificationCode":{"_":"US"}
   },
   "FinalDestinationCountry":{
    "IdentificationCode":{"_":"GB"}
   },
   "DeliveryTerms":{
    "ID":{"_":"FOB Destination"},
    "DeliveryLocation":{
     "ID":{"_":"GBBRS",
      "schemeAgencyID":"6",
      "schemeID":"UN/LOCODE"},
     "Description":[{"_":"Bristol"}]
    }
   },
   "FreightAllowanceCharge":[{
    "ChargeIndicator":{"_":true},
    "AllowanceChargeReason":[{"_":"Freight charges"}],
    "SequenceNumeric":{"_":1},
    "Amount":{"_":254.00,
     "currencyID":"USD"}
   },{
    "ChargeIndicator":{"_":false},
    "AllowanceChargeReasonCode":{"_":"79"},
    "AllowanceChargeReason":[{"_":"Sundry discount"}],
    "MultiplierFactorNumeric":{"_":0.05},
    "SequenceNumeric":{"_":2},
    "Amount":{"_":12.70,
     "currencyID":"USD"},
    "BaseAmount":{"_":254.00,
     "currencyID":"USD"}
   }]
  }],
  "GoodsItem":[{
   "ID":{"_":"1"},
   "SequenceNumberID":{"_":"1"},
   "Description":[{"_":"Acme beeswax"}],
   "HazardousRiskIndicator":{"_":false},
   "DeclaredCustomsValueAmount":{"_":524.80,
    "currencyID":"GBP"},
   "DeclaredStatisticsValueAmount":{"_":1000.00,
    "currencyID":"USD"},
   "FreeOnBoardValueAmount":{"_":1241.30,
    "currencyID":"USD"},
   "InsuranceValueAmount":{"_":1241.30,
    "currencyID":"USD"},
   "ValueAmount":{"_":1000.00,
    "currencyID":"USD"},
   "GrossWeightMeasure":{"_":130,
    "unitCode":"KGM"},
   "NetWeightMeasure":{"_":110,
    "unitCode":"KGM"},
   "NetNetWeightMeasure":{"_":100,
    "unitCode":"KGM"},
   "GrossVolumeMeasure":{"_":2,
    "unitCode":"MTQ"},
   "NetVolumeMeasure":{"_":2.235,
    "unitCode":"MTQ"},
   "Quantity":{"_":10},
   "RequiredCustomsID":{"_":"ECN12344566"},
   "CustomsStatusCode":{"_":"Cleared"},
   "CustomsTariffQuantity":{"_":100},
   "Item":[{
    "Description":[{"_":"Beeswax"}],
    "Name":{"_":"Acme Beeswax"},
    "BuyersItemIdentification":{
     "ID":{"_":"6578489"}
    },
    "SellersItemIdentification":{
     "ID":{"_":"17589683"}
    }
   }]
  }]
 },
 "DocumentReference":[{
  "ID":{"_":"234534533"},
  "DocumentType":[{"_":"CMR"}],
  "IssuerParty":{
   "PartyName":[{
    "Name":{"_":"Boston Road"}
   }]
  }
 },{
  "ID":{"_":"2343456533"},
  "DocumentType":[{"_":"CMR"}],
  "IssuerParty":{
   "PartyName":[{
    "Name":{"_":"Boston Road"}
   }]
  }
 },{
  "ID":{"_":"XD534533"},
  "DocumentType":[{"_":"BOL"}],
  "IssuerParty":{
   "PartyName":[{
    "Name":{"_":"Maersk"}
   }]
  }
 }]
}}

=== metasfresh/metasfresh/misc/services/camel/de-metas-camel-externalsystems/com-adekia-exchange/com.adekia.exchange-model/model/UBL-2.3-JSON-v1.0-cn01/json-model/UBL-Manifest-2.3-Example-Reference-Only.json
{"_D":"urn:oasis:names:specification:ubl:schema:xsd:Manifest-2",
 "_A":"urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2",
 "_B":"urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2",
 "Manifest":{
 "UBLVersionID":{"_":"2.3"},
 "CustomizationID":{"_":"urn:oasis:names:specification:ubl:xpath:ForwardingInstructions-2.0:samples-2.0-draft"},
 "ProfileID":{"_":"bpid:urn:oasis:names:draft:bpss:ubl-2-sample-international-scenario"},
 "ID":{"_":"KHN23-44048"},
 "UUID":{"_":"6E09886B-DC6E-439F-82D1-7C83709652B1"},
 "IssueDate":{"_":"2005-06-24"},
 "IssueTime":{"_":"14:20:00.0Z"},
 "SendingLogisticsOperatorParty":{
  "PartyName":[{
   "Name":{"_":"One-Stop Forwarders"}
  }],
  "PostalAddress":{
   "Postbox":{"_":"99043"},
   "CityName":{"_":"Boston"},
   "PostalZone":{"_":"02210"},
   "CountrySubentityCode":{"_":"MA"},
   "Country":{
    "IdentificationCode":{"_":"US"}
   }
  },
  "Contact":{
   "Name":{"_":"Con Solidador"},
   "Telephone":{"_":" +1 343 1453654"},
   "Telefax":{"_":"+1 343 1453655"},
   "ElectronicMail":{"_":"ctanner@onestopfreight.com"}
  }
 },
 "ConsignorParty":{
  "PartyName":[{
   "Name":{"_":"Consortial"}
  }],
  "PostalAddress":{
   "StreetName":{"_":"Boston Road"},
   "BuildingName":{"_":"Suite M-102"},
   "BuildingNumber":{"_":"630"},
   "CityName":{"_":"Billerica"},
   "PostalZone":{"_":"01821"},
   "CountrySubentity":{"_":"Massachusetts"},
   "CountrySubentityCode":{"_":"MA"},
   "Country":{
    "IdentificationCode":{"_":"US"}
   }
  },
  "Contact":{
   "Name":{"_":"Mrs Bouquet"},
   "Telephone":{"_":" +1 158 1233714"},
   "Telefax":{"_":"+ 1 158 1233856"},
   "ElectronicMail":{"_":"bouquet@fpconsortial.com"}
  }
 },
 "ConsigneeParty":{
  "PartyName":[{
   "Name":{"_":"IYT Corporation"}
  }],
  "PostalAddress":{
   "StreetName":{"_":"Avon Way"},
   "BuildingName":{"_":"Thereabouts"},
   "BuildingNumber":{"_":"56A"},
   "CityName":{"_":"Bridgtow"},
   "PostalZone":{"_":"ZZ99 1ZZ"},
   "CountrySubentity":{"_":"Avon"},
   "AddressLine":[{
    "Line":{"_":"3rd Floor, Room 5"}
   }],
   "Country":{
    "IdentificationCode":{"_":"GB"}
   }
  },
  "Contact":{
   "Name":{"_":"Mr Fred Churchill"},
   "Telephone":{"_":"+44 127 2653214"},
   "Telefax":{"_":"+44 127 2653215"},
   "ElectronicMail":{"_":"fred@iytcorporation.gov.uk"}
  }
 },
 "DocumentReference":[{
  "ID":{"_":"234534533"},
  "DocumentType":[{"_":"CMR"}],
  "IssuerParty":{
   "PartyName":[{
    "Name":{"_":"Boston Road"}
   }]
  }
 },{
  "ID":{"_":"2343456533"},
  "DocumentType":[{"_":"CMR"}],
  "IssuerParty":{
   "PartyName":[{
    "Name":{"_":"Boston Road"}
   }]
  }
 },{
  "ID":{"_":"XD534533"},
  "DocumentType":[{"_":"BOL"}],
  "IssuerParty":{
   "PartyName":[{
    "Name":{"_":"Maersk"}
   }]
  }
 }]
}}
