=== metasfresh/metasfresh/misc/services/camel/de-metas-camel-externalsystems/com-adekia-exchange/com.adekia.exchange-model/model/UBL-2.3-JSON-v1.0-cn01/json-schema-model/maindoc/UBL-Quotation-2.3.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "json-schema-model/maindoc/UBL-Quotation-2.3.json",
  "description": "\n  Library:           OASIS Universal Business Language (UBL) 2.3 OS\n                     http://docs.oasis-open.org/ubl/os-UBL-2.3/\n  Release Date:      15 June 2021\n  Module:            json-schema-model/maindoc/UBL-Quotation-2.3.json\n  Generated on:      2021-12-15 21:56z\n  Copyright (c) OASIS Open 2021. All Rights Reserved.\n\n\n  OASIS takes no position regarding the validity or scope of any \n  intellectual property or other rights that might be claimed to pertain \n  to the implementation or use of the technology described in this \n  document or the extent to which any license under such rights \n  might or might not be available; neither does it represent that it has \n  made any effort to identify any such rights. Information on OASIS's \n  procedures with respect to rights in OASIS specifications can be \n  found at the OASIS website. Copies of claims of rights made \n  available for publication and any assurances of licenses to be made \n  available, or the result of an attempt made to obtain a general \n  license or permission for the use of such proprietary rights by \n  implementors or users of this specification, can be obtained from \n  the OASIS Executive Director.\n\n  OASIS invites any interested party to bring to its attention any \n  copyrights, patents or patent applications, or other proprietary \n  rights which may cover technology that may be required to \n  implement this specification. Please address the information to the \n  OASIS Executive Director.\n  \n  This document and translations of it may be copied and furnished to \n  others, and derivative works that comment on or otherwise explain \n  it or assist in its implementation may be prepared, copied, \n  published and distributed, in whole or in part, without restriction of \n  any kind, provided that the above copyright notice and this \n  paragraph are included on all such copies and derivative works. \n  However, this document itself may not be modified in any way, \n  such as by removing the copyright notice or references to OASIS, \n  except as needed for the purpose of developing OASIS \n  specifications, in which case the procedures for copyrights defined \n  in the OASIS Intellectual Property Rights document must be \n  followed, or as required to translate it into languages other than \n  English. \n\n  The limited permissions granted above are perpetual and will not be \n  revoked by OASIS or its successors or assigns. \n\n  This document and the information contained herein is provided on \n  an \"AS IS\" basis and OASIS DISCLAIMS ALL WARRANTIES, \n  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO ANY \n  WARRANTY THAT THE USE OF THE INFORMATION HEREIN \n  WILL NOT INFRINGE ANY RIGHTS OR ANY IMPLIED \n  WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A \n  PARTICULAR PURPOSE.    \n",
  "required": [
    "Quotation"
    ],
  "properties": {
    "_D": {
      "description": "Document ABIE XML namespace string",
      "type": "string"
      },
    "_A": {
      "description": "Library ABIE XML namespace string (for ASBIEs)",
      "type": "string"
      },
    "_B": {
      "description": "BBIE XML namespace string",
      "type": "string"
      },
    "_E": {
      "description": "Extension scaffolding XML namespace string",
      "type": "string"
      },
    "Quotation": {
      "description": "A document used to quote for the provision of goods and services.",
      "$ref": "#/definitions/Quotation"
      }
    },
  "additionalProperties": false,
  "type": "object",
  "definitions": {
    "Quotation": {
      "title": "Quotation. Details",
      "description": "A document used to quote for the provision of goods and services.",
      "required": [
        "IssueDate",
        "SellerSupplierParty",
        "QuotedMonetaryTotal",
        "QuotationLine"
        ],
      "properties": {

        "UBLExtensions": {
          "title": "UBLExtensions",
          "description": "An optional set of extensions to the committee model",
          "items": { 
            "$ref": "../common/UBL-CommonExtensionComponents-2.3.json#/definitions/UBLExtensions" },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },

        "UBLVersionID": {
          "title": "Quotation. UBL Version Identifier. Identifier",
          "description": "Identifies the earliest version of the UBL 2 schema for this document type that defines all of the elements that might be encountered in the current instance.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/UBLVersionID"
          },
        "CustomizationID": {
          "title": "Quotation. Customization Identifier. Identifier",
          "description": "Identifies a user-defined customization of UBL for a specific use.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/CustomizationID"
          },
        "ProfileID": {
          "title": "Quotation. Profile Identifier. Identifier",
          "description": "Identifies a user-defined profile of the subset of UBL being used.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ProfileID"
          },
        "ProfileExecutionID": {
          "title": "Quotation. Profile Execution Identifier. Identifier",
          "description": "Identifies an instance of executing a profile, to associate all transactions in a collaboration.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ProfileExecutionID"
          },
        "ID": {
          "title": "Quotation. Identifier",
          "description": "An identifier for this document, assigned by the sender.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ID"
          },
        "CopyIndicator": {
          "title": "Quotation. Copy_ Indicator. Indicator",
          "description": "Indicates whether this document is a copy (true) or not (false).",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/CopyIndicator"
          },
        "UUID": {
          "title": "Quotation. UUID. Identifier",
          "description": "A universally unique identifier for an instance of this document.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/UUID"
          },
        "IssueDate": {
          "title": "Quotation. Issue Date. Date",
          "description": "The date, assigned by the sender, on which this document was issued.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/IssueDate"
          },
        "IssueTime": {
          "title": "Quotation. Issue Time. Time",
          "description": "The time, assigned by the sender, at which this document was issued.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/IssueTime"
          },
        "Note": {
          "title": "Quotation. Note. Text",
          "description": "Free-form text pertinent to this document, conveying information that is not contained explicitly in other structures.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/Note"
            },
          "minItems": 1,
          "type": "array"
          },
        "PricingCurrencyCode": {
          "title": "Quotation. Pricing_ Currency Code. Code",
          "description": "A code signifying the currency used for all prices in the Quotation.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/PricingCurrencyCode"
          },
        "LineCountNumeric": {
          "title": "Quotation. Line Count. Numeric",
          "description": "The number of Quotation Lines in this document.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/LineCountNumeric"
          },
        "ValidityPeriod": {
          "title": "Quotation. Validity_ Period. Period",
          "description": "The period for which the Quotation is valid.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/ValidityPeriod"
          },
        "RequestForQuotationDocumentReference": {
          "title": "Quotation. Request For Quotation_ Document Reference. Document Reference",
          "description": "A reference to the Request for Quotation associated with this Quotation.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/RequestForQuotationDocumentReference"
          },
        "AdditionalDocumentReference": {
          "title": "Quotation. Additional_ Document Reference. Document Reference",
          "description": "A reference to an additional document associated with this document.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/AdditionalDocumentReference"
            },
          "minItems": 1,
          "type": "array"
          },
        "Contract": {
          "title": "Quotation. Contract",
          "description": "A contract associated with this Quotation.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/Contract"
            },
          "minItems": 1,
          "type": "array"
          },
        "Signature": {
          "title": "Quotation. Signature",
          "description": "A signature applied to this document.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/Signature"
            },
          "minItems": 1,
          "type": "array"
          },
        "SellerSupplierParty": {
          "title": "Quotation. Seller_ Supplier Party. Supplier Party",
          "description": "The seller.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/SellerSupplierParty"
          },
        "BuyerCustomerParty": {
          "title": "Quotation. Buyer_ Customer Party. Customer Party",
          "description": "Association to the Buyer.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/BuyerCustomerParty"
          },
        "OriginatorCustomerParty": {
          "title": "Quotation. Originator_ Customer Party. Customer Party",
          "description": "The originator.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/OriginatorCustomerParty"
          },
        "Delivery": {
          "title": "Quotation. Delivery",
          "description": "A delivery associated with this document.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/Delivery"
            },
          "minItems": 1,
          "type": "array"
          },
        "DeliveryTerms": {
          "title": "Quotation. Delivery Terms",
          "description": "A set of delivery terms associated with this document.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/DeliveryTerms"
          },
        "PaymentMeans": {
          "title": "Quotation. Payment Means",
          "description": "Expected means of payment.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/PaymentMeans"
          },
        "TransactionConditions": {
          "title": "Quotation. Transaction Conditions",
          "description": "A specification of purchasing, sales, or payment conditions applying to Orders related to this Quotation.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/TransactionConditions"
          },
        "AllowanceCharge": {
          "title": "Quotation. Allowance Charge",
          "description": "A discount or charge that applies to a price component.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/AllowanceCharge"
            },
          "minItems": 1,
          "type": "array"
          },
        "DestinationCountry": {
          "title": "Quotation. Destination_ Country. Country",
          "description": "The country of destination of potential orders (for customs purposes).",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/DestinationCountry"
          },
        "TaxTotal": {
          "title": "Quotation. Tax Total",
          "description": "The total amount of a specific type of tax.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/TaxTotal"
            },
          "minItems": 1,
          "type": "array"
          },
        "QuotedMonetaryTotal": {
          "title": "Quotation. Quoted_ Monetary Total. Monetary Total",
          "description": "The total amount of the Quotation.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/QuotedMonetaryTotal"
          },
        "QuotationLine": {
          "title": "Quotation. Quotation Line",
          "description": "A line quoting a cost for one kind of item.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/QuotationLine"
            },
          "minItems": 1,
          "type": "array"
          }
        },
      "additionalProperties": false,
      "type": "object"
      }
    }
  }

=== metasfresh/metasfresh/misc/services/camel/de-metas-camel-externalsystems/com-adekia-exchange/com.adekia.exchange-model/model/UBL-2.3-JSON-v1.0-cn01/json-model/UBL-Quotation-2.0-Example.json
{"_D":"urn:oasis:names:specification:ubl:schema:xsd:Quotation-2",
 "_A":"urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2",
 "_B":"urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2",
 "Quotation":{
 "UBLVersionID":{"_":"2.0"},
 "CustomizationID":{"_":"urn:oasis:names:specification:ubl:schema:xsd:Quotation-2-draft"},
 "ProfileID":{"_":"bpid:urn:oasis:names:draft:bpss:ubl-2-sbs-request-for-quotation-draft"},
 "ID":{"_":"QIY7655"},
 "CopyIndicator":{"_":false},
 "UUID":{"_":"4D07786B-DA6D-439F-82D1-6FFFC7F4E3B1"},
 "IssueDate":{"_":"2005-06-20"},
 "Note":[{"_":"sample"}],
 "ValidityPeriod":{
  "StartDate":{"_":"2005-06-20"},
  "EndDate":{"_":"2005-07-20"}
 },
 "RequestForQuotationDocumentReference":{
  "ID":{"_":"G867B"},
  "UUID":{"_":"8D076867-AE6D-439F-8281-5AAFC7F4E3B1"},
  "IssueDate":{"_":"2005-06-19"}
 },
 "SellerSupplierParty":{
  "CustomerAssignedAccountID":{"_":"CO001"},
  "Party":{
   "PartyName":[{
    "Name":{"_":"Consortial"}
   }],
   "PostalAddress":{
    "StreetName":{"_":"Busy Street"},
    "BuildingName":{"_":"Thereabouts"},
    "BuildingNumber":{"_":"56A"},
    "CityName":{"_":"Farthing"},
    "PostalZone":{"_":"AA99 1BB"},
    "CountrySubentity":{"_":"Heremouthshire"},
    "AddressLine":[{
     "Line":{"_":"The Roundabout"}
    }],
    "Country":{
     "IdentificationCode":{"_":"GB"}
    }
   },
   "PartyTaxScheme":[{
    "RegistrationName":{"_":"Farthing Purchasing Consortium"},
    "CompanyID":{"_":"175 269 2355"},
    "ExemptionReason":[{"_":"N/A"}],
    "TaxScheme":{
     "ID":{"_":"VAT"},
     "TaxTypeCode":{"_":"VAT"}
    }
   }],
   "Contact":{
    "Name":{"_":"Mrs Bouquet"},
    "Telephone":{"_":"0158 1233714"},
    "Telefax":{"_":"0158 1233856"},
    "ElectronicMail":{"_":"bouquet@fpconsortial.co.uk"}
   }
  }
 },
 "OriginatorCustomerParty":{
  "Party":{
   "PartyName":[{
    "Name":{"_":"The Terminus"}
   }],
   "PostalAddress":{
    "StreetName":{"_":"Avon Way"},
    "BuildingName":{"_":"Thereabouts"},
    "BuildingNumber":{"_":"56A"},
    "CityName":{"_":"Bridgtow"},
    "PostalZone":{"_":"ZZ99 1ZZ"},
    "CountrySubentity":{"_":"Avon"},
    "AddressLine":[{
     "Line":{"_":"3rd Floor, Room 5"}
    }],
    "Country":{
     "IdentificationCode":{"_":"GB"}
    }
   },
   "PartyTaxScheme":[{
    "RegistrationName":{"_":"Bridgtow District Council"},
    "CompanyID":{"_":"12356478"},
    "ExemptionReason":[{"_":"Local Authority"}],
    "TaxScheme":{
     "ID":{"_":"UK VAT"},
     "TaxTypeCode":{"_":"VAT"}
    }
   }],
   "Contact":{
    "Name":{"_":"S Massiah"},
    "Telephone":{"_":"0127 98876545"},
    "Telefax":{"_":"0127 98876546"},
    "ElectronicMail":{"_":"smassiah@the-email.co.uk"}
   }
  }
 },
 "Delivery":[{
  "DeliveryAddress":{
   "StreetName":{"_":"Avon Way"},
   "BuildingName":{"_":"Thereabouts"},
   "BuildingNumber":{"_":"56A"},
   "CityName":{"_":"Bridgtow"},
   "PostalZone":{"_":"ZZ99 1ZZ"},
   "CountrySubentity":{"_":"Avon"},
   "AddressLine":[{
    "Line":{"_":"3rd Floor, Room 5"}
   }],
   "Country":{
    "IdentificationCode":{"_":"GB"}
   }
  },
  "RequestedDeliveryPeriod":{
   "StartDate":{"_":"2005-06-29"},
   "StartTime":{"_":"09:30:47.0Z"},
   "EndDate":{"_":"2005-06-29"},
   "EndTime":{"_":"09:30:47.0Z"}
  }
 }],
 "DeliveryTerms":{
  "SpecialTerms":[{"_":"1% deduction for late delivery as per contract"}]
 },
 "PaymentMeans":{
  "PaymentMeansCode":{"_":"20"},
  "PayeeFinancialAccount":{
   "ID":{"_":"12345678"},
   "Name":{"_":"Farthing Purchasing Consortium"},
   "AccountTypeCode":{"_":"Current"},
   "CurrencyCode":{"_":"GBP"},
   "FinancialInstitutionBranch":{
    "ID":{"_":"10-26-58"},
    "Name":{"_":"Open Bank Ltd, Bridgstow Branch "},
    "FinancialInstitution":{
     "ID":{"_":"10-26-58"},
     "Name":{"_":"Open Bank Ltd"},
     "Address":{
      "StreetName":{"_":"City Road"},
      "BuildingName":{"_":"Banking House"},
      "BuildingNumber":{"_":"12"},
      "CityName":{"_":"London"},
      "PostalZone":{"_":"AQ1 6TH"},
      "CountrySubentity":{"_":"London\n"},
      "AddressLine":[{
       "Line":{"_":"5th Floor"}
      }],
      "Country":{
       "IdentificationCode":{"_":"GB"}
      }
     }
    },
    "Address":{
     "StreetName":{"_":"Busy Street"},
     "BuildingName":{"_":"The Mall"},
     "BuildingNumber":{"_":"152"},
     "CityName":{"_":"Farthing"},
     "PostalZone":{"_":"AA99 1BB"},
     "CountrySubentity":{"_":"Heremouthshire"},
     "AddressLine":[{
      "Line":{"_":"West Wing"}
     }],
     "Country":{
      "IdentificationCode":{"_":"GB"}
     }
    }
   },
   "Country":{
    "IdentificationCode":{"_":"GB"}
   }
  }
 },
 "TransactionConditions":{
  "Description":[{"_":"order response required; payment is by BACS or by cheque"}]
 },
 "AllowanceCharge":[{
  "ChargeIndicator":{"_":false},
  "AllowanceChargeReasonCode":{"_":"17"},
  "MultiplierFactorNumeric":{"_":0.10},
  "Amount":{"_":10.00,
   "currencyID":"GBP"}
 }],
 "DestinationCountry":{
  "IdentificationCode":{"_":"GB"},
  "Name":{"_":"Great Britain"}
 },
 "TaxTotal":[{
  "TaxAmount":{"_":17.50,
   "currencyID":"GBP"},
  "TaxEvidenceIndicator":{"_":false},
  "TaxSubtotal":[{
   "TaxableAmount":{"_":100.00,
    "currencyID":"GBP"},
   "TaxAmount":{"_":17.50,
    "currencyID":"GBP"},
   "TaxCategory":{
    "ID":{"_":"A"},
    "TaxScheme":{
     "ID":{"_":"UK VAT"},
     "TaxTypeCode":{"_":"VAT"}
    }
   }
  }]
 }],
 "QuotedMonetaryTotal":{
  "LineExtensionAmount":{"_":100.00,
   "currencyID":"GBP"},
  "TaxExclusiveAmount":{"_":90.00,
   "currencyID":"GBP"},
  "PayableAmount":{"_":107.50,
   "currencyID":"GBP"}
 },
 "QuotationLine":[{
  "ID":{"_":"1"},
  "Note":[{"_":"sample"}],
  "LineItem":{
   "ID":{"_":"1"},
   "Quantity":{"_":100,
    "unitCode":"KGM"},
   "LineExtensionAmount":{"_":100.00,
    "currencyID":"GBP"},
   "TotalTaxAmount":{"_":17.50,
    "currencyID":"GBP"},
   "Price":{
    "PriceAmount":{"_":100.00,
     "currencyID":"GBP"},
    "BaseQuantity":{"_":1,
     "unitCode":"KGM"}
   },
   "Item":{
    "Description":[{"_":"Acme beeswax"}],
    "Name":{"_":"beeswax"},
    "BuyersItemIdentification":{
     "ID":{"_":"6578489"}
    },
    "SellersItemIdentification":{
     "ID":{"_":"17589683"}
    }
   }
  }
 }]
}}
