=== metasfresh/metasfresh/misc/services/camel/de-metas-camel-externalsystems/com-adekia-exchange/com.adekia.exchange-model/model/UBL-2.3-JSON-v1.0-cn01/json-schema-model/maindoc/UBL-RequestForQuotation-2.3.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "json-schema-model/maindoc/UBL-RequestForQuotation-2.3.json",
  "description": "\n  Library:           OASIS Universal Business Language (UBL) 2.3 OS\n                     http://docs.oasis-open.org/ubl/os-UBL-2.3/\n  Release Date:      15 June 2021\n  Module:            json-schema-model/maindoc/UBL-RequestForQuotation-2.3.json\n  Generated on:      2021-12-15 21:56z\n  Copyright (c) OASIS Open 2021. All Rights Reserved.\n\n\n  OASIS takes no position regarding the validity or scope of any \n  intellectual property or other rights that might be claimed to pertain \n  to the implementation or use of the technology described in this \n  document or the extent to which any license under such rights \n  might or might not be available; neither does it represent that it has \n  made any effort to identify any such rights. Information on OASIS's \n  procedures with respect to rights in OASIS specifications can be \n  found at the OASIS website. Copies of claims of rights made \n  available for publication and any assurances of licenses to be made \n  available, or the result of an attempt made to obtain a general \n  license or permission for the use of such proprietary rights by \n  implementors or users of this specification, can be obtained from \n  the OASIS Executive Director.\n\n  OASIS invites any interested party to bring to its attention any \n  copyrights, patents or patent applications, or other proprietary \n  rights which may cover technology that may be required to \n  implement this specification. Please address the information to the \n  OASIS Executive Director.\n  \n  This document and translations of it may be copied and furnished to \n  others, and derivative works that comment on or otherwise explain \n  it or assist in its implementation may be prepared, copied, \n  published and distributed, in whole or in part, without restriction of \n  any kind, provided that the above copyright notice and this \n  paragraph are included on all such copies and derivative works. \n  However, this document itself may not be modified in any way, \n  such as by removing the copyright notice or references to OASIS, \n  except as needed for the purpose of developing OASIS \n  specifications, in which case the procedures for copyrights defined \n  in the OASIS Intellectual Property Rights document must be \n  followed, or as required to translate it into languages other than \n  English. \n\n  The limited permissions granted above are perpetual and will not be \n  revoked by OASIS or its successors or assigns. \n\n  This document and the information contained herein is provided on \n  an \"AS IS\" basis and OASIS DISCLAIMS ALL WARRANTIES, \n  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO ANY \n  WARRANTY THAT THE USE OF THE INFORMATION HEREIN \n  WILL NOT INFRINGE ANY RIGHTS OR ANY IMPLIED \n  WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A \n  PARTICULAR PURPOSE.    \n",
  "required": [
    "RequestForQuotation"
    ],
  "properties": {
    "_D": {
      "description": "Document ABIE XML namespace string",
      "type": "string"
      },
    "_A": {
      "description": "Library ABIE XML namespace string (for ASBIEs)",
      "type": "string"
      },
    "_B": {
      "description": "BBIE XML namespace string",
      "type": "string"
      },
    "_E": {
      "description": "Extension scaffolding XML namespace string",
      "type": "string"
      },
    "RequestForQuotation": {
      "description": "A document used to request a Quotation for goods and services from a Seller.",
      "$ref": "#/definitions/RequestForQuotation"
      }
    },
  "additionalProperties": false,
  "type": "object",
  "definitions": {
    "RequestForQuotation": {
      "title": "Request For Quotation. Details",
      "description": "A document used to request a Quotation for goods and services from a Seller.",
      "required": [
        "IssueDate",
        "IssueTime",
        "SellerSupplierParty",
        "RequestForQuotationLine"
        ],
      "properties": {

        "UBLExtensions": {
          "title": "UBLExtensions",
          "description": "An optional set of extensions to the committee model",
          "items": { 
            "$ref": "../common/UBL-CommonExtensionComponents-2.3.json#/definitions/UBLExtensions" },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },

        "UBLVersionID": {
          "title": "Request For Quotation. UBL Version Identifier. Identifier",
          "description": "Identifies the earliest version of the UBL 2 schema for this document type that defines all of the elements that might be encountered in the current instance.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/UBLVersionID"
          },
        "CustomizationID": {
          "title": "Request For Quotation. Customization Identifier. Identifier",
          "description": "Identifies a user-defined customization of UBL for a specific use.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/CustomizationID"
          },
        "ProfileID": {
          "title": "Request For Quotation. Profile Identifier. Identifier",
          "description": "Identifies a user-defined profile of the customization of UBL being used.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ProfileID"
          },
        "ProfileExecutionID": {
          "title": "Request For Quotation. Profile Execution Identifier. Identifier",
          "description": "Identifies an instance of executing a profile, to associate all transactions in a collaboration.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ProfileExecutionID"
          },
        "ID": {
          "title": "Request For Quotation. Identifier",
          "description": "An identifier for this document, assigned by the sender.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ID"
          },
        "CopyIndicator": {
          "title": "Request For Quotation. Copy_ Indicator. Indicator",
          "description": "Indicates whether this document is a copy (true) or not (false).",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/CopyIndicator"
          },
        "UUID": {
          "title": "Request For Quotation. UUID. Identifier",
          "description": "A universally unique identifier for an instance of this document.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/UUID"
          },
        "IssueDate": {
          "title": "Request For Quotation. Issue Date. Date",
          "description": "The date, assigned by the sender, on which this document was issued.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/IssueDate"
          },
        "IssueTime": {
          "title": "Request For Quotation. Issue Time. Time",
          "description": "The time, assigned by the sender, at which this document was issued.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/IssueTime"
          },
        "SubmissionDueDate": {
          "title": "Request For Quotation. Submission Due Date. Date",
          "description": "The due date for submission of the Quotation.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/SubmissionDueDate"
          },
        "Note": {
          "title": "Request For Quotation. Note. Text",
          "description": "Free-form text pertinent to this document, conveying information that is not contained explicitly in other structures.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/Note"
            },
          "minItems": 1,
          "type": "array"
          },
        "PricingCurrencyCode": {
          "title": "Request For Quotation. Pricing_ Currency Code. Code",
          "description": "The currency that the Seller should use to price the Quotation.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/PricingCurrencyCode"
          },
        "LineCountNumeric": {
          "title": "Request For Quotation. Line Count. Numeric",
          "description": "The number of Request For Quotation Lines in this document.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/LineCountNumeric"
          },
        "RequestedValidityPeriod": {
          "title": "Request For Quotation. Requested Validity_ Period. Period",
          "description": "The validity period requested for this Quotation.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/RequestedValidityPeriod"
          },
        "CatalogueDocumentReference": {
          "title": "Request For Quotation. Catalogue_ Document Reference. Document Reference",
          "description": "The Catalogue on which this Request for Quotation is based.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/CatalogueDocumentReference"
          },
        "AdditionalDocumentReference": {
          "title": "Request For Quotation. Additional_ Document Reference. Document Reference",
          "description": "A reference to an additional document associated with this document.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/AdditionalDocumentReference"
            },
          "minItems": 1,
          "type": "array"
          },
        "Signature": {
          "title": "Request For Quotation. Signature",
          "description": "A signature applied to this document.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/Signature"
            },
          "minItems": 1,
          "type": "array"
          },
        "OriginatorCustomerParty": {
          "title": "Request For Quotation. Originator_ Customer Party. Customer Party",
          "description": "The originator.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/OriginatorCustomerParty"
          },
        "SellerSupplierParty": {
          "title": "Request For Quotation. Seller_ Supplier Party. Supplier Party",
          "description": "The seller.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/SellerSupplierParty"
          },
        "BuyerCustomerParty": {
          "title": "Request For Quotation. Buyer_ Customer Party. Customer Party",
          "description": "The buyer.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/BuyerCustomerParty"
          },
        "Delivery": {
          "title": "Request For Quotation. Delivery",
          "description": "A delivery associated with this document.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/Delivery"
            },
          "minItems": 1,
          "type": "array"
          },
        "DeliveryTerms": {
          "title": "Request For Quotation. Delivery Terms",
          "description": "A set of delivery terms associated with this document.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/DeliveryTerms"
            },
          "minItems": 1,
          "type": "array"
          },
        "DestinationCountry": {
          "title": "Request For Quotation. Destination_ Country. Country",
          "description": "The country of destination of potential orders (for customs purposes).",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/DestinationCountry"
          },
        "Contract": {
          "title": "Request For Quotation. Contract",
          "description": "A contract associated with this Request for Quotation..",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/Contract"
            },
          "minItems": 1,
          "type": "array"
          },
        "RequestForQuotationLine": {
          "title": "Request For Quotation. Request For Quotation Line",
          "description": "A line specifying a kind of item of sale.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/RequestForQuotationLine"
            },
          "minItems": 1,
          "type": "array"
          }
        },
      "additionalProperties": false,
      "type": "object"
      }
    }
  }

=== metasfresh/metasfresh/misc/services/camel/de-metas-camel-externalsystems/com-adekia-exchange/com.adekia.exchange-model/model/UBL-2.3-JSON-v1.0-cn01/json-model/UBL-RequestForQuotation-2.1-Example.json
{"_D":"urn:oasis:names:specification:ubl:schema:xsd:RequestForQuotation-2",
 "_A":"urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2",
 "_B":"urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2",
 "RequestForQuotation":{
 "UBLVersionID":{"_":"2.1"},
 "CustomizationID":{"_":"OIOUBL-2.1"},
 "ProfileID":{"_":"Procurement-QuoSim-1.0",
  "schemeAgencyID":"320",
  "schemeID":"urn:oioubl:id:profileid-1.2"},
 "ID":{"_":"G867B"},
 "CopyIndicator":{"_":false},
 "UUID":{"_":"93T5G3G5-HYA3-7267-BVG3-GS46SW44WG53"},
 "IssueDate":{"_":"2008-04-19"},
 "IssueTime":{"_":"11:32:26.0Z"},
 "SubmissionDueDate":{"_":"2008-04-24"},
 "Note":[{"_":"Bestilling af computere"}],
 "PricingCurrencyCode":{"_":"DKK"},
 "OriginatorCustomerParty":{
  "Party":{
   "EndpointID":{"_":"5798000416604",
    "schemeAgencyID":"9",
    "schemeID":"GLN"},
   "PartyIdentification":[{
    "ID":{"_":"5798000416604",
     "schemeAgencyID":"9",
     "schemeID":"GLN"}
   }],
   "PartyName":[{
    "Name":{"_":"Gentofte Kommune"}
   }],
   "PostalAddress":{
    "AddressFormatCode":{"_":"StructuredDK",
     "listAgencyID":"320",
     "listID":"urn:oioubl:codelist:addressformatcode-1.1"},
    "StreetName":{"_":"Bernstorffsvej"},
    "BuildingNumber":{"_":"161"},
    "CityName":{"_":"Charlottenlund"},
    "PostalZone":{"_":"2920"},
    "Country":{
     "IdentificationCode":{"_":"DK"}
    }
   },
   "PartyTaxScheme":[{
    "CompanyID":{"_":"DK12345678",
     "schemeID":"DK:SE"},
    "TaxScheme":{
     "ID":{"_":"63",
      "schemeAgencyID":"320",
      "schemeID":"urn:oioubl:id:taxschemeid-1.1"},
     "Name":{"_":"Moms"}
    }
   }],
   "PartyLegalEntity":[{
    "RegistrationName":{"_":"Gentofte Kommune"},
    "CompanyID":{"_":"DK12345678",
     "schemeID":"DK:CVR"}
   }],
   "Contact":{
    "ID":{"_":"12345678"},
    "Name":{"_":"Sille Schyberg"}
   }
  }
 },
 "SellerSupplierParty":{
  "CustomerAssignedAccountID":{"_":"LEV00123"},
  "Party":{
   "EndpointID":{"_":"DK18296799",
    "schemeID":"DK:CVR"},
   "PartyIdentification":[{
    "ID":{"_":"DK18296799",
     "schemeID":"DK:CVR"}
   }],
   "PartyName":[{
    "Name":{"_":"Delcomputer A/S"}
   }],
   "PostalAddress":{
    "AddressFormatCode":{"_":"StructuredDK",
     "listAgencyID":"320",
     "listID":"urn:oioubl:codelist:addressformatcode-1.1"},
    "StreetName":{"_":"Arne Jacobsens Allé"},
    "BuildingNumber":{"_":"15"},
    "CityName":{"_":"København S"},
    "PostalZone":{"_":"2300"},
    "Country":{
     "IdentificationCode":{"_":"DK"}
    }
   },
   "PartyTaxScheme":[{
    "CompanyID":{"_":"DK18296799",
     "schemeID":"DK:SE"},
    "TaxScheme":{
     "ID":{"_":"63",
      "schemeAgencyID":"320",
      "schemeID":"urn:oioubl:id:taxschemeid-1.1"},
     "Name":{"_":"Moms"}
    }
   }],
   "PartyLegalEntity":[{
    "RegistrationName":{"_":"Delcomputer A/S"},
    "CompanyID":{"_":"DK18296799",
     "schemeID":"DK:CVR"}
   }]
  }
 },
 "Delivery":[{
  "DeliveryAddress":{
   "AddressFormatCode":{"_":"StructuredDK",
    "listAgencyID":"320",
    "listID":"urn:oioubl:codelist:addressformatcode-1.1"},
   "StreetName":{"_":"Bernstorffsvej"},
   "BuildingNumber":{"_":"161"},
   "CityName":{"_":"Charlottenlund"},
   "PostalZone":{"_":"2920"},
   "AddressLine":[{
    "Line":{"_":"1. sal"}
   },{
    "Line":{"_":"IT-afdelingen"}
   }],
   "Country":{
    "IdentificationCode":{"_":"DK"}
   }
  },
  "RequestedDeliveryPeriod":{
   "StartDate":{"_":"2008-05-06"},
   "StartTime":{"_":"09:30:47.0Z"},
   "EndDate":{"_":"2008-05-10"},
   "EndTime":{"_":"09:30:47.0Z"}
  }
 }],
 "DeliveryTerms":[{
  "SpecialTerms":[{"_":"1% reduktion i kontraktsummen pr. dags forsinkelse jf. SKI kontrakt"}]
 }],
 "Contract":[{
  "ContractDocumentReference":[{
   "ID":{"_":"SKI123456"},
   "IssueDate":{"_":"2006-01-01"}
  }]
 }],
 "RequestForQuotationLine":[{
  "ID":{"_":"1"},
  "Note":[{"_":"Computer"}],
  "LineItem":{
   "ID":{"_":"DELL1052665"},
   "Quantity":{"_":35,
    "unitCode":"NIU"},
   "Item":{
    "Description":[{"_":"Stationær computer"}],
    "Name":{"_":"Dell PrecisionTM  T3400"}
   }
  }
 },{
  "ID":{"_":"2"},
  "Note":[{"_":"Skærm"}],
  "LineItem":{
   "ID":{"_":"DELL2363463"},
   "Quantity":{"_":35,
    "unitCode":"NIU"},
   "Item":{
    "Description":[{"_":"Fladskærm"}],
    "Name":{"_":"FP/BL 1908WFP"}
   }
  }
 },{
  "ID":{"_":"3"},
  "Note":[{"_":"Mus"}],
  "LineItem":{
   "ID":{"_":"DELL2367452"},
   "Quantity":{"_":35,
    "unitCode":"NIU"},
   "Item":{
    "Description":[{"_":"Mus"}],
    "Name":{"_":"Dell Quietkey USB-tastatur, sort - Dansk (QWERTY)"}
   }
  }
 },{
  "ID":{"_":"4"},
  "Note":[{"_":"Tastatur"}],
  "LineItem":{
   "ID":{"_":"DELL8436783"},
   "Quantity":{"_":35,
    "unitCode":"NIU"},
   "Item":{
    "Description":[{"_":"Tastatur"}],
    "Name":{"_":"Dell Quietkey USB-tastatur, sort - Dansk (QWERTY)"}
   }
  }
 }]
}}
