=== metasfresh/metasfresh/misc/services/camel/de-metas-camel-externalsystems/com-adekia-exchange/com.adekia.exchange-model/model/UBL-2.3-JSON-v1.0-cn01/json-schema-model/maindoc/UBL-GoodsItemItinerary-2.3.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "json-schema-model/maindoc/UBL-GoodsItemItinerary-2.3.json",
  "description": "\n  Library:           OASIS Universal Business Language (UBL) 2.3 OS\n                     http://docs.oasis-open.org/ubl/os-UBL-2.3/\n  Release Date:      15 June 2021\n  Module:            json-schema-model/maindoc/UBL-GoodsItemItinerary-2.3.json\n  Generated on:      2021-12-15 21:56z\n  Copyright (c) OASIS Open 2021. All Rights Reserved.\n\n\n  OASIS takes no position regarding the validity or scope of any \n  intellectual property or other rights that might be claimed to pertain \n  to the implementation or use of the technology described in this \n  document or the extent to which any license under such rights \n  might or might not be available; neither does it represent that it has \n  made any effort to identify any such rights. Information on OASIS's \n  procedures with respect to rights in OASIS specifications can be \n  found at the OASIS website. Copies of claims of rights made \n  available for publication and any assurances of licenses to be made \n  available, or the result of an attempt made to obtain a general \n  license or permission for the use of such proprietary rights by \n  implementors or users of this specification, can be obtained from \n  the OASIS Executive Director.\n\n  OASIS invites any interested party to bring to its attention any \n  copyrights, patents or patent applications, or other proprietary \n  rights which may cover technology that may be required to \n  implement this specification. Please address the information to the \n  OASIS Executive Director.\n  \n  This document and translations of it may be copied and furnished to \n  others, and derivative works that comment on or otherwise explain \n  it or assist in its implementation may be prepared, copied, \n  published and distributed, in whole or in part, without restriction of \n  any kind, provided that the above copyright notice and this \n  paragraph are included on all such copies and derivative works. \n  However, this document itself may not be modified in any way, \n  such as by removing the copyright notice or references to OASIS, \n  except as needed for the purpose of developing OASIS \n  specifications, in which case the procedures for copyrights defined \n  in the OASIS Intellectual Property Rights document must be \n  followed, or as required to translate it into languages other than \n  English. \n\n  The limited permissions granted above are perpetual and will not be \n  revoked by OASIS or its successors or assigns. \n\n  This document and the information contained herein is provided on \n  an \"AS IS\" basis and OASIS DISCLAIMS ALL WARRANTIES, \n  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO ANY \n  WARRANTY THAT THE USE OF THE INFORMATION HEREIN \n  WILL NOT INFRINGE ANY RIGHTS OR ANY IMPLIED \n  WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A \n  PARTICULAR PURPOSE.    \n",
  "required": [
    "GoodsItemItinerary"
    ],
  "properties": {
    "_D": {
      "description": "Document ABIE XML namespace string",
      "type": "string"
      },
    "_A": {
      "description": "Library ABIE XML namespace string (for ASBIEs)",
      "type": "string"
      },
    "_B": {
      "description": "BBIE XML namespace string",
      "type": "string"
      },
    "_E": {
      "description": "Extension scaffolding XML namespace string",
      "type": "string"
      },
    "GoodsItemItinerary": {
      "description": "A document providing details relating to a transport service, such as transport movement, identification of equipment and goods, subcontracted service providers, etc.",
      "$ref": "#/definitions/GoodsItemItinerary"
      }
    },
  "additionalProperties": false,
  "type": "object",
  "definitions": {
    "GoodsItemItinerary": {
      "title": "Goods Item Itinerary. Details",
      "description": "A document providing details relating to a transport service, such as transport movement, identification of equipment and goods, subcontracted service providers, etc.",
      "required": [
        "ID",
        "IssueDate",
        "IssueTime",
        "VersionID",
        "TransportExecutionPlanReferenceID",
        "TransportationSegment"
        ],
      "properties": {

        "UBLExtensions": {
          "title": "UBLExtensions",
          "description": "An optional set of extensions to the committee model",
          "items": { 
            "$ref": "../common/UBL-CommonExtensionComponents-2.3.json#/definitions/UBLExtensions" },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },

        "UBLVersionID": {
          "title": "Goods Item Itinerary. UBL Version Identifier. Identifier",
          "description": "Identifies the earliest version of the UBL 2 schema for this document type that defines all of the elements that might be encountered in the current instance.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/UBLVersionID"
          },
        "CustomizationID": {
          "title": "Goods Item Itinerary. Customization Identifier. Identifier",
          "description": "Identifies a user-defined customization of UBL for a specific use.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/CustomizationID"
          },
        "ProfileID": {
          "title": "Goods Item Itinerary. Profile Identifier. Identifier",
          "description": "Identifies a user-defined profile of the customization of UBL being used.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ProfileID"
          },
        "ProfileExecutionID": {
          "title": "Goods Item Itinerary. Profile Execution Identifier. Identifier",
          "description": "Identifies an instance of executing a profile, to associate all transactions in a collaboration.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ProfileExecutionID"
          },
        "ID": {
          "title": "Goods Item Itinerary. Identifier",
          "description": "An identifier for this document, assigned by the sender.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ID"
          },
        "CopyIndicator": {
          "title": "Goods Item Itinerary. Copy_ Indicator. Indicator",
          "description": "Indicates whether this document is a copy (true) or not (false).",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/CopyIndicator"
          },
        "UUID": {
          "title": "Goods Item Itinerary. UUID. Identifier",
          "description": "A universally unique identifier for an instance of this document.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/UUID"
          },
        "IssueDate": {
          "title": "Goods Item Itinerary. Issue Date. Date",
          "description": "The date, assigned by the sender, on which this document was issued.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/IssueDate"
          },
        "IssueTime": {
          "title": "Goods Item Itinerary. Issue Time. Time",
          "description": "The time, assigned by the sender, at which this document was issued.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/IssueTime"
          },
        "Note": {
          "title": "Goods Item Itinerary. Note. Text",
          "description": "Free-form text pertinent to this document, conveying information that is not contained explicitly in other structures.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/Note"
            },
          "minItems": 1,
          "type": "array"
          },
        "VersionID": {
          "title": "Goods Item Itinerary. Version. Identifier",
          "description": "Identifies a version of a Goods Item Itinerary in order to distinguish updates.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/VersionID"
          },
        "TransportExecutionPlanReferenceID": {
          "title": "Goods Item Itinerary. Transport Execution Plan Reference. Identifier",
          "description": "The Transport Execution Plan associated with this Goods Item Itinerary.",
          "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/TransportExecutionPlanReferenceID"
          },
        "Signature": {
          "title": "Goods Item Itinerary. Signature",
          "description": "A signature applied to this document.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/Signature"
            },
          "minItems": 1,
          "type": "array"
          },
        "SenderParty": {
          "title": "Goods Item Itinerary. Sender_ Party. Party",
          "description": "The sender of this Goods Item Itinerary.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/SenderParty"
          },
        "ReceiverParty": {
          "title": "Goods Item Itinerary. Receiver_ Party. Party",
          "description": "The receiver of this Goods Item Itinerary.",
          "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/ReceiverParty"
          },
        "ReferencedConsignment": {
          "title": "Goods Item Itinerary. Referenced_ Consignment. Consignment",
          "description": "A consignment being transported in the transport service associated with this Goods Item Itinerary.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/ReferencedConsignment"
            },
          "minItems": 1,
          "type": "array"
          },
        "ReferencedTransportEquipment": {
          "title": "Goods Item Itinerary. Referenced_ Transport Equipment. Transport Equipment",
          "description": "Transport equipment being transported in the transport service associated with this Goods Item Itinerary.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/ReferencedTransportEquipment"
            },
          "minItems": 1,
          "type": "array"
          },
        "ReferencedPackage": {
          "title": "Goods Item Itinerary. Referenced_ Package. Package",
          "description": "A package being transported in the transport service associated with this Goods Item Itinerary.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/ReferencedPackage"
            },
          "minItems": 1,
          "type": "array"
          },
        "ReferencedGoodsItem": {
          "title": "Goods Item Itinerary. Referenced_ Goods Item. Goods Item",
          "description": "An item of goods being transported in the transport service associated with this Goods Item Itinerary.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/ReferencedGoodsItem"
            },
          "minItems": 1,
          "type": "array"
          },
        "TransportationSegment": {
          "title": "Goods Item Itinerary. Transportation Segment",
          "description": "A part of a transport service that has its own Transport Execution Plan. A Transportation Segment may cover services other than transport, such as terminal handling, document management, customs procedures, etc.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/TransportationSegment"
            },
          "minItems": 1,
          "type": "array"
          }
        },
      "additionalProperties": false,
      "type": "object"
      }
    }
  }

=== metasfresh/metasfresh/misc/services/camel/de-metas-camel-externalsystems/com-adekia-exchange/com.adekia.exchange-model/model/UBL-2.3-JSON-v1.0-cn01/json-model/UBL-GoodsItemItinerary-2.1-Example.json
{"_D":"urn:oasis:names:specification:ubl:schema:xsd:GoodsItemItinerary-2",
 "_A":"urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2",
 "_B":"urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2",
 "GoodsItemItinerary":{
 "UBLVersionID":{"_":"2.1"},
 "ID":{"_":"1"},
 "IssueDate":{"_":"2011-09-13"},
 "IssueTime":{"_":"10:05:20+01:00"},
 "VersionID":{"_":"1"},
 "TransportExecutionPlanReferenceID":{"_":"TEP_1"},
 "SenderParty":{
  "PartyIdentification":[{
   "ID":{"_":"4058673827641",
    "schemeAgencyName":"GS1",
    "schemeName":"GLN"}
  }],
  "PartyName":[{
   "Name":{"_":"NECOSS"}
  }],
  "Contact":{
   "Name":{"_":"SomeName"},
   "Telephone":{"_":"+49450557000"},
   "ElectronicMail":{"_":"SomeName@necoss.de"}
  }
 },
 "ReceiverParty":{
  "PartyIdentification":[{
   "ID":{"_":"4058673827000",
    "schemeAgencyName":"GS1",
    "schemeName":"GLN"}
  }],
  "PartyName":[{
   "Name":{"_":"Consignor"}
  }],
  "Contact":{
   "Name":{"_":"SomeName"},
   "Telephone":{"_":"+8687878763"},
   "ElectronicMail":{"_":"SomeName@consignor.cn"}
  }
 },
 "ReferencedTransportEquipment":[{
  "ID":{"_":"1"},
  "TransportEquipmentSeal":[{
   "ID":{"_":"1_1"},
   "Condition":{"_":"IN_RIGHT_CONDITION"}
  }],
  "Package":[{
   "Quantity":{"_":10},
   "PackagingTypeCode":{"_":"PX"},
   "GoodsItem":[{
    "Item":[{
     "CommodityClassification":[{
      "CargoTypeCode":{"_":"12"}
     }]
    }]
   }]
  }]
 },{
  "ID":{"_":"2"},
  "TransportEquipmentSeal":[{
   "ID":{"_":"2_1"},
   "Condition":{"_":"IN_RIGHT_CONDITION"}
  }],
  "Package":[{
   "Quantity":{"_":10},
   "PackagingTypeCode":{"_":"PX"},
   "GoodsItem":[{
    "Item":[{
     "CommodityClassification":[{
      "CargoTypeCode":{"_":"12"}
     }]
    }]
   }]
  }]
 }],
 "TransportationSegment":[{
  "SequenceNumeric":{"_":1},
  "TransportExecutionPlanReferenceID":{"_":"TEP_2"},
  "TransportationService":{
   "TransportServiceCode":{"_":"3"},
   "TransportationServiceDescription":[{"_":"Rail transport service from Hamburg to Bremen"}]
  },
  "TransportServiceProviderParty":{
   "PartyIdentification":[{
    "ID":{"_":"4058673827100",
     "schemeAgencyName":"GS1",
     "schemeName":"GLN"}
   }],
   "PartyName":[{
    "Name":{"_":"NTT"}
   }],
   "Contact":{
    "Name":{"_":"SomeName"},
    "Telephone":{"_":"+49450557777"},
    "ElectronicMail":{"_":"SomeName@ntt.de"}
   }
  },
  "ReferencedConsignment":{
   "ID":{"_":"NTT_1"},
   "TransportHandlingUnit":[{
    "ID":{"_":"NTT_THU_1"},
    "TransportEquipment":[{
     "ID":{"_":"NTT_THU_1"},
     "ContainedInTransportEquipment":[{
      "ID":{"_":"NTT_TE_1"},
      "TransportEquipmentTypeCode":{"_":"RR"},
      "TraceID":{"_":"12345678914564"}
     }],
     "Package":[{
      "ID":{"_":"CON_1"},
      "Quantity":{"_":10}
     }]
    }]
   },{
    "ID":{"_":"NTT_THU_2"},
    "TransportEquipment":[{
     "ID":{"_":"CON_2"},
     "ContainedInTransportEquipment":[{
      "ID":{"_":"NTT_TE_2"},
      "TransportEquipmentTypeCode":{"_":"RR"},
      "TraceID":{"_":"12345678914565"}
     }],
     "Package":[{
      "ID":{"_":"CON_2"},
      "Quantity":{"_":10}
     }]
    }]
   }]
  },
  "ShipmentStage":[{
   "ID":{"_":"1"},
   "TransportModeCode":{"_":"2"},
   "TransportMeansTypeCode":{"_":"230"},
   "PlannedDepartureTransportEvent":{
    "Location":{
     "Address":{
      "ID":{"_":"DEHAM",
       "schemeAgencyName":"UN",
       "schemeName":"UN/LOCODE"},
      "StreetName":{"_":"Neuer Wandrahm 4"},
      "CityName":{"_":"Hamburg"},
      "Country":{
       "IdentificationCode":{"_":"DE"}
      }
     }
    },
    "Period":[{
     "StartDate":{"_":"2011-10-03"},
     "StartTime":{"_":"09:30:10+01:00"},
     "EndDate":{"_":"2011-10-03"},
     "EndTime":{"_":"12:30:10+01:00"}
    }]
   },
   "PlannedArrivalTransportEvent":{
    "Location":{
     "LocationTypeCode":{"_":"13"},
     "Address":{
      "ID":{"_":"4568763527610",
       "schemeAgencyName":"GS1",
       "schemeName":"GLN"},
      "StreetName":{"_":"Ludwig-Erhard-Str. 15"},
      "CityName":{"_":"Bremen"},
      "Country":{
       "IdentificationCode":{"_":"DE"}
      }
     }
    },
    "Period":[{
     "StartDate":{"_":"2011-10-03"},
     "StartTime":{"_":"18:30:10+01:00"},
     "EndDate":{"_":"2011-10-03"},
     "EndTime":{"_":"21:30:10+01:00"}
    }]
   }
  }]
 },{
  "SequenceNumeric":{"_":2},
  "TransportExecutionPlanReferenceID":{"_":"TEP_1"},
  "TransportationService":{
   "TransportServiceCode":{"_":"3"},
   "TransportationServiceDescription":[{"_":"Rail transport service from Bremen to Nurnberg"}]
  },
  "TransportServiceProviderParty":{
   "PartyIdentification":[{
    "ID":{"_":"4058673827641",
     "schemeAgencyName":"GS1",
     "schemeName":"GLN"}
   }],
   "PartyName":[{
    "Name":{"_":"NECOSS"}
   }],
   "Contact":{
    "Name":{"_":"SomeName"},
    "Telephone":{"_":"+49450557000"},
    "ElectronicMail":{"_":"SomeName@necoss.de"}
   }
  },
  "ReferencedConsignment":{
   "ID":{"_":"CON_1"},
   "TransportHandlingUnit":[{
    "ID":{"_":"CON_THU_1"},
    "TransportEquipment":[{
     "ID":{"_":"CON_1"},
     "ContainedInTransportEquipment":[{
      "ID":{"_":"NEC_TE_1"},
      "TransportEquipmentTypeCode":{"_":"RR"},
      "TraceID":{"_":"12345678914542"}
     }],
     "Package":[{
      "ID":{"_":"CON_1"},
      "Quantity":{"_":10}
     }]
    }]
   },{
    "ID":{"_":"CON_THU_2"},
    "TransportEquipment":[{
     "ID":{"_":"CON_2"},
     "ContainedInTransportEquipment":[{
      "ID":{"_":"NEC_TE_2"},
      "TransportEquipmentTypeCode":{"_":"RR"},
      "TraceID":{"_":"12345678914543"}
     }],
     "Package":[{
      "ID":{"_":"CON_2"},
      "Quantity":{"_":10}
     }]
    }]
   }]
  },
  "ShipmentStage":[{
   "ID":{"_":"2"},
   "PlannedDepartureTransportEvent":{
    "Location":{
     "LocationTypeCode":{"_":"13"},
     "Address":{
      "ID":{"_":"4568763527610",
       "schemeAgencyName":"GS1",
       "schemeName":"GLN"},
      "StreetName":{"_":"Ludwig-Erhard-Str. 15"},
      "CityName":{"_":"Bremen"},
      "Country":{
       "IdentificationCode":{"_":"DE"}
      }
     }
    },
    "Period":[{
     "StartDate":{"_":"2011-10-04"},
     "StartTime":{"_":"09:30:10+01:00"},
     "EndDate":{"_":"2011-10-04"},
     "EndTime":{"_":"09:30:10+01:00"}
    }]
   },
   "PlannedArrivalTransportEvent":{
    "Location":{
     "LocationTypeCode":{"_":"13"},
     "Address":{
      "StreetName":{"_":"Sandstr. 38-40"},
      "CityName":{"_":"Nurnberg"},
      "Country":{
       "IdentificationCode":{"_":"DE"}
      }
     }
    },
    "Period":[{
     "StartDate":{"_":"2011-10-04"},
     "StartTime":{"_":"15:30:10+01:00"},
     "EndDate":{"_":"2011-10-04"},
     "EndTime":{"_":"18:30:10+01:00"}
    }]
   }
  }]
 },{
  "SequenceNumeric":{"_":3},
  "TransportExecutionPlanReferenceID":{"_":"TEP_3"},
  "TransportationService":{
   "TransportServiceCode":{"_":"3"},
   "TransportationServiceDescription":[{"_":"Road transport service from Hamburg to Bremen"}]
  },
  "TransportServiceProviderParty":{
   "PartyIdentification":[{
    "ID":{"_":"4058673827112",
     "schemeAgencyName":"GS1",
     "schemeName":"GLN"}
   }],
   "PartyName":[{
    "Name":{"_":"EXT-HAL"}
   }],
   "Contact":{
    "Name":{"_":"SomeName"},
    "Telephone":{"_":"+49450557234"},
    "ElectronicMail":{"_":"SomeName@ext-hal.de"}
   }
  },
  "ReferencedConsignment":{
   "ID":{"_":"EXT_1"},
   "TransportHandlingUnit":[{
    "ID":{"_":"EXT_THU_1"},
    "TransportEquipment":[{
     "ID":{"_":"CON_1"},
     "ContainedInTransportEquipment":[{
      "ID":{"_":"EXT_TE_1"},
      "TransportEquipmentTypeCode":{"_":"TE"},
      "TraceID":{"_":"12345678914111"}
     }],
     "Package":[{
      "ID":{"_":"CON_1"},
      "Quantity":{"_":10}
     }]
    }],
    "TransportMeans":[{
     "RoadTransport":{
      "LicensePlateID":{"_":"WFN667"}
     }
    }]
   },{
    "ID":{"_":"EXT_THU_2"},
    "TransportEquipment":[{
     "ID":{"_":"CON_2"},
     "ContainedInTransportEquipment":[{
      "ID":{"_":"EXT_TE_2"},
      "TransportEquipmentTypeCode":{"_":"TE"},
      "TraceID":{"_":"12345678914112"}
     }],
     "Package":[{
      "ID":{"_":"CON_2"},
      "Quantity":{"_":10}
     }]
    }],
    "TransportMeans":[{
     "RoadTransport":{
      "LicensePlateID":{"_":"WFN667"}
     }
    }]
   }]
  },
  "ShipmentStage":[{
   "ID":{"_":"3"},
   "PlannedDepartureTransportEvent":{
    "Location":{
     "LocationTypeCode":{"_":"13"},
     "Address":{
      "StreetName":{"_":"Sandstr. 38-40"},
      "CityName":{"_":"Nurnberg"},
      "Country":{
       "IdentificationCode":{"_":"DE"}
      }
     }
    },
    "Period":[{
     "StartDate":{"_":"2011-10-06"},
     "StartTime":{"_":"09:30:10+01:00"},
     "EndDate":{"_":"2011-10-06"},
     "EndTime":{"_":"12:30:10+01:00"}
    }]
   },
   "PlannedArrivalTransportEvent":{
    "Location":{
     "Address":{
      "StreetName":{"_":"Grosse strasse 34"},
      "CityName":{"_":"Nurnberg"},
      "Country":{
       "IdentificationCode":{"_":"DE"}
      }
     }
    },
    "Period":[{
     "StartDate":{"_":"2011-10-06"},
     "StartTime":{"_":"12:30:10+01:00"},
     "EndDate":{"_":"2011-10-06"},
     "EndTime":{"_":"15:30:10+01:00"}
    }]
   }
  }]
 }]
}}
