=== metasfresh/metasfresh/misc/services/camel/de-metas-camel-externalsystems/com-adekia-exchange/com.adekia.exchange-model/model/UBL-2.3-JSON-v1.0-cn01/json-schema-legacy/maindoc/UBL-CommonTransportationReport-2.3.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "json-schema-legacy/maindoc/UBL-CommonTransportationReport-2.3.json",
  "description": "\n  Library:           OASIS Universal Business Language (UBL) 2.3 OS\n                     http://docs.oasis-open.org/ubl/os-UBL-2.3/\n  Release Date:      15 June 2021\n  Module:            json-schema-legacy/maindoc/UBL-CommonTransportationReport-2.3.json\n  Generated on:      2021-12-15 21:56z\n  Copyright (c) OASIS Open 2021. All Rights Reserved.\n\n\n  OASIS takes no position regarding the validity or scope of any \n  intellectual property or other rights that might be claimed to pertain \n  to the implementation or use of the technology described in this \n  document or the extent to which any license under such rights \n  might or might not be available; neither does it represent that it has \n  made any effort to identify any such rights. Information on OASIS's \n  procedures with respect to rights in OASIS specifications can be \n  found at the OASIS website. Copies of claims of rights made \n  available for publication and any assurances of licenses to be made \n  available, or the result of an attempt made to obtain a general \n  license or permission for the use of such proprietary rights by \n  implementors or users of this specification, can be obtained from \n  the OASIS Executive Director.\n\n  OASIS invites any interested party to bring to its attention any \n  copyrights, patents or patent applications, or other proprietary \n  rights which may cover technology that may be required to \n  implement this specification. Please address the information to the \n  OASIS Executive Director.\n  \n  This document and translations of it may be copied and furnished to \n  others, and derivative works that comment on or otherwise explain \n  it or assist in its implementation may be prepared, copied, \n  published and distributed, in whole or in part, without restriction of \n  any kind, provided that the above copyright notice and this \n  paragraph are included on all such copies and derivative works. \n  However, this document itself may not be modified in any way, \n  such as by removing the copyright notice or references to OASIS, \n  except as needed for the purpose of developing OASIS \n  specifications, in which case the procedures for copyrights defined \n  in the OASIS Intellectual Property Rights document must be \n  followed, or as required to translate it into languages other than \n  English. \n\n  The limited permissions granted above are perpetual and will not be \n  revoked by OASIS or its successors or assigns. \n\n  This document and the information contained herein is provided on \n  an \"AS IS\" basis and OASIS DISCLAIMS ALL WARRANTIES, \n  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO ANY \n  WARRANTY THAT THE USE OF THE INFORMATION HEREIN \n  WILL NOT INFRINGE ANY RIGHTS OR ANY IMPLIED \n  WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A \n  PARTICULAR PURPOSE.    \n",
  "required": [
    "CommonTransportationReport"
    ],
  "properties": {
    "_D": {
      "description": "Document ABIE XML namespace string",
      "type": "string"
      },
    "_A": {
      "description": "Library ABIE XML namespace string (for ASBIEs)",
      "type": "string"
      },
    "_B": {
      "description": "BBIE XML namespace string",
      "type": "string"
      },
    "_E": {
      "description": "Extension scaffolding XML namespace string",
      "type": "string"
      },
    "CommonTransportationReport": {
      "description": "A common document used for reporting transport related issues to authorities or regulators.",
      "items": {
        "$ref": "#/definitions/CommonTransportationReport"
        },
      "maxItems": 1,
      "minItems": 1,
      "type": "array"
      }
    },
  "additionalProperties": false,
  "type": "object",
  "definitions": {
    "CommonTransportationReport": {
      "title": "Common Transportation Report. Details",
      "description": "A common document used for reporting transport related issues to authorities or regulators.",
      "required": [
        "ID",
        "IssueDate",
        "ReporterParty",
        "SenderParty",
        "ReceiverParty"
        ],
      "properties": {

        "UBLExtensions": {
          "title": "UBLExtensions",
          "description": "An optional set of extensions to the committee model",
          "items": { 
            "$ref": "../common/UBL-CommonExtensionComponents-2.3.json#/definitions/UBLExtensions" },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },

        "UBLVersionID": {
          "title": "Common Transportation Report. UBL Version Identifier. Identifier",
          "description": "Identifies the earliest version of the UBL 2 schema for this document type that defines all of the elements that might be encountered in the current instance.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/UBLVersionID"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "CustomizationID": {
          "title": "Common Transportation Report. Customization Identifier. Identifier",
          "description": "Identifies a user-defined customization of UBL for a specific use.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/CustomizationID"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "ProfileID": {
          "title": "Common Transportation Report. Profile Identifier. Identifier",
          "description": "Identifies a user-defined profile of the customization of UBL being used.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ProfileID"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "ProfileExecutionID": {
          "title": "Common Transportation Report. Profile Execution Identifier. Identifier",
          "description": "Identifies an instance of executing a profile, to associate all transactions in a collaboration.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ProfileExecutionID"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "ID": {
          "title": "Common Transportation Report. Identifier",
          "description": "An identifier for this document.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ID"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "UUID": {
          "title": "Common Transportation Report. UUID. Identifier",
          "description": "A universally unique identifier for an instance of this document.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/UUID"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "IssueDate": {
          "title": "Common Transportation Report. Issue Date. Date",
          "description": "The date, assigned by the sender, on which this document was issued.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/IssueDate"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "IssueTime": {
          "title": "Common Transportation Report. Issue Time. Time",
          "description": "The time, assigned by the sender, at which this document was issued.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/IssueTime"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "DocumentStatusCode": {
          "title": "Common Transportation Report. Document Status Code. Code",
          "description": "A code signifying the status of this Common Transportation Report with respect to its original state.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/DocumentStatusCode"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "ReportTypeCode": {
          "title": "Common Transportation Report. Report Type Code. Code",
          "description": "A code signifying the type of report being provided",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ReportTypeCode"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "ReportType": {
          "title": "Common Transportation Report. Report Type. Text",
          "description": "A text that identifies the type of report to business users.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ReportType"
            },
          "minItems": 1,
          "type": "array"
          },
        "Description": {
          "title": "Common Transportation Report. Description. Text",
          "description": "Textual description of this document instance.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/Description"
            },
          "minItems": 1,
          "type": "array"
          },
        "Note": {
          "title": "Common Transportation Report. Note. Text",
          "description": "Free-form text pertinent to this document, conveying information that is not contained explicitly in other structures.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/Note"
            },
          "minItems": 1,
          "type": "array"
          },
        "VersionID": {
          "title": "Common Transportation Report. Version. Identifier",
          "description": "Identifies a version of a common transportation report in order to distinguish updates.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/VersionID"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "ReporterParty": {
          "title": "Common Transportation Report. Reporter_ Party. Party",
          "description": "The party providing this common transportation report.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/ReporterParty"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "AuthorityParty": {
          "title": "Common Transportation Report. Authority_ Party. Party",
          "description": "The authority or regulator receiving this common transportation report.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/AuthorityParty"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "SenderParty": {
          "title": "Common Transportation Report. Sender_ Party. Party",
          "description": "The party sending this report.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/SenderParty"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "ReceiverParty": {
          "title": "Common Transportation Report. Receiver_ Party. Party",
          "description": "The party receiving this report.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/ReceiverParty"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "ReportingLocation": {
          "title": "Common Transportation Report. Reporting_ Location. Location",
          "description": "A location to which this common transportation report applies.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/ReportingLocation"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "Shipment": {
          "title": "Common Transportation Report. Shipment",
          "description": "A shipment to which this common transportation report applies.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/Shipment"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "TransportMeans": {
          "title": "Common Transportation Report. Transport Means",
          "description": "A means of transport used in relation to this common transportation report.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/TransportMeans"
            },
          "minItems": 1,
          "type": "array"
          },
        "DocumentReference": {
          "title": "Common Transportation Report. Document Reference",
          "description": "A reference to a document relevant for or associated with this common transportation report.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/DocumentReference"
            },
          "minItems": 1,
          "type": "array"
          },
        "Signature": {
          "title": "Common Transportation Report. Signature",
          "description": "A signature applied to this document.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/Signature"
            },
          "minItems": 1,
          "type": "array"
          }
        },
      "additionalProperties": false,
      "type": "object"
      }
    }
  }

=== metasfresh/metasfresh/misc/services/camel/de-metas-camel-externalsystems/com-adekia-exchange/com.adekia.exchange-model/model/UBL-2.3-JSON-v1.0-cn01/json-legacy/UBL-CommonTransportationReport-2.3-Example.json
{"_D":"urn:oasis:names:specification:ubl:schema:xsd:CommonTransportationReport-2",
 "_A":"urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2",
 "_B":"urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2",
 "CommonTransportationReport":[{
 "UBLVersionID":[{"_":"2.1"}],
 "CustomizationID":[{"_":"Common Framework"}],
 "ProfileID":[{"_":"ENS"}],
 "ID":[{"_":"224087496582335"}],
 "IssueDate":[{"_":"2013-05-08"}],
 "IssueTime":[{"_":"10:15:00+02:00"}],
 "DocumentStatusCode":[{"_":"NotConfirmed"}],
 "VersionID":[{"_":"1"}],
 "ReporterParty":[{
  "PartyIdentification":[{
   "ID":[{"_":"4058673827641",
    "schemeAgencyName":"GS1",
    "schemeName":"GLN"}]
  }],
  "PartyName":[{
   "Name":[{"_":"D2D GmbH"}]
  }],
  "Contact":[{
   "Name":[{"_":"SomeName"}],
   "Telephone":[{"_":"+49450557000"}],
   "ElectronicMail":[{"_":"SomeName@d2d.de"}]
  }]
 }],
 "SenderParty":[{
  "PartyName":[{
   "Name":[{"_":"Declarant Inc"}]
  }],
  "PostalAddress":[{
   "StreetName":[{"_":"Declarant Street"}],
   "CityName":[{"_":"Declarant City"}],
   "PostalZone":[{"_":"Declarant Post Code"}],
   "Country":[{
    "IdentificationCode":[{"_":"DE"}]
   }]
  }],
  "Contact":[{
   "Name":[{"_":"SomeName"}],
   "Telephone":[{"_":"+49450557000"}],
   "ElectronicMail":[{"_":"SomeName@d2d.de"}]
  }]
 }],
 "ReceiverParty":[{
  "PartyIdentification":[{
   "ID":[{"_":"4058675698641",
    "schemeAgencyName":"GS1",
    "schemeName":"GLN"}]
  }],
  "PartyName":[{
   "Name":[{"_":"Lisboa Harbour"}]
  }]
 }],
 "ReportingLocation":[{
  "Address":[{
   "StreetName":[{"_":"Declarant Street"}],
   "CityName":[{"_":"Declarant City"}],
   "PostalZone":[{"_":"Declarant Post Code"}],
   "Country":[{
    "IdentificationCode":[{"_":"DE"}]
   }]
  }]
 }],
 "Shipment":[{
  "Consignment":[{
   "ID":[{"_":"7365566156191234567",
    "schemeAgencyName":"GS1",
    "schemeName":"GINC"}],
   "GrossWeightMeasure":[{"_":600,
    "unitCode":"KGM"}],
   "TotalGoodsItemQuantity":[{"_":1500}],
   "TotalTransportHandlingUnitQuantity":[{"_":2}],
   "PlannedPickupTransportEvent":[{
    "Location":[{
     "ID":[{"_":"MAPTM",
      "schemeAgencyName":"UN",
      "schemeName":"LOCODE"}],
     "Address":[{
      "CityName":[{"_":"Tanger"}],
      "Country":[{
       "IdentificationCode":[{"_":"MA"}]
      }]
     }]
    }]
   }],
   "PlannedDeliveryTransportEvent":[{
    "Location":[{
     "ID":[{"_":"ITGOA",
      "schemeAgencyName":"UN",
      "schemeName":"LOCODE"}],
     "Address":[{
      "Country":[{
       "IdentificationCode":[{"_":"IT"}]
      }]
     }]
    }]
   }],
   "ConsigneeParty":[{
    "PartyName":[{
     "Name":[{"_":"Consignee W"}]
    }],
    "PostalAddress":[{
     "StreetName":[{"_":"Consignee W Street"}],
     "CityName":[{"_":"Munich"}],
     "PostalZone":[{"_":"231"}],
     "Country":[{
      "IdentificationCode":[{"_":"DE"}]
     }]
    }]
   }],
   "ConsignorParty":[{
    "PartyIdentification":[{
     "ID":[{"_":"4058673827000",
      "schemeAgencyName":"GS1",
      "schemeName":"GLN"}]
    }],
    "PartyName":[{
     "Name":[{"_":"Disfruta"}]
    }],
    "Contact":[{
     "Name":[{"_":"SomeName"}],
     "Telephone":[{"_":"+212687878763"}],
     "ElectronicMail":[{"_":"SomeName@disfruta.ma"}]
    }]
   }],
   "OriginalDepartureCountry":[{
    "IdentificationCode":[{"_":"MA"}]
   }],
   "FinalDestinationCountry":[{
    "IdentificationCode":[{"_":"DE"}]
   }],
   "TransitCountry":[{
    "IdentificationCode":[{"_":"IT"}]
   },{
    "IdentificationCode":[{"_":"AT"}]
   }],
   "MainCarriageShipmentStage":[{
    "ShipmentStageTypeCode":[{"_":"1"}],
    "TransportModeCode":[{"_":"1"}],
    "TransportMeans":[{
     "JourneyID":[{"_":"00344"}],
     "RegistrationNationalityID":[{"_":"IT"}],
     "MaritimeTransport":[{
      "VesselID":[{"_":"3852664"}],
      "VesselName":[{"_":"Vessel Name"}]
     }]
    }],
    "EstimatedArrivalTransportEvent":[{
     "OccurrenceDate":[{"_":"2013-05-25"}],
     "OccurrenceTime":[{"_":"18:00:00+01:00"}],
     "Location":[{
      "ID":[{"_":"ITGOA",
       "schemeName":"UNLOCODE"}],
      "LocationTypeCode":[{"_":"24"}],
      "Address":[{
       "Country":[{
        "IdentificationCode":[{"_":"IT"}]
       }]
      }]
     }]
    }]
   }],
   "TransportHandlingUnit":[{
    "ID":[{"_":"CON_THU_1"}],
    "TransportHandlingUnitTypeCode":[{"_":"4"}],
    "HazardousRiskIndicator":[{"_":false}],
    "ShippingMarks":[{"_":"Agricultural products"}],
    "TransportEquipment":[{
     "ID":[{"_":"BFCU4040001",
      "schemeName":"bic"}],
     "TransportEquipmentTypeCode":[{"_":"CN"}],
     "FullnessIndicationCode":[{"_":"1"}],
     "ReturnabilityIndicator":[{"_":true}],
     "RefrigeratedIndicator":[{"_":true}],
     "Description":[{"_":"Should have a temperature between 2-4 degrees celcius"}],
     "GrossWeightMeasure":[{"_":25000,
      "unitCode":"KGM"}],
     "GrossVolumeMeasure":[{"_":39,
      "unitCode":"MTQ"}],
     "PowerIndicator":[{"_":true}],
     "MeasurementDimension":[{
      "AttributeID":[{"_":"Length"}],
      "Measure":[{"_":6.1,
       "unitCode":"MTR"}]
     },{
      "AttributeID":[{"_":"Height"}],
      "Measure":[{"_":2.6,
       "unitCode":"MTR"}]
     },{
      "AttributeID":[{"_":"Width"}],
      "Measure":[{"_":2.44,
       "unitCode":"MTR"}]
     }],
     "GoodsItem":[{
      "Item":[{
       "CommodityClassification":[{
        "CargoTypeCode":[{"_":"14"}],
        "CommodityCode":[{"_":"8"}]
       }]
      }]
     }]
    }]
   },{
    "ID":[{"_":"CON_THU_2"}],
    "TransportHandlingUnitTypeCode":[{"_":"4"}],
    "HazardousRiskIndicator":[{"_":false}],
    "ShippingMarks":[{"_":"Agricultural products"}],
    "TransportEquipment":[{
     "ID":[{"_":"BFCU4040002",
      "schemeName":"bic"}],
     "TransportEquipmentTypeCode":[{"_":"CN"}],
     "FullnessIndicationCode":[{"_":"1"}],
     "ReturnabilityIndicator":[{"_":true}],
     "RefrigeratedIndicator":[{"_":true}],
     "Description":[{"_":"Should have a temperature between 2-4 degrees celcius"}],
     "GrossWeightMeasure":[{"_":25000,
      "unitCode":"KGM"}],
     "GrossVolumeMeasure":[{"_":39,
      "unitCode":"MTQ"}],
     "PowerIndicator":[{"_":true}],
     "MeasurementDimension":[{
      "AttributeID":[{"_":"Length"}],
      "Measure":[{"_":6.1,
       "unitCode":"MTR"}]
     },{
      "AttributeID":[{"_":"Height"}],
      "Measure":[{"_":2.6,
       "unitCode":"MTR"}]
     },{
      "AttributeID":[{"_":"Width"}],
      "Measure":[{"_":2.44,
       "unitCode":"MTR"}]
     }],
     "GoodsItem":[{
      "Item":[{
       "CommodityClassification":[{
        "CargoTypeCode":[{"_":"14"}],
        "CommodityCode":[{"_":"8"}]
       }]
      }]
     }]
    }]
   }],
   "FirstArrivalPortLocation":[{
    "ID":[{"_":"ITGOA",
     "schemeName":"UNLOCODE"}],
    "LocationTypeCode":[{"_":"41"}],
    "Address":[{
     "Country":[{
      "IdentificationCode":[{"_":"IT"}]
     }]
    }]
   }],
   "OfficeOfEntryLocation":[{
    "ID":[{"_":"DE000396"}],
    "LocationTypeCode":[{"_":"41"}],
    "Address":[{
     "Country":[{
      "IdentificationCode":[{"_":"DE"}]
     }]
    }]
   }]
  }]
 }],
 "DocumentReference":[{
  "ID":[{"_":"224087496582335"}],
  "DocumentTypeCode":[{"_":"704"}]
 }]
}]}
