=== metasfresh/metasfresh/misc/services/camel/de-metas-camel-externalsystems/com-adekia-exchange/com.adekia.exchange-model/model/UBL-2.3-JSON-v1.0-cn01/json-schema-legacy/maindoc/UBL-Statement-2.3.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "json-schema-legacy/maindoc/UBL-Statement-2.3.json",
  "description": "\n  Library:           OASIS Universal Business Language (UBL) 2.3 OS\n                     http://docs.oasis-open.org/ubl/os-UBL-2.3/\n  Release Date:      15 June 2021\n  Module:            json-schema-legacy/maindoc/UBL-Statement-2.3.json\n  Generated on:      2021-12-15 21:56z\n  Copyright (c) OASIS Open 2021. All Rights Reserved.\n\n\n  OASIS takes no position regarding the validity or scope of any \n  intellectual property or other rights that might be claimed to pertain \n  to the implementation or use of the technology described in this \n  document or the extent to which any license under such rights \n  might or might not be available; neither does it represent that it has \n  made any effort to identify any such rights. Information on OASIS's \n  procedures with respect to rights in OASIS specifications can be \n  found at the OASIS website. Copies of claims of rights made \n  available for publication and any assurances of licenses to be made \n  available, or the result of an attempt made to obtain a general \n  license or permission for the use of such proprietary rights by \n  implementors or users of this specification, can be obtained from \n  the OASIS Executive Director.\n\n  OASIS invites any interested party to bring to its attention any \n  copyrights, patents or patent applications, or other proprietary \n  rights which may cover technology that may be required to \n  implement this specification. Please address the information to the \n  OASIS Executive Director.\n  \n  This document and translations of it may be copied and furnished to \n  others, and derivative works that comment on or otherwise explain \n  it or assist in its implementation may be prepared, copied, \n  published and distributed, in whole or in part, without restriction of \n  any kind, provided that the above copyright notice and this \n  paragraph are included on all such copies and derivative works. \n  However, this document itself may not be modified in any way, \n  such as by removing the copyright notice or references to OASIS, \n  except as needed for the purpose of developing OASIS \n  specifications, in which case the procedures for copyrights defined \n  in the OASIS Intellectual Property Rights document must be \n  followed, or as required to translate it into languages other than \n  English. \n\n  The limited permissions granted above are perpetual and will not be \n  revoked by OASIS or its successors or assigns. \n\n  This document and the information contained herein is provided on \n  an \"AS IS\" basis and OASIS DISCLAIMS ALL WARRANTIES, \n  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO ANY \n  WARRANTY THAT THE USE OF THE INFORMATION HEREIN \n  WILL NOT INFRINGE ANY RIGHTS OR ANY IMPLIED \n  WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A \n  PARTICULAR PURPOSE.    \n",
  "required": [
    "Statement"
    ],
  "properties": {
    "_D": {
      "description": "Document ABIE XML namespace string",
      "type": "string"
      },
    "_A": {
      "description": "Library ABIE XML namespace string (for ASBIEs)",
      "type": "string"
      },
    "_B": {
      "description": "BBIE XML namespace string",
      "type": "string"
      },
    "_E": {
      "description": "Extension scaffolding XML namespace string",
      "type": "string"
      },
    "Statement": {
      "description": "A document used to report the status of orders, billing, and payment. This document is a statement of account, not a summary invoice.",
      "items": {
        "$ref": "#/definitions/Statement"
        },
      "maxItems": 1,
      "minItems": 1,
      "type": "array"
      }
    },
  "additionalProperties": false,
  "type": "object",
  "definitions": {
    "Statement": {
      "title": "Statement. Details",
      "description": "A document used to report the status of orders, billing, and payment. This document is a statement of account, not a summary invoice.",
      "required": [
        "ID",
        "IssueDate",
        "DocumentCurrencyCode",
        "AccountingSupplierParty",
        "AccountingCustomerParty",
        "StatementLine"
        ],
      "properties": {

        "UBLExtensions": {
          "title": "UBLExtensions",
          "description": "An optional set of extensions to the committee model",
          "items": { 
            "$ref": "../common/UBL-CommonExtensionComponents-2.3.json#/definitions/UBLExtensions" },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },

        "UBLVersionID": {
          "title": "Statement. UBL Version Identifier. Identifier",
          "description": "Identifies the earliest version of the UBL 2 schema for this document type that defines all of the elements that might be encountered in the current instance.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/UBLVersionID"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "CustomizationID": {
          "title": "Statement. Customization Identifier. Identifier",
          "description": "Identifies a user-defined customization of UBL for a specific use.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/CustomizationID"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "ProfileID": {
          "title": "Statement. Profile Identifier. Identifier",
          "description": "Identifies a user-defined profile of the customization of UBL being used.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ProfileID"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "ProfileExecutionID": {
          "title": "Statement. Profile Execution Identifier. Identifier",
          "description": "Identifies an instance of executing a profile, to associate all transactions in a collaboration.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ProfileExecutionID"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "ID": {
          "title": "Statement. Identifier",
          "description": "An identifier for this document, assigned by the sender.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ID"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "CopyIndicator": {
          "title": "Statement. Copy_ Indicator. Indicator",
          "description": "Indicates whether this document is a copy (true) or not (false).",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/CopyIndicator"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "UUID": {
          "title": "Statement. UUID. Identifier",
          "description": "A universally unique identifier for an instance of this document.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/UUID"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "IssueDate": {
          "title": "Statement. Issue Date. Date",
          "description": "The date, assigned by the sender, on which this document was issued.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/IssueDate"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "IssueTime": {
          "title": "Statement. Issue Time. Time",
          "description": "The time, assigned by the sender, at which this document was issued.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/IssueTime"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "Note": {
          "title": "Statement. Note. Text",
          "description": "Free-form text pertinent to this document, conveying information that is not contained explicitly in other structures.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/Note"
            },
          "minItems": 1,
          "type": "array"
          },
        "DocumentCurrencyCode": {
          "title": "Statement. Document_ Currency Code. Code",
          "description": "The default currency for the Statement.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/DocumentCurrencyCode"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "TotalDebitAmount": {
          "title": "Statement. Total_ Debit Amount. Amount",
          "description": "The total of all debit amounts for the Statement.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/TotalDebitAmount"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "TotalCreditAmount": {
          "title": "Statement. Total_ Credit Amount. Amount",
          "description": "The total of all credit amounts for the Statement.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/TotalCreditAmount"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "TotalBalanceAmount": {
          "title": "Statement. Total_ Balance Amount. Amount",
          "description": "The total amount for the Statement.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/TotalBalanceAmount"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "LineCountNumeric": {
          "title": "Statement. Line Count. Numeric",
          "description": "The number of Statement Lines in the Statement.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/LineCountNumeric"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "StatementTypeCode": {
          "title": "Statement. Statement Type Code. Code",
          "description": "A code signifying the type of the Statement.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/StatementTypeCode"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "StatementPeriod": {
          "title": "Statement. Statement_ Period. Period",
          "description": "A period to which the Statement applies.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/StatementPeriod"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "AdditionalDocumentReference": {
          "title": "Statement. Additional_ Document Reference. Document Reference",
          "description": "A reference to an additional document associated with this document.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/AdditionalDocumentReference"
            },
          "minItems": 1,
          "type": "array"
          },
        "Signature": {
          "title": "Statement. Signature",
          "description": "A signature applied to this document.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/Signature"
            },
          "minItems": 1,
          "type": "array"
          },
        "AccountingSupplierParty": {
          "title": "Statement. Accounting_ Supplier Party. Supplier Party",
          "description": "The accounting supplier party.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/AccountingSupplierParty"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "AccountingCustomerParty": {
          "title": "Statement. Accounting_ Customer Party. Customer Party",
          "description": "The accounting customer party.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/AccountingCustomerParty"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "BuyerCustomerParty": {
          "title": "Statement. Buyer_ Customer Party. Customer Party",
          "description": "The buyer.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/BuyerCustomerParty"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "SellerSupplierParty": {
          "title": "Statement. Seller_ Supplier Party. Supplier Party",
          "description": "The seller.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/SellerSupplierParty"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "OriginatorCustomerParty": {
          "title": "Statement. Originator_ Customer Party. Customer Party",
          "description": "The originator.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/OriginatorCustomerParty"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "PayeeParty": {
          "title": "Statement. Payee_ Party. Party",
          "description": "The payee.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/PayeeParty"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "PaymentMeans": {
          "title": "Statement. Payment Means",
          "description": "Expected means of payment.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/PaymentMeans"
            },
          "minItems": 1,
          "type": "array"
          },
        "PaymentTerms": {
          "title": "Statement. Payment Terms",
          "description": "A set of payment terms associated with this document.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/PaymentTerms"
            },
          "minItems": 1,
          "type": "array"
          },
        "AllowanceCharge": {
          "title": "Statement. Allowance Charge",
          "description": "A discount or charge that applies to a price component.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/AllowanceCharge"
            },
          "minItems": 1,
          "type": "array"
          },
        "TaxTotal": {
          "title": "Statement. Tax Total",
          "description": "The total amount of a specific type of tax.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/TaxTotal"
            },
          "minItems": 1,
          "type": "array"
          },
        "StatementLine": {
          "title": "Statement. Statement Line",
          "description": "A Statement Line.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/StatementLine"
            },
          "minItems": 1,
          "type": "array"
          }
        },
      "additionalProperties": false,
      "type": "object"
      }
    }
  }

=== metasfresh/metasfresh/misc/services/camel/de-metas-camel-externalsystems/com-adekia-exchange/com.adekia.exchange-model/model/UBL-2.3-JSON-v1.0-cn01/json-legacy/UBL-Statement-2.0-Example.json
{"_D":"urn:oasis:names:specification:ubl:schema:xsd:Statement-2",
 "_A":"urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2",
 "_B":"urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2",
 "Statement":[{
 "UBLVersionID":[{"_":"2.0"}],
 "CustomizationID":[{"_":"urn:oasis:names:specification:ubl:xpath:Statement-2.0:sbs-1.0-draft"}],
 "ProfileID":[{"_":"bpid:urn:oasis:names:draft:bpss:ubl-2-sbs-statement-notification-draft"}],
 "ID":[{"_":"JUL2005-07758990"}],
 "CopyIndicator":[{"_":false}],
 "UUID":[{"_":"normalizedString"}],
 "IssueDate":[{"_":"2005-08-02"}],
 "Note":[{"_":"please present invoice if this credit amount cannot be taken against a forthcoming payment"}],
 "DocumentCurrencyCode":[{"_":"GBP"}],
 "TotalDebitAmount":[{"_":0.00,
  "currencyID":"GBP"}],
 "TotalCreditAmount":[{"_":107.50,
  "currencyID":"GBP"}],
 "TotalBalanceAmount":[{"_":-107.50,
  "currencyID":"GBP"}],
 "StatementPeriod":[{
  "StartDate":[{"_":"2005-07-01"}],
  "EndDate":[{"_":"2005-07-31"}],
  "Description":[{"_":"July"}]
 }],
 "AccountingSupplierParty":[{
  "CustomerAssignedAccountID":[{"_":"CO001"}],
  "Party":[{
   "PartyName":[{
    "Name":[{"_":"Consortial"}]
   }],
   "PostalAddress":[{
    "StreetName":[{"_":"Busy Street"}],
    "BuildingName":[{"_":"Thereabouts"}],
    "BuildingNumber":[{"_":"56A"}],
    "CityName":[{"_":"Farthing"}],
    "PostalZone":[{"_":"AA99 1BB"}],
    "CountrySubentity":[{"_":"Heremouthshire"}],
    "AddressLine":[{
     "Line":[{"_":"The Roundabout"}]
    }],
    "Country":[{
     "IdentificationCode":[{"_":"GB"}]
    }]
   }],
   "PartyTaxScheme":[{
    "RegistrationName":[{"_":"Farthing Purchasing Consortium"}],
    "CompanyID":[{"_":"175 269 2355"}],
    "ExemptionReason":[{"_":"N/A"}],
    "TaxScheme":[{
     "ID":[{"_":"VAT"}],
     "TaxTypeCode":[{"_":"VAT"}]
    }]
   }],
   "Contact":[{
    "Name":[{"_":"Mrs Bouquet"}],
    "Telephone":[{"_":"0158 1233714"}],
    "Telefax":[{"_":"0158 1233856"}],
    "ElectronicMail":[{"_":"bouquet@fpconsortial.co.uk"}]
   }]
  }]
 }],
 "AccountingCustomerParty":[{
  "CustomerAssignedAccountID":[{"_":"XFB01"}],
  "SupplierAssignedAccountID":[{"_":"GT00978567"}],
  "Party":[{
   "PartyName":[{
    "Name":[{"_":"IYT Corporation"}]
   }],
   "PostalAddress":[{
    "StreetName":[{"_":"Avon Way"}],
    "BuildingName":[{"_":"Thereabouts"}],
    "BuildingNumber":[{"_":"56A"}],
    "CityName":[{"_":"Bridgtow"}],
    "PostalZone":[{"_":"ZZ99 1ZZ"}],
    "CountrySubentity":[{"_":"Avon"}],
    "AddressLine":[{
     "Line":[{"_":"3rd Floor, Room 5"}]
    }],
    "Country":[{
     "IdentificationCode":[{"_":"GB"}]
    }]
   }],
   "PartyTaxScheme":[{
    "RegistrationName":[{"_":"Bridgtow District Council"}],
    "CompanyID":[{"_":"12356478"}],
    "ExemptionReason":[{"_":"Local Authority"}],
    "TaxScheme":[{
     "ID":[{"_":"UK VAT"}],
     "TaxTypeCode":[{"_":"VAT"}]
    }]
   }],
   "Contact":[{
    "Name":[{"_":"Mr Fred Churchill"}],
    "Telephone":[{"_":"0127 2653214"}],
    "Telefax":[{"_":"0127 2653215"}],
    "ElectronicMail":[{"_":"fred@iytcorporation.gov.uk"}]
   }]
  }]
 }],
 "PayeeParty":[{
  "PartyName":[{
   "Name":[{"_":"Consortial"}]
  }],
  "PostalAddress":[{
   "StreetName":[{"_":"Busy Street"}],
   "BuildingName":[{"_":"Thereabouts"}],
   "BuildingNumber":[{"_":"56A"}],
   "CityName":[{"_":"Farthing"}],
   "PostalZone":[{"_":"AA99 1BB"}],
   "CountrySubentity":[{"_":"Heremouthshire"}],
   "AddressLine":[{
    "Line":[{"_":"The Roundabout"}]
   }],
   "Country":[{
    "IdentificationCode":[{"_":"GB"}]
   }]
  }],
  "PartyTaxScheme":[{
   "RegistrationName":[{"_":"Farthing Purchasing Consortium"}],
   "CompanyID":[{"_":"175 269 2355"}],
   "ExemptionReason":[{"_":"N/A"}],
   "TaxScheme":[{
    "ID":[{"_":"VAT"}],
    "TaxTypeCode":[{"_":"VAT"}]
   }]
  }],
  "Contact":[{
   "Name":[{"_":"Mrs Bouquet"}],
   "Telephone":[{"_":"0158 1233714"}],
   "Telefax":[{"_":"0158 1233856"}],
   "ElectronicMail":[{"_":"bouquet@fpconsortial.co.uk"}]
  }]
 }],
 "PaymentMeans":[{
  "PaymentMeansCode":[{"_":"20"}],
  "PaymentDueDate":[{"_":"2005-07-21"}],
  "PayeeFinancialAccount":[{
   "ID":[{"_":"12345678"}],
   "Name":[{"_":"Farthing Purchasing Consortium"}],
   "AccountTypeCode":[{"_":"Current"}],
   "CurrencyCode":[{"_":"GBP"}],
   "FinancialInstitutionBranch":[{
    "ID":[{"_":"10-26-58"}],
    "Name":[{"_":"Open Bank Ltd, Bridgstow Branch "}],
    "FinancialInstitution":[{
     "ID":[{"_":"10-26-58"}],
     "Name":[{"_":"Open Bank Ltd"}],
     "Address":[{
      "StreetName":[{"_":"City Road"}],
      "BuildingName":[{"_":"Banking House"}],
      "BuildingNumber":[{"_":"12"}],
      "CityName":[{"_":"London"}],
      "PostalZone":[{"_":"AQ1 6TH"}],
      "CountrySubentity":[{"_":"London\n"}],
      "AddressLine":[{
       "Line":[{"_":"5th Floor"}]
      }],
      "Country":[{
       "IdentificationCode":[{"_":"GB"}]
      }]
     }]
    }],
    "Address":[{
     "StreetName":[{"_":"Busy Street"}],
     "BuildingName":[{"_":"The Mall"}],
     "BuildingNumber":[{"_":"152"}],
     "CityName":[{"_":"Farthing"}],
     "PostalZone":[{"_":"AA99 1BB"}],
     "CountrySubentity":[{"_":"Heremouthshire"}],
     "AddressLine":[{
      "Line":[{"_":"West Wing"}]
     }],
     "Country":[{
      "IdentificationCode":[{"_":"GB"}]
     }]
    }]
   }],
   "Country":[{
    "IdentificationCode":[{"_":"GB"}]
   }]
  }]
 }],
 "PaymentTerms":[{
  "Note":[{"_":"Payment due immediately"}]
 }],
 "StatementLine":[{
  "ID":[{"_":"normalizedString"}],
  "Note":[{"_":"String"}],
  "BalanceBroughtForwardIndicator":[{"_":false}],
  "DebitLineAmount":[{"_":0.00,
   "currencyID":"GBP"}],
  "CreditLineAmount":[{"_":107.50,
   "currencyID":"GBP"}],
  "BalanceAmount":[{"_":-107.50,
   "currencyID":"GBP"}],
  "OriginatorCustomerParty":[{
   "Party":[{
    "PartyName":[{
     "Name":[{"_":"The Terminus"}]
    }],
    "PostalAddress":[{
     "StreetName":[{"_":"Avon Way"}],
     "BuildingName":[{"_":"Thereabouts"}],
     "BuildingNumber":[{"_":"56A"}],
     "CityName":[{"_":"Bridgtow"}],
     "PostalZone":[{"_":"ZZ99 1ZZ"}],
     "CountrySubentity":[{"_":"Avon"}],
     "AddressLine":[{
      "Line":[{"_":"3rd Floor, Room 5"}]
     }],
     "Country":[{
      "IdentificationCode":[{"_":"GB"}]
     }]
    }],
    "PartyTaxScheme":[{
     "RegistrationName":[{"_":"Bridgtow District Council"}],
     "CompanyID":[{"_":"12356478"}],
     "ExemptionReason":[{"_":"Local Authority"}],
     "TaxScheme":[{
      "ID":[{"_":"UK VAT"}],
      "TaxTypeCode":[{"_":"VAT"}]
     }]
    }],
    "Contact":[{
     "Name":[{"_":"S Massiah"}],
     "Telephone":[{"_":"0127 98876545"}],
     "Telefax":[{"_":"0127 98876546"}],
     "ElectronicMail":[{"_":"smassiah@the-email.co.uk"}]
    }]
   }]
  }],
  "BillingReference":[{
   "CreditNoteDocumentReference":[{
    "ID":[{"_":"CN758494"}],
    "UUID":[{"_":"349ABBAE-DF9D-40B4-849F-94C5FF9D1AF4"}],
    "IssueDate":[{"_":"2005-06-25"}]
   }]
  }]
 }]
}]}
