=== metasfresh/metasfresh/misc/services/camel/de-metas-camel-externalsystems/com-adekia-exchange/com.adekia.exchange-model/model/UBL-2.3-JSON-v1.0-cn01/json-schema-legacy/maindoc/UBL-InstructionForReturns-2.3.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "json-schema-legacy/maindoc/UBL-InstructionForReturns-2.3.json",
  "description": "\n  Library:           OASIS Universal Business Language (UBL) 2.3 OS\n                     http://docs.oasis-open.org/ubl/os-UBL-2.3/\n  Release Date:      15 June 2021\n  Module:            json-schema-legacy/maindoc/UBL-InstructionForReturns-2.3.json\n  Generated on:      2021-12-15 21:56z\n  Copyright (c) OASIS Open 2021. All Rights Reserved.\n\n\n  OASIS takes no position regarding the validity or scope of any \n  intellectual property or other rights that might be claimed to pertain \n  to the implementation or use of the technology described in this \n  document or the extent to which any license under such rights \n  might or might not be available; neither does it represent that it has \n  made any effort to identify any such rights. Information on OASIS's \n  procedures with respect to rights in OASIS specifications can be \n  found at the OASIS website. Copies of claims of rights made \n  available for publication and any assurances of licenses to be made \n  available, or the result of an attempt made to obtain a general \n  license or permission for the use of such proprietary rights by \n  implementors or users of this specification, can be obtained from \n  the OASIS Executive Director.\n\n  OASIS invites any interested party to bring to its attention any \n  copyrights, patents or patent applications, or other proprietary \n  rights which may cover technology that may be required to \n  implement this specification. Please address the information to the \n  OASIS Executive Director.\n  \n  This document and translations of it may be copied and furnished to \n  others, and derivative works that comment on or otherwise explain \n  it or assist in its implementation may be prepared, copied, \n  published and distributed, in whole or in part, without restriction of \n  any kind, provided that the above copyright notice and this \n  paragraph are included on all such copies and derivative works. \n  However, this document itself may not be modified in any way, \n  such as by removing the copyright notice or references to OASIS, \n  except as needed for the purpose of developing OASIS \n  specifications, in which case the procedures for copyrights defined \n  in the OASIS Intellectual Property Rights document must be \n  followed, or as required to translate it into languages other than \n  English. \n\n  The limited permissions granted above are perpetual and will not be \n  revoked by OASIS or its successors or assigns. \n\n  This document and the information contained herein is provided on \n  an \"AS IS\" basis and OASIS DISCLAIMS ALL WARRANTIES, \n  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO ANY \n  WARRANTY THAT THE USE OF THE INFORMATION HEREIN \n  WILL NOT INFRINGE ANY RIGHTS OR ANY IMPLIED \n  WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A \n  PARTICULAR PURPOSE.    \n",
  "required": [
    "InstructionForReturns"
    ],
  "properties": {
    "_D": {
      "description": "Document ABIE XML namespace string",
      "type": "string"
      },
    "_A": {
      "description": "Library ABIE XML namespace string (for ASBIEs)",
      "type": "string"
      },
    "_B": {
      "description": "BBIE XML namespace string",
      "type": "string"
      },
    "_E": {
      "description": "Extension scaffolding XML namespace string",
      "type": "string"
      },
    "InstructionForReturns": {
      "description": "A document used to initiate a return of goods. The producer is requesting the return of products that are not selling well, either to use in other places or to free up rack or shelf space.",
      "items": {
        "$ref": "#/definitions/InstructionForReturns"
        },
      "maxItems": 1,
      "minItems": 1,
      "type": "array"
      }
    },
  "additionalProperties": false,
  "type": "object",
  "definitions": {
    "InstructionForReturns": {
      "title": "Instruction For Returns. Details",
      "description": "A document used to initiate a return of goods. The producer is requesting the return of products that are not selling well, either to use in other places or to free up rack or shelf space.",
      "required": [
        "ID",
        "IssueDate",
        "SellerSupplierParty",
        "RetailerCustomerParty",
        "InstructionForReturnsLine"
        ],
      "properties": {

        "UBLExtensions": {
          "title": "UBLExtensions",
          "description": "An optional set of extensions to the committee model",
          "items": { 
            "$ref": "../common/UBL-CommonExtensionComponents-2.3.json#/definitions/UBLExtensions" },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },

        "UBLVersionID": {
          "title": "Instruction For Returns. UBL Version Identifier. Identifier",
          "description": "Identifies the earliest version of the UBL 2 schema for this document type that defines all of the elements that might be encountered in the current instance.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/UBLVersionID"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "CustomizationID": {
          "title": "Instruction For Returns. Customization Identifier. Identifier",
          "description": "Identifies a user-defined customization of UBL for a specific use.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/CustomizationID"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "ProfileID": {
          "title": "Instruction For Returns. Profile Identifier. Identifier",
          "description": "Identifies a user-defined profile of the customization of UBL being used.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ProfileID"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "ProfileExecutionID": {
          "title": "Instruction For Returns. Profile Execution Identifier. Identifier",
          "description": "Identifies an instance of executing a profile, to associate all transactions in a collaboration.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ProfileExecutionID"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "ID": {
          "title": "Instruction For Returns. Identifier",
          "description": "An identifier for this document, assigned by the sender.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ID"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "CopyIndicator": {
          "title": "Instruction For Returns. Copy_ Indicator. Indicator",
          "description": "Indicates whether this document is a copy (true) or not (false).",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/CopyIndicator"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "UUID": {
          "title": "Instruction For Returns. UUID. Identifier",
          "description": "A universally unique identifier for an instance of this document.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/UUID"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "IssueDate": {
          "title": "Instruction For Returns. Issue Date. Date",
          "description": "The date, assigned by the sender, on which this document was issued.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/IssueDate"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "IssueTime": {
          "title": "Instruction For Returns. Issue Time. Time",
          "description": "The time, assigned by the sender, at which this document was issued.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/IssueTime"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "Note": {
          "title": "Instruction For Returns. Note. Text",
          "description": "Free-form text pertinent to this document, conveying information that is not contained explicitly in other structures.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/Note"
            },
          "minItems": 1,
          "type": "array"
          },
        "DocumentReference": {
          "title": "Instruction For Returns. Document Reference",
          "description": "A reference to another document associated with this document.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/DocumentReference"
            },
          "minItems": 1,
          "type": "array"
          },
        "Signature": {
          "title": "Instruction For Returns. Signature",
          "description": "A signature applied to this document.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/Signature"
            },
          "minItems": 1,
          "type": "array"
          },
        "SellerSupplierParty": {
          "title": "Instruction For Returns. Seller_ Supplier Party. Supplier Party",
          "description": "The seller.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/SellerSupplierParty"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "RetailerCustomerParty": {
          "title": "Instruction For Returns. Retailer_ Customer Party. Customer Party",
          "description": "The retailer.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/RetailerCustomerParty"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "ManufacturerParty": {
          "title": "Instruction For Returns. Manufacturer_ Party. Party",
          "description": "The manufacturer.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/ManufacturerParty"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "Shipment": {
          "title": "Instruction For Returns. Shipment",
          "description": "The shipment.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/Shipment"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "InstructionForReturnsLine": {
          "title": "Instruction For Returns. Instruction For Returns Line",
          "description": "A line providing details about one type of article to be returned.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/InstructionForReturnsLine"
            },
          "minItems": 1,
          "type": "array"
          }
        },
      "additionalProperties": false,
      "type": "object"
      }
    }
  }

=== metasfresh/metasfresh/misc/services/camel/de-metas-camel-externalsystems/com-adekia-exchange/com.adekia.exchange-model/model/UBL-2.3-JSON-v1.0-cn01/json-legacy/UBL-InstructionForReturns-2.1-Example.json
{"_D":"urn:oasis:names:specification:ubl:schema:xsd:InstructionForReturns-2",
 "_A":"urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2",
 "_B":"urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2",
 "InstructionForReturns":[{
 "UBLVersionID":[{"_":"2.1"}],
 "ID":[{"_":"AB011"}],
 "CopyIndicator":[{"_":false}],
 "IssueDate":[{"_":"2010-04-10"}],
 "Note":[{"_":"Instruction to return goods that are badly sent to you."}],
 "SellerSupplierParty":[{
  "Party":[{
   "PartyName":[{
    "Name":[{"_":"Arancio Forniture spa"}]
   }],
   "PostalAddress":[{
    "StreetName":[{"_":"Via Dell'Arcoveggio"}],
    "BuildingNumber":[{"_":"403"}],
    "CityName":[{"_":"Bologna"}],
    "PostalZone":[{"_":"40129"}],
    "Country":[{
     "IdentificationCode":[{"_":"IT"}],
     "Name":[{"_":"Italy"}]
    }]
   }],
   "Contact":[{
    "Name":[{"_":"Mr Rossi"}],
    "Telephone":[{"_":"0039 051 23000000"}],
    "Telefax":[{"_":"0039 051 23000023"}],
    "ElectronicMail":[{"_":"rossi@arancioforniture.it"}]
   }]
  }]
 }],
 "RetailerCustomerParty":[{
  "Party":[{
   "PartyName":[{
    "Name":[{"_":"Beta Shop"}]
   }],
   "PostalAddress":[{
    "StreetName":[{"_":"Via Emilia"}],
    "BuildingNumber":[{"_":"1"}],
    "CityName":[{"_":"Modena"}],
    "PostalZone":[{"_":"41121"}],
    "Country":[{
     "IdentificationCode":[{"_":"IT"}],
     "Name":[{"_":"Italy"}]
    }]
   }],
   "Contact":[{
    "Name":[{"_":"Mr Delta"}],
    "Telephone":[{"_":"0039 059 33000000"}],
    "Telefax":[{"_":"0039 059 33000055"}],
    "ElectronicMail":[{"_":"delta@betashop.it"}]
   }]
  }]
 }],
 "ManufacturerParty":[{
  "PartyName":[{
   "Name":[{"_":"AZ Outsourcing srl"}]
  }],
  "PostalAddress":[{
   "StreetName":[{"_":"Via Bolognese"}],
   "BuildingNumber":[{"_":"199"}],
   "CityName":[{"_":"Bologna"}],
   "PostalZone":[{"_":"40129"}],
   "Country":[{
    "IdentificationCode":[{"_":"IT"}],
    "Name":[{"_":"Italy"}]
   }]
  }],
  "Contact":[{
   "Name":[{"_":"Mr Verdi"}],
   "Telephone":[{"_":"0039 051 25400000"}],
   "Telefax":[{"_":"0039 051 25400023"}],
   "ElectronicMail":[{"_":"verdi@azoutsourcing.it"}]
  }]
 }],
 "Shipment":[{
  "ID":[{"_":"51022"}],
  "Consignment":[{
   "ID":[{"_":"510"}]
  }],
  "Delivery":[{
   "DeliveryAddress":[{
    "StreetName":[{"_":"Via Dell'Arcoveggio"}],
    "BuildingNumber":[{"_":"403"}],
    "CityName":[{"_":"Bologna"}],
    "PostalZone":[{"_":"40129"}],
    "Country":[{
     "IdentificationCode":[{"_":"IT"}],
     "Name":[{"_":"Italy"}]
    }]
   }],
   "Despatch":[{
    "DespatchAddress":[{
     "StreetName":[{"_":"Via Emilia"}],
     "BuildingNumber":[{"_":"1"}],
     "CityName":[{"_":"Modena"}],
     "PostalZone":[{"_":"41121"}],
     "Country":[{
      "IdentificationCode":[{"_":"IT"}],
      "Name":[{"_":"Italy"}]
     }]
    }]
   }]
  }]
 }],
 "InstructionForReturnsLine":[{
  "ID":[{"_":"1"}],
  "Quantity":[{"_":20,
   "unitCode":"NAR"}],
  "Item":[{
   "Description":[{"_":"Denim Jeans Jacket"}],
   "Name":[{"_":"Jeans Jacket man"}],
   "BuyersItemIdentification":[{
    "ID":[{"_":"AA109"}]
   }],
   "SellersItemIdentification":[{
    "ID":[{"_":"YX401"}]
   }]
  }]
 },{
  "ID":[{"_":"2"}],
  "Quantity":[{"_":5,
   "unitCode":"NAR"}],
  "Item":[{
   "Description":[{"_":"Leather Jacket"}],
   "Name":[{"_":"Leather Jacket man"}],
   "BuyersItemIdentification":[{
    "ID":[{"_":"AA128"}]
   }],
   "SellersItemIdentification":[{
    "ID":[{"_":"YX233"}]
   }]
  }]
 }]
}]}
