=== metasfresh/metasfresh/misc/services/camel/de-metas-camel-externalsystems/com-adekia-exchange/com.adekia.exchange-model/model/UBL-2.3-JSON-v1.0-cn01/json-schema-legacy/maindoc/UBL-ExpressionOfInterestRequest-2.3.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "json-schema-legacy/maindoc/UBL-ExpressionOfInterestRequest-2.3.json",
  "description": "\n  Library:           OASIS Universal Business Language (UBL) 2.3 OS\n                     http://docs.oasis-open.org/ubl/os-UBL-2.3/\n  Release Date:      15 June 2021\n  Module:            json-schema-legacy/maindoc/UBL-ExpressionOfInterestRequest-2.3.json\n  Generated on:      2021-12-15 21:56z\n  Copyright (c) OASIS Open 2021. All Rights Reserved.\n\n\n  OASIS takes no position regarding the validity or scope of any \n  intellectual property or other rights that might be claimed to pertain \n  to the implementation or use of the technology described in this \n  document or the extent to which any license under such rights \n  might or might not be available; neither does it represent that it has \n  made any effort to identify any such rights. Information on OASIS's \n  procedures with respect to rights in OASIS specifications can be \n  found at the OASIS website. Copies of claims of rights made \n  available for publication and any assurances of licenses to be made \n  available, or the result of an attempt made to obtain a general \n  license or permission for the use of such proprietary rights by \n  implementors or users of this specification, can be obtained from \n  the OASIS Executive Director.\n\n  OASIS invites any interested party to bring to its attention any \n  copyrights, patents or patent applications, or other proprietary \n  rights which may cover technology that may be required to \n  implement this specification. Please address the information to the \n  OASIS Executive Director.\n  \n  This document and translations of it may be copied and furnished to \n  others, and derivative works that comment on or otherwise explain \n  it or assist in its implementation may be prepared, copied, \n  published and distributed, in whole or in part, without restriction of \n  any kind, provided that the above copyright notice and this \n  paragraph are included on all such copies and derivative works. \n  However, this document itself may not be modified in any way, \n  such as by removing the copyright notice or references to OASIS, \n  except as needed for the purpose of developing OASIS \n  specifications, in which case the procedures for copyrights defined \n  in the OASIS Intellectual Property Rights document must be \n  followed, or as required to translate it into languages other than \n  English. \n\n  The limited permissions granted above are perpetual and will not be \n  revoked by OASIS or its successors or assigns. \n\n  This document and the information contained herein is provided on \n  an \"AS IS\" basis and OASIS DISCLAIMS ALL WARRANTIES, \n  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO ANY \n  WARRANTY THAT THE USE OF THE INFORMATION HEREIN \n  WILL NOT INFRINGE ANY RIGHTS OR ANY IMPLIED \n  WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A \n  PARTICULAR PURPOSE.    \n",
  "required": [
    "ExpressionOfInterestRequest"
    ],
  "properties": {
    "_D": {
      "description": "Document ABIE XML namespace string",
      "type": "string"
      },
    "_A": {
      "description": "Library ABIE XML namespace string (for ASBIEs)",
      "type": "string"
      },
    "_B": {
      "description": "BBIE XML namespace string",
      "type": "string"
      },
    "_E": {
      "description": "Extension scaffolding XML namespace string",
      "type": "string"
      },
    "ExpressionOfInterestRequest": {
      "description": "An expression of interest to a tendering process. An Economic Operator can demonstrate interest in a tendering process issuing an Expression Of Interest document to the contracting party. Upon reception, the Contracting Party registers the interest of the Economic Operator sending the relevant information for the tendering process.",
      "items": {
        "$ref": "#/definitions/ExpressionOfInterestRequest"
        },
      "maxItems": 1,
      "minItems": 1,
      "type": "array"
      }
    },
  "additionalProperties": false,
  "type": "object",
  "definitions": {
    "ExpressionOfInterestRequest": {
      "title": "Expression Of Interest Request. Details",
      "description": "An expression of interest to a tendering process. An Economic Operator can demonstrate interest in a tendering process issuing an Expression Of Interest document to the contracting party. Upon reception, the Contracting Party registers the interest of the Economic Operator sending the relevant information for the tendering process.",
      "required": [
        "ID",
        "IssueDate",
        "EconomicOperatorParty",
        "ContractingParty"
        ],
      "properties": {

        "UBLExtensions": {
          "title": "UBLExtensions",
          "description": "An optional set of extensions to the committee model",
          "items": { 
            "$ref": "../common/UBL-CommonExtensionComponents-2.3.json#/definitions/UBLExtensions" },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },

        "UBLVersionID": {
          "title": "Expression Of Interest Request. UBL Version Identifier. Identifier",
          "description": "The earliest version of the UBL 2 schema for this document type that defines all of the elements that might be encountered in the current instance.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/UBLVersionID"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "CustomizationID": {
          "title": "Expression Of Interest Request. Customization Identifier. Identifier",
          "description": "Identifies a user-defined customization of UBL for a specific use.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/CustomizationID"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "ProfileID": {
          "title": "Expression Of Interest Request. Profile Identifier. Identifier",
          "description": "Identifies a user-defined profile of the customization of UBL being used.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ProfileID"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "ProfileExecutionID": {
          "title": "Expression Of Interest Request. Profile Execution Identifier. Identifier",
          "description": "Identifies an instance of executing a profile, to associate all transactions in a collaboration.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ProfileExecutionID"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "ID": {
          "title": "Expression Of Interest Request. Identifier",
          "description": "An identifier for this document, assigned by the sender.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ID"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "CopyIndicator": {
          "title": "Expression Of Interest Request. Copy_ Indicator. Indicator",
          "description": "Indicates whether this document is a copy (true) or not (false).",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/CopyIndicator"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "UUID": {
          "title": "Expression Of Interest Request. UUID. Identifier",
          "description": "A universally unique identifier for an instance of this document.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/UUID"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "ContractFolderID": {
          "title": "Expression Of Interest Request. Contract Folder Identifier. Identifier",
          "description": "An identifier, assigned by the sender, for the process file (i.e., record) to which this document belongs.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ContractFolderID"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "IssueDate": {
          "title": "Expression Of Interest Request. Issue Date. Date",
          "description": "The date, assigned by the sender, on which this document was issued.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/IssueDate"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "IssueTime": {
          "title": "Expression Of Interest Request. Issue Time. Time",
          "description": "The time, assigned by the sender, at which this document was issued.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/IssueTime"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "ContractName": {
          "title": "Expression Of Interest Request. Contract Name. Name",
          "description": "Short title of a contract associated with this Expression of Interest.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ContractName"
            },
          "minItems": 1,
          "type": "array"
          },
        "PreferredLanguageLocaleCode": {
          "title": "Expression Of Interest Request. Preferred Language_ Locale Code. Code",
          "description": "A code signifying the locale in which the language in the required documents is preferred.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/PreferredLanguageLocaleCode"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "Note": {
          "title": "Expression Of Interest Request. Note. Text",
          "description": "Free-form text pertinent to this document, conveying information that is not contained explicitly in other structures.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/Note"
            },
          "minItems": 1,
          "type": "array"
          },
        "ValidityPeriod": {
          "title": "Expression Of Interest Request. Validity_ Period. Period",
          "description": "The period for which the expression of interest is valid.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/ValidityPeriod"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "DocumentReference": {
          "title": "Expression Of Interest Request. Document Reference",
          "description": "A reference to another document associated with this document.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/DocumentReference"
            },
          "minItems": 1,
          "type": "array"
          },
        "Signature": {
          "title": "Expression Of Interest Request. Signature",
          "description": "A signature applied to this document.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/Signature"
            },
          "minItems": 1,
          "type": "array"
          },
        "EconomicOperatorParty": {
          "title": "Expression Of Interest Request. Economic Operator Party",
          "description": "The Economic Operator issuing the expression of interest.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/EconomicOperatorParty"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "ContractingParty": {
          "title": "Expression Of Interest Request. Contracting Party",
          "description": "The Contracting Party or the contracting parties in case of joint procurement.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/ContractingParty"
            },
          "minItems": 1,
          "type": "array"
          },
        "ProcurementProject": {
          "title": "Expression Of Interest Request. Procurement Project",
          "description": "An overall definition of this procurement project.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/ProcurementProject"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "ProcurementProjectLotReference": {
          "title": "Expression Of Interest Request. Procurement Project Lot Reference",
          "description": "One of the procurement project lots into which this contract can be split.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/ProcurementProjectLotReference"
            },
          "minItems": 1,
          "type": "array"
          }
        },
      "additionalProperties": false,
      "type": "object"
      }
    }
  }

=== metasfresh/metasfresh/misc/services/camel/de-metas-camel-externalsystems/com-adekia-exchange/com.adekia.exchange-model/model/UBL-2.3-JSON-v1.0-cn01/json-legacy/UBL-ExpressionOfInterestRequest-2.2-Example.json
{"_D":"urn:oasis:names:specification:ubl:schema:xsd:ExpressionOfInterestRequest-2",
 "_A":"urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2",
 "_B":"urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2",
 "ExpressionOfInterestRequest":[{
 "UBLVersionID":[{"_":"2.2"}],
 "CustomizationID":[{"_":"urn:www.cenbii.eu:transaction:BiiTrns081:ver2.0"}],
 "ProfileID":[{"_":"urn:www.cenbii.eu:profile:bii46:ver2.0"}],
 "ID":[{"_":"234486-2017"}],
 "UUID":[{"_":"x2344vghjjrhhfhrrrgd4567"}],
 "ContractFolderID":[{"_":"2017/S 214-3792289"}],
 "IssueDate":[{"_":"2017-10-16"}],
 "IssueTime":[{"_":"17:30:00+01:00"}],
 "Note":[{"_":"We are very interested please send us all information possible"}],
 "EconomicOperatorParty":[{
  "Party":[{
   "WebsiteURI":[{"_":"http://super.company.dk"}],
   "EndpointID":[{"_":"01842222222222",
    "schemeAgencyID":"9",
    "schemeID":"FI:OVT"}],
   "PartyIdentification":[{
    "ID":[{"_":"5790000127777",
     "schemeAgencyID":"9",
     "schemeID":"GLN"}]
   }],
   "PartyName":[{
    "Name":[{"_":"SuperCompany"}]
   }],
   "PostalAddress":[{
    "AddressFormatCode":[{"_":"Structured",
     "listAgencyID":"700",
     "listID":"CENBII3"}],
    "StreetName":[{"_":"Korsbygade 34"}],
    "CityName":[{"_":"Aalborg"}],
    "PostalZone":[{"_":"9000"}],
    "Country":[{
     "IdentificationCode":[{"_":"DK"}]
    }]
   }],
   "PartyLegalEntity":[{
    "RegistrationName":[{"_":"SuperCompany"}],
    "CompanyID":[{"_":"DK59873677",
     "schemeID":"DK:CVR"}]
   }],
   "Contact":[{
    "ID":[{"_":"7778"}],
    "Name":[{"_":"Ole Hansen"}],
    "Telephone":[{"_":"4526532147"}],
    "Telefax":[{"_":"4526532146"}],
    "ElectronicMail":[{"_":"Ole@super.company.dk"}]
   }]
  }]
 }],
 "ContractingParty":[{
  "Party":[{
   "EndpointID":[{"_":"01841111111111",
    "schemeID":"FI:OVT"}],
   "PartyIdentification":[{
    "ID":[{"_":"5398000392577",
     "schemeAgencyID":"9",
     "schemeID":"GLN"}]
   }],
   "PartyName":[{
    "Name":[{"_":"FirstAgency"}]
   }],
   "Contact":[{
    "Name":[{"_":"Ole Ellerb√¶k Madsen"}]
   }]
  }]
 }],
 "ProcurementProject":[{
  "ID":[{"_":"DP"}],
  "Name":[{"_":"DigitalPost"}],
  "Description":[{"_":"Only Lot2"}]
 }],
 "ProcurementProjectLotReference":[{
  "ID":[{"_":"Lot2"}]
 }]
}]}
