=== metasfresh/metasfresh/misc/services/camel/de-metas-camel-externalsystems/com-adekia-exchange/com.adekia.exchange-model/model/UBL-2.3-JSON-v1.0-cn01/json-schema-legacy/maindoc/UBL-DigitalCapability-2.3.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "json-schema-legacy/maindoc/UBL-DigitalCapability-2.3.json",
  "description": "\n  Library:           OASIS Universal Business Language (UBL) 2.3 OS\n                     http://docs.oasis-open.org/ubl/os-UBL-2.3/\n  Release Date:      15 June 2021\n  Module:            json-schema-legacy/maindoc/UBL-DigitalCapability-2.3.json\n  Generated on:      2021-12-15 21:56z\n  Copyright (c) OASIS Open 2021. All Rights Reserved.\n\n\n  OASIS takes no position regarding the validity or scope of any \n  intellectual property or other rights that might be claimed to pertain \n  to the implementation or use of the technology described in this \n  document or the extent to which any license under such rights \n  might or might not be available; neither does it represent that it has \n  made any effort to identify any such rights. Information on OASIS's \n  procedures with respect to rights in OASIS specifications can be \n  found at the OASIS website. Copies of claims of rights made \n  available for publication and any assurances of licenses to be made \n  available, or the result of an attempt made to obtain a general \n  license or permission for the use of such proprietary rights by \n  implementors or users of this specification, can be obtained from \n  the OASIS Executive Director.\n\n  OASIS invites any interested party to bring to its attention any \n  copyrights, patents or patent applications, or other proprietary \n  rights which may cover technology that may be required to \n  implement this specification. Please address the information to the \n  OASIS Executive Director.\n  \n  This document and translations of it may be copied and furnished to \n  others, and derivative works that comment on or otherwise explain \n  it or assist in its implementation may be prepared, copied, \n  published and distributed, in whole or in part, without restriction of \n  any kind, provided that the above copyright notice and this \n  paragraph are included on all such copies and derivative works. \n  However, this document itself may not be modified in any way, \n  such as by removing the copyright notice or references to OASIS, \n  except as needed for the purpose of developing OASIS \n  specifications, in which case the procedures for copyrights defined \n  in the OASIS Intellectual Property Rights document must be \n  followed, or as required to translate it into languages other than \n  English. \n\n  The limited permissions granted above are perpetual and will not be \n  revoked by OASIS or its successors or assigns. \n\n  This document and the information contained herein is provided on \n  an \"AS IS\" basis and OASIS DISCLAIMS ALL WARRANTIES, \n  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO ANY \n  WARRANTY THAT THE USE OF THE INFORMATION HEREIN \n  WILL NOT INFRINGE ANY RIGHTS OR ANY IMPLIED \n  WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A \n  PARTICULAR PURPOSE.    \n",
  "required": [
    "DigitalCapability"
    ],
  "properties": {
    "_D": {
      "description": "Document ABIE XML namespace string",
      "type": "string"
      },
    "_A": {
      "description": "Library ABIE XML namespace string (for ASBIEs)",
      "type": "string"
      },
    "_B": {
      "description": "BBIE XML namespace string",
      "type": "string"
      },
    "_E": {
      "description": "Extension scaffolding XML namespace string",
      "type": "string"
      },
    "DigitalCapability": {
      "description": "A document used to provide information about a business party and its digital trade capabilities.",
      "items": {
        "$ref": "#/definitions/DigitalCapability"
        },
      "maxItems": 1,
      "minItems": 1,
      "type": "array"
      }
    },
  "additionalProperties": false,
  "type": "object",
  "definitions": {
    "DigitalCapability": {
      "title": "Digital Capability. Details",
      "description": "A document used to provide information about a business party and its digital trade capabilities.",
      "required": [
        "ID",
        "IssueDate",
        "BusinessParty",
        "DigitalProcess"
        ],
      "properties": {

        "UBLExtensions": {
          "title": "UBLExtensions",
          "description": "An optional set of extensions to the committee model",
          "items": { 
            "$ref": "../common/UBL-CommonExtensionComponents-2.3.json#/definitions/UBLExtensions" },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },

        "UBLVersionID": {
          "title": "Digital Capability. UBL Version Identifier. Identifier",
          "description": "Identifies the earliest version of the UBL 2 schema for this document type that defines all of the elements that might be encountered in the current instance.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/UBLVersionID"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "CustomizationID": {
          "title": "Digital Capability. Customization Identifier. Identifier",
          "description": "Identifies a user-defined customization of UBL for a specific use.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/CustomizationID"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "ProfileID": {
          "title": "Digital Capability. Profile Identifier. Identifier",
          "description": "Identifies a user-defined profile of the customization of UBL being used.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ProfileID"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "ProfileExecutionID": {
          "title": "Digital Capability. Profile Execution Identifier. Identifier",
          "description": "Identifies an instance of executing a profile, to associate all transactions in a collaboration.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ProfileExecutionID"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "ID": {
          "title": "Digital Capability. Identifier",
          "description": "An identifier for this document, assigned by the sender.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/ID"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "UUID": {
          "title": "Digital Capability. UUID. Identifier",
          "description": "A universally unique identifier for an instance of this document.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/UUID"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "IssueDate": {
          "title": "Digital Capability. Issue Date. Date",
          "description": "The date, assigned by the sender, on which this document was issued.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/IssueDate"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "IssueTime": {
          "title": "Digital Capability. Issue Time. Time",
          "description": "The time, assigned by the sender, at which this document was issued.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/IssueTime"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "VersionID": {
          "title": "Digital Capability. Version Identifier. Identifier",
          "description": "Identifies the current version of party's digital capabilities.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/VersionID"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "PreviousVersionID": {
          "title": "Digital Capability. Previous Version Identifier. Identifier",
          "description": "Identifies the previous version of party's digital capabilities.",
          "items": {
            "$ref": "../common/UBL-CommonBasicComponents-2.3.json#/definitions/PreviousVersionID"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "Signature": {
          "title": "Digital Capability. Signature",
          "description": "A signature applied to this document.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/Signature"
            },
          "minItems": 1,
          "type": "array"
          },
        "SenderParty": {
          "title": "Digital Capability. Sender_ Party. Party",
          "description": "The party sending these digital capabilities. This party could be the owner of these digital capabilities or a third-party acting on behalf of the owner (e.g. service provider).",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/SenderParty"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "ReceiverParty": {
          "title": "Digital Capability. Receiver_ Party. Party",
          "description": "The party receiving these digital capabilities.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/ReceiverParty"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "BusinessParty": {
          "title": "Digital Capability. Business_ Party. Party",
          "description": "The party owning these digital capabilities.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/BusinessParty"
            },
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
          },
        "DigitalProcess": {
          "title": "Digital Capability. Digital Process",
          "description": "The digital trade processes supported by the party.",
          "items": {
            "$ref": "../common/UBL-CommonAggregateComponents-2.3.json#/definitions/DigitalProcess"
            },
          "minItems": 1,
          "type": "array"
          }
        },
      "additionalProperties": false,
      "type": "object"
      }
    }
  }

=== metasfresh/metasfresh/misc/services/camel/de-metas-camel-externalsystems/com-adekia-exchange/com.adekia.exchange-model/model/UBL-2.3-JSON-v1.0-cn01/json-legacy/UBL-DigitalCapability-2.2-Example.json
{"_D":"urn:oasis:names:specification:ubl:schema:xsd:DigitalCapability-2",
 "_A":"urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2",
 "_B":"urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2",
 "DigitalCapability":[{
 "UBLVersionID":[{"_":"2.2"}],
 "ID":[{"_":"C12345-2016"}],
 "IssueDate":[{"_":"2016-11-07"}],
 "VersionID":[{"_":"1.1"}],
 "PreviousVersionID":[{"_":"1.0"}],
 "SenderParty":[{
  "EndpointID":[{"_":"1234567987654",
   "schemeID":"GLN",
   "schemeAgencyID":"9"}],
  "PartyIdentification":[{
   "ID":[{"_":"DK12345678",
    "schemeID":"DK:CVR"}]
  }],
  "PartyName":[{
   "Name":[{"_":"Papir√∏en Food ApS"}]
  }],
  "PostalAddress":[{
   "StreetName":[{"_":"Trangravsvej"}],
   "BuildingNumber":[{"_":"12"}],
   "CityName":[{"_":"Copenhagen"}],
   "Country":[{
    "IdentificationCode":[{"_":"DK"}]
   }]
  }]
 }],
 "BusinessParty":[{
  "EndpointID":[{"_":"9994567987654",
   "schemeID":"GLN",
   "schemeAgencyID":"9"}],
  "PartyIdentification":[{
   "ID":[{"_":"IT01234567890",
    "schemeID":"IT:VAT"}]
  }],
  "PartyName":[{
   "Name":[{"_":"Slow Food Srl"}]
  }],
  "PostalAddress":[{
   "CityName":[{"_":"La Spezia"}],
   "Country":[{
    "IdentificationCode":[{"_":"IT"}]
   }]
  }]
 }],
 "DigitalProcess":[{
  "ID":[{"_":"urn:www.cenbii.eu:profile:bii05:ver2.0"}],
  "ProfileID":[{"_":"BII"}],
  "DigitalCollaboration":[{
   "ID":[{"_":"1"}],
   "SendingDigitalService":[{
    "ID":[{"_":"Invoice"}],
    "CustomizationID":[{"_":"urn:www.cenbii.eu:transaction:biitrns010:ver2.0:extended:urn:www.peppol.eu:bis:peppol5a:ver2.0"}],
    "DigitalDocumentMetadata":[{
     "FormatID":[{"_":"UBL"}],
     "VersionID":[{"_":"2.2"}],
     "SchemaURI":[{"_":"urn:oasis:names:specification:ubl:schema:xsd:Invoice-2"}],
     "DocumentTypeCode":[{"_":"380",
      "listAgencyID":"6",
      "listID":"UN/ECE 1001"}]
    }],
    "DigitalDeliveryChannel":[{
     "NetworkID":[{"_":"OpenPEPPOL"}],
     "ParticipantID":[{"_":"1234567987654",
      "schemeAgencyID":"9",
      "schemeID":"GLN"}],
     "TestIndicator":[{"_":true}],
     "DigitalMessageDelivery":[{
      "ProtocolID":[{"_":"AS2"}],
      "EndpointURI":[{"_":"http://as2.papifood.dk"}]
     }]
    }]
   }],
   "ReceivingDigitalService":[{
    "ID":[{"_":"CreditNote"}],
    "CustomizationID":[{"_":"urn:www.cenbii.eu:transaction:biitrns014:ver2.0:extended:urn:www.peppol.eu:bis:peppol5a:ver2.0"}],
    "DigitalDocumentMetadata":[{
     "FormatID":[{"_":"UBL"}],
     "VersionID":[{"_":"2.2"}],
     "SchemaURI":[{"_":"urn:oasis:names:specification:ubl:schema:xsd:CreditNote-2"}],
     "DocumentTypeCode":[{"_":"381",
      "listAgencyID":"6",
      "listID":"UN/ECE 1001"}]
    }],
    "DigitalDeliveryChannel":[{
     "NetworkID":[{"_":"OpenPEPPOL"}],
     "ParticipantID":[{"_":"1234567987654",
      "schemeAgencyID":"9",
      "schemeID":"GLN"}],
     "DigitalMessageDelivery":[{
      "ProtocolID":[{"_":"AS2"}],
      "EndpointURI":[{"_":"http://as2.papifood.dk"}]
     }]
    }]
   }]
  }]
 }]
}]}
